redis/RedisInsight

- redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss
#RI-1902 - fix encryption error background
> Fix/ Encryption error background

- redisinsight/ui/src/pages/home/components/HelpLinksMenu/HelpLinksMenu.tsx
- redisinsight/ui/src/pages/home/components/HelpLinksMenu/styles.module.scss
#RI-2059 - fix styles for HelpLinksMenu
> Fix/ HelpLinksMenu styles

- redisinsight/api/src/modules/core/services/redis/redis.service.ts
#RI-2003 - catch the lastNodeError for the cluster if it exists
> Fix/ Cluster Node Error

- redisinsight/ui/src/pages/home/HomePage.tsx
add a missing event handler for the DatabaseList component
> Fix/ DB deletion notification

- redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementAreaWrapper.tsx
added testid for Enablement area wrapper
> added testid for Enablement area wrapper

- tests/e2e/pageObjects/workbench-page.ts
- tests/e2e/tests/regression/workbench/default-scripts-area.e2e.ts
Fixing failed tests:
- Verify that user can expand/collapse the enablement area - fix
- Verify that user can resize(maximize)/(minimize) the enablement area - deleted as obsolet after requirements and code changes
> [E2E] Fix failed tests with Enablement area

- redisinsight/api/src/modules/cli/dto/cli.dto.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.spec.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
- redisinsight/api/src/modules/cli/services/cli-tool/cli-tool.service.ts
- redisinsight/api/test/api/cli/POST-instance-id-cli-uuid-send_cluster_command.test.ts
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts
- redisinsight/ui/src/utils/cliHelper.tsx
- redisinsight/ui/src/utils/cliTextFormatter.ts
#RI-2156 - display redirection message in CLI
> Fix/ CLI Redirection message

- redisinsight/api/config/production.ts
- redisinsight/api/config/staging.ts
allow defining APP FOLDER NAME by using env variable only for production
> Fix/ Folder name for settings on prod

- .circleci/config.yml
- redisinsight/main.dev.ts
Also possibility for updates for any build environment if "manual" environment variable defined
> #RI-1841 - add support for auto updates to stage builds

- redisinsight/ui/src/components/query/Query/Query.tsx
- redisinsight/ui/src/pages/workbench/interfaces.ts
* #RI-1981 - Using enter or space user is still inside of printing command
> * #RI-1981 - Using enter or space user is still inside of printing command

- redisinsight/api/config/default.ts
- redisinsight/api/config/production.ts
- redisinsight/api/src/modules/shared/services/redis-cloud-business/redis-cloud-business.service.ts
- redisinsight/api/test/helpers/constants.ts
#RI-2242 - update REDIS_CLOUD_URL for dev and stage configs
> Fix/ Update URL to Redis Cloud API

- redisinsight/ui/src/components/bottom-group-components/styles.module.scss
- redisinsight/ui/src/components/database-list-modules/styles.module.scss
- redisinsight/ui/src/pages/workbench/components/module-not-loaded/styles.module.scss
#RI-2247 - remove system tooltips for cli & ch badges
#RI-2248 - fix custom modules icons
#RI-2249 - fix text wrapping for module not loaded [redisearch]
> #RI-2247, #RI-2248, #RI-2249

- redisinsight/api/src/modules/shared/services/instances-business/instances-analytics.service.spec.ts
- redisinsight/api/src/modules/shared/services/instances-business/instances-analytics.service.ts
- redisinsight/api/src/utils/analytics-helper.ts
- redisinsight/api/src/utils/redis-modules-summary.spec.ts
- redisinsight/api/src/utils/redis-modules-summary.ts
* #RI-2115 - reorganize the list of modules
> Feature/ List of modules for telemetry

- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
- redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/InternalPage/InternalPage.tsx
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/slices/cli/cli-settings.ts
- redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts
#RI-2311 - monitor command in the unsupported list
> Fix/ Monitor in unsupported list

- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/InternalPage/InternalPage.tsx
#RI-2322 - fix anchor navigation for electronic app
> fix/ Footnotes navigation

- redisinsight/ui/src/components/command-helper/CommandHelper/CommandHelper.tsx
- redisinsight/ui/src/constants/commands.ts
- redisinsight/ui/src/utils/commands.ts
- redisinsight/ui/src/utils/monacoRedisComplitionProvider.ts
- redisinsight/ui/src/utils/tests/commands.spec.ts
#RI-2252 - Add additional commands.json files RedisGears and RedisBloom
> #RI-2252 - Add additional commands.json

- redisinsight/main.dev.ts
> add icon to splash screen

- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
- redisinsight/ui/src/components/cli/components/cli-header/CliHeader.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInput/CliInput.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInput/CliInput.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInputWrapper.tsx
- redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
- redisinsight/ui/src/constants/apiErrors.ts
- redisinsight/ui/src/constants/cliOutput.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/pages/sentinelDatabases/SentinelDatabasesPage.tsx
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/slices/cli/cli-settings.ts
- redisinsight/ui/src/slices/interfaces/cli.ts
- redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts
- redisinsight/ui/src/slices/tests/cli/cli-settings.spec.ts
- redisinsight/ui/src/utils/cliHelper.tsx
- redisinsight/ui/src/utils/tests/cliHelper.spec.ts
* #RI-2122 - update messages
* #RI-2122 - display selected db index in cli
* #RI-2122 - create a new client if the previous one was closed
> Improve/ CLI selected db index

- redisinsight/main.dev.ts
- redisinsight/splash.html
- redisinsight/ui/src/electron/constants/ipcEvent.ts
#RI-2250 - Previous app version is displayed on splash screen when application version is updated
> #RI-2250 - Previous app version is displayed on splash screen

- redisinsight/ui/src/constants/commands.ts
- redisinsight/ui/src/constants/keys.ts
#RI-2102 - Added TopK label for badge
> #RI-2102 - Added TopK label for badge

- redisinsight/ui/src/components/cli/Cli/Cli.spec.tsx
- redisinsight/ui/src/components/cli/CliWrapper.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-body/CliBody/CliBody.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
- redisinsight/ui/src/constants/cliOutput.tsx
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/slices/cli/cli-settings.ts
- redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts
- redisinsight/ui/src/slices/tests/cli/cli-settings.spec.ts
* #RI-2371 - handle fail execution
* #RI-2370 - refactor cli text output for connection state
> Fix/RI-2371 - handle fail execution

- redisinsight/package.json
increase version to 2.0.4-preview
> increase version to 2.0.4-preview

- redisinsight/api/src/constants/error-messages.ts
- redisinsight/api/src/modules/workbench/dto/create-plugin-state.dto.ts
- redisinsight/api/src/modules/workbench/models/plugin-state.ts
- redisinsight/api/test/api/plugins/POST-instance-id-plugins-command_executions.test.ts
- redisinsight/api/test/api/plugins/POST-instance-id-plugins-id-command_executions-id-state.test.ts
#RI-2388 Cha command not "allowed" message for plugin api
> #RI-2391 change plugin state validation schema

- redisinsight/api/test/api/cli/POST-instance-id-cli-uuid-send_command.test.ts
- redisinsight/api/test/helpers/test.ts
also added sleep function to the deps to use it in the future
> fix client recreate testcase flow

- package.json
- redisinsight/api/package.json
- redisinsight/api/src/modules/shared/services/redis-cloud-business/redis-cloud-business.service.spec.ts
- redisinsight/api/yarn.lock
- yarn.lock
> Dependencies/ Update axios

- redisinsight/api/config/default.ts
- redisinsight/api/src/__mocks__/analytics.ts
- redisinsight/api/src/constants/telemetry-events.ts
- redisinsight/api/src/modules/cli/constants/errors.ts
- redisinsight/api/src/modules/cli/services/cli-analytics/cli-analytics.service.spec.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
- redisinsight/api/src/modules/workbench/plugins.service.ts
- redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.spec.ts
- redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.spec.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.ts
- redisinsight/api/src/modules/workbench/workbench.controller.ts
- redisinsight/api/src/modules/workbench/workbench.module.ts
- redisinsight/api/src/utils/cli-helper.spec.ts
- redisinsight/api/src/utils/cli-helper.ts
* #RI-2355 - create workbench analytics service
* #RI-2355 - add WORKBENCH_COMMAND_EXECUTED, WORKBENCH_COMMAND_ERROR_RECEIVED events
> Feature/ Workbench execution telemetry

- redisinsight/api/src/__mocks__/analytics.ts
- redisinsight/api/src/constants/telemetry-events.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.spec.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.ts
- redisinsight/api/src/modules/workbench/workbench.service.spec.ts
- redisinsight/api/src/modules/workbench/workbench.service.ts
- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
- redisinsight/ui/src/pages/workbench/constants.ts
- redisinsight/ui/src/utils/cliHelper.tsx
- redisinsight/ui/src/utils/tests/cliHelper.spec.ts
* #RI-2201 - add  WORKBENCH_COMMAND_DELETE_COMMAND telemetry event on BE side
* #RI-2201 - update config for default text view for workbench execution
* #RI-2201 - send command name for some Workbench events
> Feature/ Command name for Workbench events

- redisinsight/api/src/modules/monitor/helpers/monitor-observer/monitor-observer.spec.ts
- redisinsight/api/src/modules/monitor/helpers/monitor-observer/monitor-observer.ts
* #RI-2387 - implement a workaround to handle cases when a user has no permission for the 'monitor' command
* #RI-2387 - add unit tests
> Fix/ NOPERM for monitor

- redisinsight/ui/src/components/bottom-group-components/components/bottom-group-minimized/BottomGroupMinimized.tsx
#RI-2434 - always send PROFILER_OPEN event on expand
> Fix/  PROFILER_OPEN event

- .circleci/config.yml
#RI-2446 Disable auto update for dev builds
> #RI-2427 remove internal releases from be published to GH

- redisinsight/api/config/production.ts
- redisinsight/api/config/staging.ts
fix destination path for STAGE and PROD builds
> Fix/ Content folder destination

- redisinsight/api/config/default.ts
- redisinsight/api/config/stack.ts
- redisinsight/api/src/app.module.ts
- redisinsight/api/src/decorators/api-endpoint.decorator.ts
- redisinsight/api/src/middleware/exclude-route.middleware.ts
- redisinsight/api/src/modules/core/models/server-provider.interface.ts
- redisinsight/api/src/modules/instances/controllers/instances/instances.controller.ts
- redisinsight/api/src/modules/redis-enterprise/controllers/cloud.controller.ts
- redisinsight/api/src/modules/redis-enterprise/controllers/cluster.controller.ts
- redisinsight/api/src/utils/config.ts
> Feature/ Redis stack exclude routes

- redisinsight/ui/src/components/main-router/constants/defaultRoutes.ts
- redisinsight/ui/src/components/promo-link/styles.module.scss
* fix default router
* fix styles for promo link
> Fix/ Promo link

- redisinsight/ui/src/components/config/Config.tsx
- redisinsight/ui/src/components/main-router/MainRouter.tsx
move ConsentsSettingsPopup to MainRouter
> Fix/ Consents Settings popup

- redisinsight/ui/src/components/main-router/MainRouter.tsx
- redisinsight/ui/src/components/main-router/constants/commonRoutes.ts
- redisinsight/ui/src/components/main-router/constants/defaultRoutes.ts
- redisinsight/ui/src/components/main-router/constants/redisStackRoutes.ts
#RI-2467 - fix router configuration
> Fix/ Router Configuration

- redisinsight/ui/src/components/query/Query/Query.tsx
- redisinsight/ui/src/components/query/QueryWrapper.tsx
- redisinsight/ui/src/components/shortcuts-flyout/schema.tsx
- redisinsight/ui/src/constants/keyboardShortcuts.tsx
#RI-2453 - add a shortcut to get access to the Workbench execution history
> Feature/ Workbench history quick access

- redisinsight/ui/src/assets/img/modules/RediStack.svg
- redisinsight/ui/src/components/database-list-modules/DatabaseListModules.tsx
- redisinsight/ui/src/components/database-list-modules/styles.module.scss
- redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/home/components/DatabasesListComponent/styles.module.scss
- redisinsight/ui/src/slices/instances.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- redisinsight/ui/src/slices/tests/instances.spec.ts
- redisinsight/ui/src/utils/index.ts
- redisinsight/ui/src/utils/redistack.ts
- redisinsight/ui/src/utils/tests/redistack.spec.ts
#RI-985 - Display the list of modules per database
#RI-2460 - Highlight Redis Stack databases in the list of databases
> #RI-985, #RI-2460 

- Dockerfile
- configs/webpack.config.renderer.dev.babel.js
- configs/webpack.config.renderer.prod.babel.js
- configs/webpack.config.web.dev.babel.js
- configs/webpack.config.web.prod.babel.js
#RI-2512 - fix docker image net-tools
> #RI-2487 - fix fonts

- package.json
- yarn.lock
#RI-2481 - Downgrade version of elastic
> #RI-2481 - Downgrade version of elastic

- redisinsight/ui/src/components/query/DedicatedEditor/DedicatedEditor.tsx
- redisinsight/ui/src/components/query/DedicatedEditor/styles.module.scss
- redisinsight/ui/src/components/query/Query/Query.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/formatter/MarkdownToJsxString.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/remarkImage.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/styles.module.scss
- redisinsight/ui/src/styles/base/_monaco.scss
#RI-2536 - make widget clickable
#RI-2529 - fix dedicated editor position
#RI-2531 - fix dedicated editor height
#RI-2525 - add trigger for onChangeCursorPosition after closing dedicated editor
#RI-2476 - fix wb history
#RI-2543 - fix images for Enablement area
> [bugfix] - cypher, wb, enablement area

- redisinsight/ui/src/pages/instance/InstancePage.tsx
- redisinsight/ui/src/slices/instances.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- redisinsight/ui/src/slices/tests/instances.spec.ts
#RI-2562 - fix blinking of overview
> #RI-2561 - fix showing redis stack logo

- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
> Change redisgraph empty response wording.

- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/LazyInternalPage/LazyInternalPage.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/styles.module.scss
#RI-2615 - No scroll when all the articles are unfolde
#RI-2614 - Enablement area pagination doesn't work correctly
> #RI-2614, #RI-2615

- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
- redisinsight/ui/src/packages/redisgraph/src/styles/styles.less
> [RedisGraph] Change color of empty graph response

- redisinsight/ui/src/packages/redisgraph/src/parser.ts
> [RedisGraph] Fix parser on no data

- redisinsight/ui/src/components/database-overview/styles.module.scss
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
#RI-2650 - fix label for checkbox
> #RI-2651 - fix logo for overview

- redisinsight/ui/src/packages/redisgraph/src/App.tsx
- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
- redisinsight/ui/src/packages/redisgraph/src/constants.ts
- redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
- redisinsight/ui/src/packages/redisgraph/src/main.tsx
- redisinsight/ui/src/packages/redisgraph/src/styles/_dark_theme.less
- redisinsight/ui/src/packages/redisgraph/src/styles/_light_theme.less
- redisinsight/ui/src/packages/redisgraph/src/styles/styles.less
- redisinsight/ui/src/packages/redisgraph/src/utils.ts
Addressing PR comments of https://github.com/RedisInsight/RedisInsight/pull/334
> [RedisGraph] Fix indentation, move constants to separate file, add types

- redisinsight/ui/src/components/query/DedicatedEditor/styles.module.scss
- redisinsight/ui/src/components/query/Query/styles.module.scss
#RI-2644 - disable run btn with dedicated editor
> #RI-2648 - change dedicated editor dimensions

- redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx
- redisinsight/ui/src/components/inline-item-editor/index.ts
- redisinsight/ui/src/components/inline-item-editor/styles.module.scss
- redisinsight/ui/src/components/virtual-tree/VirtualTree.tsx
- redisinsight/ui/src/components/virtual-tree/interfaces.ts
- redisinsight/ui/src/constants/browser.ts
- redisinsight/ui/src/constants/storage.ts
- redisinsight/ui/src/helpers/constructKeysToTree.ts
- redisinsight/ui/src/helpers/tests/constructKeysToTree.spec.ts
- redisinsight/ui/src/helpers/tests/constructKeysToTreeMockResult.ts
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/KeyTreeDelimiter.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/KeyTreeDelimiter.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/index.ts
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/styles.module.scss
- redisinsight/ui/src/pages/browser/components/key-tree/styles.module.scss
- redisinsight/ui/src/slices/app/context.ts
- redisinsight/ui/src/slices/interfaces/app.ts
- redisinsight/ui/src/slices/tests/app/context.spec.ts
- redisinsight/ui/src/utils/index.ts
- redisinsight/ui/src/utils/replaceSpaces.ts
- redisinsight/ui/src/utils/tests/replaceSpaces.spec.ts
- redisinsight/ui/src/utils/tests/tree.spec.ts
- redisinsight/ui/src/utils/tree.ts
#RI-1344 - Added tree view change delimiter
> #RI-1344 - Added tree view change delimiter

- redisinsight/ui/src/components/group-badge/GroupBadge.tsx
- redisinsight/ui/src/components/group-badge/styles.module.scss
- redisinsight/ui/src/components/multi-search/MultiSearch.tsx
- redisinsight/ui/src/components/multi-search/styles.module.scss
- redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/constants.ts
- redisinsight/ui/src/pages/browser/components/filter-key-type/styles.module.scss
- redisinsight/ui/src/pages/browser/components/search-key-list/styles.module.scss
#RI-2661 - fix color for info icon on open
#RI-2670 - sort data types
#RI-2675 - UI fixes for filter
#RI-2676 - show clear btn when options are added
#RI-2678 - fix clear btn text
#RI-2679 - remove titles for badges
> filter bugfix

- .circleci/config.yml
#RI-2628 - Need invalidate CloudFront cache during the release automatically
> #RI-2628 - Need invalidate CloudFront cache 

- redisinsight/ui/src/components/query/DedicatedEditor/styles.module.scss
- redisinsight/ui/src/components/query/Query/Query.tsx
- redisinsight/ui/src/components/query/Query/styles.module.scss
- redisinsight/ui/src/pages/browser/components/add-key/constants/key-type-options.ts
- redisinsight/ui/src/pages/browser/components/filter-key-type/styles.module.scss
#RI-2670 - sort data types for add key
#RI-2683 - fix filter background on hover
> #RI-2681 - fix dedicated editor position

- redisinsight/ui/src/components/instance-header/components/ShortInstanceInfo.tsx
- redisinsight/ui/src/components/instance-header/styles.module.scss
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/KeyTreeDelimiter.tsx
* Fix filter for Tree view
* Fix line height Instance header name
> small fixes

- redisinsight/ui/src/packages/redistimeseries-app/jest.config.js
- redisinsight/ui/src/packages/redistimeseries-app/package.json
- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/ChartConfigForm.tsx
- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/ChartResultView.tsx
- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/interfaces.ts
- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/utils.test.ts
- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/utils.ts
- redisinsight/ui/src/packages/redistimeseries-app/src/main.tsx
- redisinsight/ui/src/packages/redistimeseries-app/src/styles/_dark_theme.less
- redisinsight/ui/src/packages/redistimeseries-app/src/styles/_light_theme.less
- redisinsight/ui/src/packages/redistimeseries-app/src/styles/styles.less
- redisinsight/ui/src/packages/redistimeseries-app/yarn.lock
Address PR comments of: https://github.com/RedisInsight/RedisInsight/pull/312
> [RedisTimeseries] Convert class components to functional, add tests for utils, refactor hex to rgba

- redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
Apologies. Forgot to push identifier at other places....
This is continuation of https://github.com/RedisInsight/RedisInsight/pull/543
> [RedisGraph] Add const identifier for arc and loop edges as well

- redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/Chart.tsx
- redisinsight/ui/src/packages/redistimeseries-app/src/styles/styles.less
RI-063: Fix x axis label placement
RI-2632 - Fix Additional unnecessary scroll bar that appears
https://user-images.githubusercontent.com/20211167/163993300-f27d8ee8-15e7-41ca-b632-94fdeccd3c87.mp4
> [RedisTimeseries] Fix RI-2063, RI-2632

- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
#RI-2749 - Verify TLS Certificate option is ticked when user selects Use TLS option
> #RI-2749 - Verify TLS Certificate option is switched off

- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/styles.module.scss
#RI-2750 - Server Name for SNI is not aligned for Add DB full screen
> #RI-2750 - Server Name for SNI is not aligned for Add DB full screen

- redisinsight/ui/src/packages/redistimeseries-app/package.json
- redisinsight/ui/src/utils/validations.ts
#RI-2657 - During application building default timeseries plugin is not built
> #RI-2657 - During application building default timeseries plugin is not built

- tests/e2e/pageObjects/browser-page.ts
- tests/e2e/tests/critical-path/browser/large-data.e2e.ts
- tests/e2e/tests/critical-path/browser/list-key.e2e.ts
- tests/e2e/tests/critical-path/tree-view/tree-view.e2e.ts
The following tests are fixes:
https://app.circleci.com/pipelines/github/RedisInsight/RedisInsight/2339/workflows/8f9044c9-2193-41e1-972e-fa53bd97424c/jobs/36306 
https://app.circleci.com/pipelines/github/RedisInsight/RedisInsight/2339/workflows/8f9044c9-2193-41e1-972e-fa53bd97424c/jobs/36318
> [E2E] Test fixes desktop and web

- redisinsight/ui/src/packages/redisgraph/src/styles/styles.less
Fixes: https://redislabs.atlassian.net/browse/RI-2776
> [RedisGraph] Fix graph failure response color

- redisinsight/ui/src/pages/browser/components/add-key/AddKey.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyCommonFields/AddKeyCommonFields.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyCommonFields/styles.module.scss
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyStream/AddKeyStream.tsx
- redisinsight/ui/src/pages/browser/components/add-key/constants/fields-config.ts
- redisinsight/ui/src/pages/browser/components/key-details-add-items/add-stream-entity/AddStreamEntries.tsx
- redisinsight/ui/src/pages/browser/components/key-details-add-items/add-stream-entity/StreamEntryFields/StreamEntryFields.tsx
- redisinsight/ui/src/pages/browser/components/key-details-add-items/add-stream-entity/styles.module.scss
#RI-2811 - fix add key panel scroll
> #RI-2819, RI-2812 - update stream entries controls

- tests/e2e/pageObjects/browser-page.ts
- tests/e2e/tests/regression/browser/full-screen.e2e.ts
Failed full screen tests fixes + one more test added according to new logic
> [E2E] Two screens toogle

- redisinsight/ui/src/pages/browser/components/key-details-add-items/add-stream-entity/StreamEntryFields/StreamEntryFields.tsx
- redisinsight/ui/src/pages/home/components/DatabaseAlias/DatabaseAlias.tsx
#RI-2882 - fix db name for edit form
> #RI-2833 - change tooltip

- redisinsight/ui/.eslintrc.js
- redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx
- redisinsight/ui/src/components/virtual-tree/VirtualTree.tsx
- redisinsight/ui/src/constants/durationUnits.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/key-list/index.ts
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.spec.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/utils/validations.ts
* #RI-2880 - There is flickering in key list when auto-refresh is enabled
* #RI-2883 - Not possible to set -1 to stop slowlog in ms
* #RI-2884 - Default button doesn't reset parameters to default
* #RI-2905 - User can not set 0 to track all the commands
> #RI-2883, #RI-2884, #RI-2905, #RI-2880

- redisinsight/ui/src/pages/slowLog/SlowLogPage.tsx
- redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.spec.tsx
- redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogTable/SlowLogTable.tsx
- redisinsight/ui/src/slices/interfaces/slowlog.ts
- redisinsight/ui/src/slices/slowlog/slowlog.ts
- redisinsight/ui/src/slices/tests/slowlog/slowlog.spec.ts
#RI-2917 - fix message for empty slowlog
* add unit tests
> #RI-2920 - add units converter for configure popup

- redisinsight/ui/src/pages/browser/components/key-details/KeyDetailsWrapper.tsx
- redisinsight/ui/src/pages/slowLog/SlowLogPage.tsx
- redisinsight/ui/src/pages/slowLog/components/Actions/Actions.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx
- redisinsight/ui/src/slices/interfaces/instances.ts
#RI-2964 - send count as maxLen from config for slow log cloud db
#RI-2969 - fix key details closing
> #RI-2964, #RI-2969

- redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
Fix #501 
https://user-images.githubusercontent.com/20211167/170473278-1df3a022-890b-4862-af98-06209b3949f8.mp4
> [RedisGraph] Show graph entity overlay only on click and not hover

- redisinsight/ui/src/packages/redisgraph/src/styles/styles.less
https://redislabs.atlassian.net/browse/RI-2623
> [RedisGraph] Make tooltip consistent with workbench tooltip

- redisinsight/ui/src/pages/browser/components/stream-details/consumers-view/ConsumersViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsView/GroupsView.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/messages-view/MessagesView/MessagesView.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/messages-view/MessagesViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/styles.module.scss
- redisinsight/ui/src/slices/browser/stream.ts
- redisinsight/ui/src/slices/interfaces/stream.ts
- redisinsight/ui/src/slices/tests/browser/stream.spec.ts
- redisinsight/ui/src/styles/components/_tabs.scss
#RI-2942 - Show Pending messages list
> #RI-2942 - Show Pending messages list

- redisinsight/ui/src/components/popover-item-editor/PopoverItemEditor.tsx
- redisinsight/ui/src/components/range-filter/styles.module.scss
- redisinsight/ui/src/pages/browser/components/key-details-add-items/add-stream-group/AddStreamGroup.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/styles.module.scss
- redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsViewWrapper.tsx
- redisinsight/ui/src/slices/browser/stream.ts
- redisinsight/ui/src/slices/tests/browser/stream.spec.ts
- redisinsight/ui/src/styles/components/_forms.scss
#RI-2996 - change placeholder
#RI-2997 - fix panel overlap
#RI-2995 - change popoverItemEditor behavior
#RI-3002 - fix cursor for disabled range
* fix on leave hover for inline item editor
* add unit tests
> #RI-2996, #RI-2997, #RI-2995, #RI-3002

- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
- redisinsight/ui/src/components/database-overview/components/OverviewMetrics/OverviewMetrics.tsx
- redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
- redisinsight/ui/src/constants/cliOutput.tsx
- redisinsight/ui/src/pages/home/components/HomeHeader/HomeHeader.tsx
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/styles/components/_buttons.scss
- redisinsight/ui/src/utils/cliHelper.tsx
#RI-3096 - Total keys are not formatted
#RI-3071 - Internal links for Monitor and PSubscribe
> #RI-3096, #RI-3071

- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
- redisinsight/ui/src/packages/redisgraph/src/parser.ts
- redisinsight/ui/src/packages/redisgraph/src/utils.ts
Refer: https://redislabs.atlassian.net/browse/RI-3062?focusedCommentId=1592776
Points: 3, 4, 5, 6, 7
Before: https://drive.google.com/file/d/1dDJDOf1dhTG9ixCMLa7WVQ3GtuHDFO7O/view?usp=sharing
After: https://drive.google.com/file/d/1gHEdEx4knBG-3bEJgUifwQhnc44bmlk-/view?usp=sharing
> [RedisGraph] Fix relationship duplication

- redisinsight/api/config/production.ts
- redisinsight/api/config/staging.ts
Reverts RedisInsight/RedisInsight#845
> Revert "#RI-2685 add analytics keys into source code since docker"

- redisinsight/api/src/modules/notification/dto/index.ts
- redisinsight/api/src/modules/notification/dto/read-notifications.dto.ts
- redisinsight/api/src/modules/notification/notification.controller.ts
- redisinsight/api/src/modules/notification/notification.service.spec.ts
- redisinsight/api/src/modules/notification/notification.service.ts
- redisinsight/api/test/api/notifications/WS-global-sync.test.ts
- redisinsight/api/test/api/stream/POST-instance-id-streams-entries-get.test.ts
- redisinsight/api/test/helpers/constants.ts
- redisinsight/api/test/helpers/local-db.ts
- redisinsight/api/test/test-runs/docker.build.env
- redisinsight/api/test/test-runs/docker.build.yml
- redisinsight/api/test/test-runs/local.build.env
- redisinsight/api/test/test-runs/local.build.yml
#RI-3064 isolate problematic test
> #RI-3149 add filter on "read" operation + fix nightly tests

- tests/e2e/pageObjects/workbench-page.ts
- tests/e2e/tests/regression/workbench/history-of-results.e2e.ts
- tests/e2e/tests/regression/workbench/redis-stack-commands.e2e.ts
> [E2E] Fix 31 commands in Workbench test

- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
- redisinsight/ui/src/packages/redisgraph/src/parser.ts
- redisinsight/ui/src/packages/redisgraph/src/utils.ts
Fixes 2nd point - https://redislabs.atlassian.net/browse/RI-3062?focusedCommentId=1592776
Demo:
https://user-images.githubusercontent.com/20211167/177832508-d9fbb2a4-0f96-4869-a2ee-a3b8173f0bec.mp4
> [RedisGraph] Retrieve nodes automatically if dangling edges are found

- redisinsight/api/package.json
- redisinsight/api/test/api/.mocharc.yml
- redisinsight/api/test/api/notifications/WS-global-sync.test.ts
- redisinsight/api/test/api/stream/DELETE-instance-id-streams-consumer_groups.test.ts
- redisinsight/api/test/api/stream/POST-instance-id-streams-consumer_groups-consumers-pending_messages-ack.test.ts
- redisinsight/api/test/api/stream/POST-instance-id-streams-consumer_groups-consumers-pending_messages-claim.test.ts
- redisinsight/api/test/api/stream/POST-instance-id-streams-consumer_groups-consumers-pending_messages-get.test.ts
- redisinsight/api/test/api/stream/POST-instance-id-streams-entries-get.test.ts
fix nightly tests for notifications feature
move mocha configs to a file to avoid rebuilding docker image any time on config changes
> fix long-running validation tests for streams

- redisinsight/ui/src/components/virtual-table/VirtualTable.tsx
- redisinsight/ui/src/pages/browser/BrowserPage.tsx
- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsInfo/BulkActionsInfo.tsx
- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsInfo/styles.module.scss
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataView/StreamDataView.tsx
* #RI-3250 -  largestCellLength preprty conatins wrong value
* #RI-3263 - Event BULK_ACTIONS_OPENED contains sensitive
* fix demo's comments
> #RI-3250, #RI-3263

- redisinsight/ui/index.html.ejs
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx
#RI-3252 - Set member is displayed not trancated in full mode
fix react import cdn
> #RI-3252 - Set member is displayed not trancated in full mode

- redisinsight/ui/src/pages/browser/BrowserPage.spec.tsx
- redisinsight/ui/src/pages/browser/BrowserPage.tsx
- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx
- redisinsight/ui/src/slices/app/context.ts
- redisinsight/ui/src/slices/interfaces/app.ts
* #RI-3271 - Context is not saved
* #RI-3267 - Clicking on close and Cancel button panel is not closed
> #RI-3271, #RI-3267

- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
RI-2198 - Additional telemetry for Database list
> #RI-3198_update telemetry

- .circleci/config.yml
Reverts RedisInsight/RedisInsight#927
> Revert "change executor to docker"

- tests/e2e/helpers/api/api-database.ts
- tests/e2e/helpers/conf.ts
- tests/e2e/pageObjects/add-redis-database-page.ts
- tests/e2e/tests/regression/database/database-list-search.e2e.ts
- tests/e2e/tests/regression/workbench/workbench-pipeline.e2e.ts
fixes for
- Verify that user can search DB by port on the List of databases
- Verify that only chosen in pipeline number of commands is loading at the same time in Workbench
- Verify that user can see spinner over Run button and grey preloader for each command
> e2e fixes for web tests

- redisinsight/ui/src/components/keys-summary/KeysSummary.tsx
- redisinsight/ui/src/pages/pubSub/components/subscription-panel/SubscriptionPanel.tsx
- redisinsight/ui/src/pages/pubSub/components/subscription-panel/styles.module.scss
- redisinsight/ui/src/pages/pubSub/styles.module.scss
https://redislabs.atlassian.net/browse/RI-3347
https://redislabs.atlassian.net/browse/RI-3178
> #RI-3178,3347- update pub/sub styles, fix scanning text appearence

- package.json
- redisinsight/ui/src/components/notifications/success-messages.tsx
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/constants.ts
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx
- redisinsight/ui/src/slices/browser/string.ts
- redisinsight/ui/src/types/index.d.ts
- redisinsight/ui/src/utils/formatters/bufferFormatters.ts
- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
- yarn.lock
> #RI-3202 - Support ASCII

- redisinsight/ui/src/components/virtual-table/VirtualTable.tsx
- redisinsight/ui/src/pages/browser/BrowserPage.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx
- redisinsight/ui/src/slices/browser/keys.ts
* #RI-3381 - Formatter doesn't reset to default when switching between keys with opened key details
* #RI-3384 - Key details data is missing after second click on a key
> * #RI-3381, #RI-3384

- redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/KeyValueFormatter.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/styles.module.scss
* #RI-3379 - No icon for format switcher at low screen resolution
> * #RI-3379 - No icon for format switcher at low screen resolution

- redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/KeyValueFormatter.tsx
* #RI-3387 - Formatters switcher focused and highlighted when opening key details
> * #RI-3387 - Formatters switcher focused and highlighted

- redisinsight/api/src/modules/shared/services/redis-sentinel-business/redis-sentinel-business.service.ts
probably some Redis 7x inconsistency
> catch quit connection error

- redisinsight/ui/src/components/database-overview/components/MoreInfoPopover/MoreInfoPopover.tsx
- redisinsight/ui/src/components/navigation-menu/components/notifications-center/Notification/Notification.tsx
#RI-3396 - truncate category name for notification
#RI-3397 - fix modules name for more into overview
> #RI-3396, #RI-3397

- redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInputWrapper.tsx
- redisinsight/ui/src/components/query-card/QueryCardCommonResult/components/CommonErrorResponse/CommonErrorResponse.tsx
- redisinsight/ui/src/utils/commands.ts
- redisinsight/ui/src/utils/monacoUtils.ts
#RI-3371 - User cannot open Workbench
> #RI-3371 - User cannot open Workbench

- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
#RI-3422 - User can not save valid value
> #RI-3422 - User can not save valid value

- redisinsight/ui/src/assets/img/icons/raw_mode.svg
- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
> replace -R to -r

- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/stream-tabs/StreamTabs.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx
- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
* #RI-3430 - Edit field with unprintable characters are not highlighed in yellow
* #RI-3314 - Stream Entry is not updated when user goes between tabs
* #RI-3443 - Not possible to change Msgpack value with unprintable characters in Unicode
> #RI-3430, #RI-3314, #RI-3443

- redisinsight/api/package.json
- redisinsight/api/yarn.lock
- redisinsight/package.json
- redisinsight/yarn.lock
#RI-3364 - increase keytar version
> #RI-3364 - increase keytar version

- package.json
- redisinsight/ui/src/constants/keys.ts
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/constants.ts
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx
- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
- redisinsight/ui/src/utils/tests/truncateTTL.spec.ts
- redisinsight/ui/src/utils/truncateTTL.ts
- yarn.lock
> #RI-3334 support pickle

- redisinsight/ui/src/components/keyboard-shortcut/KeyboardShortcut.tsx
- redisinsight/ui/src/components/query-card/QueryCard.tsx
- redisinsight/ui/src/components/query-card/QueryCardCliGroupResult/QueryCardCliGroupResult.tsx
- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
- redisinsight/ui/src/components/query/Query/Query.tsx
- redisinsight/ui/src/components/query/Query/styles.module.scss
- redisinsight/ui/src/components/query/QueryWrapper.tsx
- redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx
- redisinsight/ui/src/pages/workbench/components/wb-results/WBResultsWrapper.tsx
- redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
RI-3543 - [FE][Group Mode] Tooltip style is not the same as for other tooltips
RI-3544 - [FE][Group Mode] Command result is not on the full screen
RI-3546 - [FE][Group Mode] Group property has False value even if commands were run in group
> #RI-3543-3544-3546-bugfix

- redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.spec.tsx
- redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx
- redisinsight/ui/src/components/inline-item-editor/styles.module.scss
- redisinsight/ui/src/constants/browser.ts
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx
#RI-3426 - Invalid format warning
> #RI-3426 - Invalid format warning

- redisinsight/ui/src/pages/home/components/ClusterConnection/ClusterConnectionForm/ClusterConnectionForm.tsx
#RI-3577 - Change validation for Admin Username in RE Cluster
> #RI-3577 - Change validation for Admin Username in RE Cluster

- redisinsight/ui/src/components/query-card/QueryCardCliPlugin/QueryCardCliPlugin.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/EnablementArea.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/Code/Code.spec.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/Code/Code.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/CodeButton/CodeButton.spec.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/CodeButton/CodeButton.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/CodeButton/styles.module.scss
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/LazyCodeButton/LazyCodeButton.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/index.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/parseParams.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/remarkRedisCode.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/tests/getFileInfo.spec.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/tests/parseParams.spec.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/utils/tests/remarkRedisCode.spec.ts
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementAreaWrapper.tsx
- redisinsight/ui/src/pages/workbench/components/enablement-area/interfaces.ts
- redisinsight/ui/src/pages/workbench/components/wb-results/WBResultsWrapper.tsx
- redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
- redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx
- redisinsight/ui/src/pages/workbench/contexts/enablementAreaContext.tsx
also fix id for plugin iframes
> #RI-3479 - add redis-auto button

- redisinsight/ui/.eslintrc.js
- redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/CodeButton/styles.module.scss
* update import/order rule for eslint
> #RI-3610 - fix focus on buttons in enablement area

- redisinsight/ui/src/components/charts/area-chart/AreaChart.tsx
- redisinsight/ui/src/components/charts/area-chart/styles.module.scss
#RI-3634 - Small value in bytes is not centred in tooltip
> #RI-3634 - Small value in bytes is not centred in tooltip

- redisinsight/ui/src/components/navigation-menu/NavigationMenu.tsx
- redisinsight/ui/src/pages/analytics/AnalyticsPage.tsx
- redisinsight/ui/src/pages/analytics/styles.module.scss
- redisinsight/ui/src/pages/clusterDetails/ClusterDetailsPage.tsx
- redisinsight/ui/src/pages/clusterDetails/styles.module.scss
- redisinsight/ui/src/pages/databaseAnalysis/DatabaseAnalysisPage.tsx
- redisinsight/ui/src/pages/databaseAnalysis/styles.module.scss
- redisinsight/ui/src/pages/instance/InstancePage.tsx
- redisinsight/ui/src/pages/slowLog/SlowLogPage.tsx
- redisinsight/ui/src/pages/slowLog/styles.module.scss
- redisinsight/ui/src/slices/app/context.ts
- redisinsight/ui/src/slices/interfaces/app.ts
- redisinsight/ui/src/slices/tests/app/context.spec.ts
* refactor analytics routing
* fix reset context
> #RI-3630 - add tab context for analytics page

- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/utils/formatters/utils.ts
* #RI-3671 - Keys are not refreshed when there are no keys of selected type
* #RI-3672 - 400 error and key not displayed when searching for key
> #RI-3672, #RI-3671

- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
#RI-3673 - Tree view without metadata
> #RI-3673 - Tree view without metadata

- redisinsight/ui/src/components/query-card/QueryCardCliResultWrapper/QueryCardCliResultWrapper.tsx
- redisinsight/ui/src/components/query-card/QueryCardCliResultWrapper/styles.module.scss
- redisinsight/ui/src/components/query-card/styles.module.scss
#RI-3690 - No results displayed for full mode
#RI-3692 - Errors are highlighted not in red
#RI-3693 - Two scrolls appear in full screen when command output in several lines
> #RI-3690, #RI-3692, #RI-3693

- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-3689 - Key list refreshed when refreshing only key details
> #RI-3689 - Key list refreshed when refreshing only key details

- redisinsight/ui/src/components/charts/bar-chart/BarChart.spec.tsx
- redisinsight/ui/src/components/charts/bar-chart/BarChart.tsx
#RU-3722 - no tooltip for horeving small bar
> #RU-3722 - no tooltip for horeving small bar

- redisinsight/ui/src/pages/browser/BrowserPage.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/redisearch-key-list/styles.module.scss
- redisinsight/ui/src/pages/browser/components/search-key-list/styles.module.scss
- redisinsight/ui/src/slices/browser/keys.ts
#RI-3753 - Keys are not displayed correctly in Tree View
> #RI-3753 - Keys are not displayed correctly in Tree View

- redisinsight/ui/src/constants/apiErrors.ts
- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.tsx
- redisinsight/ui/src/slices/browser/redisearch.ts
- redisinsight/ui/src/slices/interfaces/redisearch.ts
- redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts
* #RI-3757 - Page is not cleared when empty indexes response received
* #RI-3756 - Scan more button is displayed after switching from Browser
> #RI-3756, #RI-3757

- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
> #RI-3771 - Incorrect message

- redisinsight/ui/src/constants/api.ts
- redisinsight/ui/src/mocks/handlers/instances/instancesHandlers.ts
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/pages/home/HomePage.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/index.ts
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/index.ts
- redisinsight/ui/src/pages/instance/InstancePage.tsx
- redisinsight/ui/src/slices/instances/cloud.ts
- redisinsight/ui/src/slices/instances/cluster.ts
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/slices/instances/sentinel.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
- redisinsight/ui/src/slices/tests/instances/instances.spec.ts
- redisinsight/ui/src/utils/instance/getUrlInstance.ts
#RI-3711 - Prepare UI for docker
> #RI-3711 - Prepare UI for docker

- redisinsight/ui/src/constants/storage.ts
- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.spec.tsx
- redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.tsx
- redisinsight/ui/src/slices/app/context.ts
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/slices/interfaces/app.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- redisinsight/ui/src/slices/tests/app/context.spec.ts
- redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts
- redisinsight/ui/src/slices/tests/instances/instances.spec.ts
- redisinsight/ui/src/utils/index.ts
- redisinsight/ui/src/utils/modules.ts
- redisinsight/ui/src/utils/tests/modules.spec.ts
- tests/e2e/tests/critical-path/browser/search-capabilities.e2e.ts
#RI-3714 - Save context for Redisearch
> #RI-3714 - Save context for Redisearch

- redisinsight/ui/src/components/keys-summary/KeysSummary.spec.tsx
- redisinsight/ui/src/components/keys-summary/KeysSummary.tsx
- redisinsight/ui/src/components/virtual-tree/VirtualTree.tsx
- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.spec.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.tsx
- redisinsight/ui/src/pages/instance/InstancePage.tsx
- redisinsight/ui/src/slices/interfaces/keys.ts
#RI-3768 - Display the "Scan more" button in the tree view
> #RI-3768 - Display the "Scan more" button in the tree view

- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/utils/redistack.ts
#RI-3808 - No Redis Stack icon on the Edit screen
> #RI-3808 - No Redis Stack icon on the Edit screen

- redisinsight/api/config/default.ts
- redisinsight/api/src/modules/cli/services/cli-analytics/cli-analytics.service.spec.ts
- redisinsight/api/src/modules/cli/services/cli-analytics/cli-analytics.service.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.spec.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
- redisinsight/api/src/modules/workbench/providers/workbench-commands.executor.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.spec.ts
- redisinsight/api/src/modules/workbench/services/workbench-analytics/workbench-analytics.service.ts
* #RI-3736 - Normalize commands in CLI and Workbench
* #RI-3738 - Module name is Redijson for telemetry events
> #RI-3736, #RI-3738

- redisinsight/ui/src/pages/home/HomePage.tsx
#RI-3798 - Last connected DB is highlighted after turning back to List of DBs
> #RI-3798 - Last connected DB is highlighted after turning back to List of DBs

- redisinsight/ui/src/pages/browser/BrowserPage.tsx
- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
* #RI-3848 - The button is displayed with incorrect scanned parameters
* removed panelState from BrowserLeftPanel
> * #RI-3848 - Button is displayed with incorrect scanned parameters

- redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
> [RI-3860] RedisGraph - Properly quote object values. string should appear different from number

- redisinsight/ui/src/packages/redisgraph/src/parser.ts
- redisinsight/ui/src/packages/redisgraph/src/utils.ts
Due to: https://redislabs.atlassian.net/browse/RI-3860?focusedCommentId=1639547
Relates to: https://github.com/RedisInsight/RedisInsight/pull/1438
> [RI-3860] [RedisGraph] Don't convert graph Ids to string.

- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/browser/redisearch.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
- redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts
#RI-3842 - Selected key not displayed in key list when switching between pages/views
> #RI-3842 - Selected key not displayed in key list when switching between pages/views

- redisinsight/ui/src/pages/databaseAnalysis/components/top-keys/Table.tsx
- redisinsight/ui/src/pages/databaseAnalysis/components/top-namespace/Table.tsx
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/utils/comparisons/compareVersions.ts
> fix pika db black screen

- redisinsight/ui/src/components/virtual-tree/VirtualTree.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.spec.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/KeyTreeDelimiter.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeDelimiter/KeyTreeDelimiter.tsx
- redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
- redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.tsx
#RI-3355 - Tree view improvements
> #RI-3355 - Tree view improvements

- .circleci/config.yml
- electron-builder.json
#RI-3936 - build snapcraft in the circleci
> #RI-3936 - build snapcraft in the circleci

- redisinsight/api/src/modules/workbench/dto/create-command-execution.dto.ts
- redisinsight/api/src/modules/workbench/workbench.service.spec.ts
- redisinsight/api/src/modules/workbench/workbench.service.ts
- redisinsight/api/test/api/plugins/POST-databases-id-plugins-command_executions.test.ts
#RI-3702 -[BE] Add silent mode to Workbench guides and Tutorials
> #RI-3702 -[BE] Add silent mode to Workbench guides and Tutorials

- redisinsight/ui/src/pages/home/HomePage.tsx
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/slices/tests/instances/instances.spec.ts
#RI-4012 - Edit alias input appears in a second after opening Edit panel
> #RI-4012 - Edit alias input appears in a second after opening Edit panel

- redisinsight/ui/src/components/database-overview/styles.module.scss
- redisinsight/ui/src/pages/home/HomePage.tsx
- redisinsight/ui/src/pages/home/components/DatabaseAlias/DatabaseAlias.tsx
- redisinsight/ui/src/pages/home/components/DatabaseAlias/styles.module.scss
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/slices/tests/instances/instances.spec.ts
#RI-3956 - Make edit mode for database alias more visible
> #RI-3956 - Make edit mode for database alias more visible

- redisinsight/ui/src/components/cli/components/cli-header/CliHeader.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInput/CliInput.spec.tsx
- redisinsight/ui/src/components/cli/components/cli-input/CliInput/CliInput.tsx
- redisinsight/ui/src/components/query-card/QueryCard.tsx
- redisinsight/ui/src/components/query-card/QueryCardCliGroupResult/QueryCardCliGroupResult.tsx
- redisinsight/ui/src/components/query-card/QueryCardCliResultWrapper/QueryCardCliResultWrapper.tsx
- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
- redisinsight/ui/src/components/query-card/QueryCardTooltip/QueryCardTooltip.spec.tsx
- redisinsight/ui/src/components/query-card/QueryCardTooltip/QueryCardTooltip.tsx
- redisinsight/ui/src/constants/cliOutput.tsx
- redisinsight/ui/src/pages/databaseAnalysis/components/header/Header.tsx
- redisinsight/ui/src/pages/home/components/DatabaseAlias/DatabaseAlias.tsx
- redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx
- redisinsight/ui/src/utils/cliHelper.tsx
- redisinsight/ui/src/utils/longNames.tsx
- redisinsight/ui/src/utils/tests/cliHelper.spec.ts
- redisinsight/ui/src/utils/tests/longNames.spec.ts
#RI-3997 - [FE] Display db indexes in Workbench and Database analysis
> #RI-3997 - [FE] Display db indexes in Workbench and Database analysis

- redisinsight/api/migration/1673934231410-workbench_and_analysis_db.ts
- redisinsight/api/migration/index.ts
- redisinsight/api/src/modules/database-analysis/database-analysis.service.ts
- redisinsight/api/src/modules/database-analysis/entities/database-analysis.entity.ts
- redisinsight/api/src/modules/database-analysis/models/database-analysis.ts
- redisinsight/api/src/modules/database-analysis/models/short-database-analysis.ts
- redisinsight/api/src/modules/database-analysis/providers/database-analysis.provider.ts
- redisinsight/api/src/modules/workbench/entities/command-execution.entity.ts
- redisinsight/api/src/modules/workbench/models/command-execution.ts
- redisinsight/api/src/modules/workbench/providers/command-execution.provider.ts
- redisinsight/api/src/modules/workbench/workbench.service.spec.ts
- redisinsight/api/src/modules/workbench/workbench.service.ts
- redisinsight/api/test/api/database-analysis/GET-databases-id-analysis-id.test.ts
- redisinsight/api/test/api/database-analysis/GET-databases-id-analysis.test.ts
- redisinsight/api/test/api/database-analysis/POST-databases-id-analysis.test.ts
- redisinsight/api/test/api/database-analysis/constants.ts
- redisinsight/api/test/api/workbench/GET-databases-id-workbench-command_executions-id.test.ts
- redisinsight/api/test/api/workbench/GET-databases-id-workbench-command_executions.test.ts
- redisinsight/api/test/api/workbench/POST-databases-id-workbench-command_executions.test.ts
- redisinsight/api/test/helpers/constants.ts
- redisinsight/api/test/helpers/local-db.ts
#RI-3997 - [BE] Display db indexes in Workbench and Database analysis
> #RI-3997 - [BE] Display db indexes in Workbench and Database analysis

- redisinsight/ui/src/components/multi-search/MultiSearch.spec.tsx
- redisinsight/ui/src/components/multi-search/MultiSearch.tsx
- redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/search-key-list/SearchKeyList.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-4114 - fix request for history on reload
#RI-4115 - close history after click search button
> fix #RI-4114 #RI-4115

- configs/webpack.config.renderer.prod.babel.js
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DatabaseForm.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
* #RI-4151 - [FE] 'NaN' timeout by default when adding database
* #RI-4152 - [FE] Timeout field placeholder is '30'
* #RI-4153 - [FE] Sentinel autodiscovery has Connection Timeout input
* Merged Test connection branch
> #RI-4151, #RI-4152, #RI-4153

- redisinsight/api/src/modules/database/database.analytics.spec.ts
- redisinsight/api/src/modules/database/database.analytics.ts
- redisinsight/api/src/modules/database/database.controller.ts
- redisinsight/api/src/modules/database/database.module.ts
- redisinsight/api/test/api/database/POST-databases-test.test.ts
* #RI-4155 - Timeout is displayed in milliseconds in telemetry
* Merged branch with Test connection
> #RI-4155 - Timeout in telemetry in milliseconds

- jest.config.js
- package.json
- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.spec.tsx
- redisinsight/ui/src/constants/browser.ts
- redisinsight/ui/src/constants/keys.ts
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/StreamDetailsWrapper.spec.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/interfaces/keys.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
- redisinsight/ui/src/utils/decompressors/decompressors.ts
- redisinsight/ui/src/utils/decompressors/index.ts
- redisinsight/ui/src/utils/formatters/bufferFormatters.ts
- redisinsight/ui/src/utils/tests/decompressors/decompressors.spec.ts
- yarn.lock
#RI-4142 - decompressed gzip data
> #RI-4142 - decompressed gzip data

- package.json
- redisinsight/ui/src/constants/keys.ts
- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/list-details/ListDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/stream-details/StreamDetailsWrapper.spec.tsx
- redisinsight/ui/src/pages/browser/components/string-details/StringDetails.spec.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.spec.tsx
- redisinsight/ui/src/types/index.d.ts
- redisinsight/ui/src/utils/decompressors/decompressors.ts
- redisinsight/ui/src/utils/formatters/bufferFormatters.ts
- redisinsight/ui/src/utils/tests/decompressors/constants.ts
- redisinsight/ui/src/utils/tests/decompressors/decompressors.spec.ts
- redisinsight/ui/src/utils/tests/decompressors/index.ts
- yarn.lock
#RI-4144 - decompressed ZSTD data
> #RI-4144 - decompressed ZSTD data

- package.json
- redisinsight/ui/src/constants/keys.ts
- redisinsight/ui/src/utils/decompressors/decompressors.ts
- redisinsight/ui/src/utils/tests/decompressors/constants.ts
- redisinsight/ui/src/utils/tests/decompressors/decompressors.spec.ts
- yarn.lock
#RI-4145 - decompressed SNAPPY
> #RI-4145 - decompressed SNAPPY

- redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/components/popover-delete/PopoverDelete.spec.tsx
- redisinsight/ui/src/pages/browser/components/popover-delete/PopoverDelete.tsx
- redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx
- redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx
#RI-4210 - Fields/Members from Hash/Set keys with some special characters can't be deleted
> #RI-4210 - Fields/Members from Hash/Set keys with some special characters can't be deleted

- configs/webpack.config.web.prod.babel.js
split prod web js bundle to chunks
> split prod web js bundle to chunks

- redisinsight/ui/src/packages/ri-explain/src/Explain.tsx
- redisinsight/ui/src/packages/ri-explain/src/Node.tsx
- redisinsight/ui/src/packages/ri-explain/src/parser.ts
- Support for parsing fuzzy expressions
- No collapse window for profile commands
- Parse additional coordinator info
> #RI-4223 Fe/bugfix ri 3726 profile explain 

- redisinsight/ui/src/components/multi-search/MultiSearch.tsx
- redisinsight/ui/src/components/multi-search/styles.module.scss
- redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndex.tsx
- redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.spec.tsx
- redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.tsx
- redisinsight/ui/src/pages/browser/components/create-redisearch-index/styles.module.scss
- redisinsight/ui/src/styles/components/_popover.scss
#RI-4201 - Disable Search per Value when index is not selected
> #RI-4201 - Disable Search per Value when index is not selected

- redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.spec.ts
- redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.ts
#RI-4205 - run FT.CONFIG once for all requests
> #RI-4205 - run FT.CONFIG once for all requests

- redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
[Screencast from 2023-03-07 13-55-25.webm](https://user-images.githubusercontent.com/20211167/223365938-db61297c-d226-46c8-ba51-295ec6a72010.webm)
[Screencast from 2023-03-07 13-44-53.webm](https://user-images.githubusercontent.com/20211167/223365969-eda30204-b282-4c49-8125-f5fa65bd28b4.webm)
> [RI-4267] Graph Plugin - Restrict node movement of other nodes that were not dragged.

- redisinsight/ui/src/packages/redistimeseries-app/src/App.tsx
Fix https://github.com/RedisInsight/RedisInsight/issues/1804
> [RI-4268] Timeseries Plugin - Uppercase cmd before checking TIMESERIES command prefix

- tests/e2e/pageObjects/onboarding-page.ts
- tests/e2e/tests/regression/browser/onboarding.e2e.ts
https://redislabs.atlassian.net/browse/RI-4278
> update test for https://redislabs.atlassian.net/browse/RI-4278

- redisinsight/ui/src/packages/redisgraph/package.json
- redisinsight/ui/src/packages/redisgraph/yarn.lock
#RI-4319 - RedisGraph QUERY visualisations are empty
> #RI-4319 - RedisGraph QUERY visualisations are empty

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
#RI-4341 - Already read recommendations are displayed with yellow border
> #RI-4341 - Already read recommendations are displayed with yellow border

- redisinsight/api/migration/1680591299098-live-time-recommendations.ts
- redisinsight/api/migration/1680619653922-live-time-recommendations.ts
- redisinsight/api/migration/index.ts
- redisinsight/api/src/constants/error-messages.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.controller.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
- redisinsight/api/src/modules/database-recommendation/dto/database-recommendation-vote.dto.ts
- redisinsight/api/src/modules/database-recommendation/dto/index.ts
- redisinsight/api/src/modules/database-recommendation/entities/database-recommendation.entity.ts
- redisinsight/api/src/modules/database-recommendation/models/database-recommendation.ts
- redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.ts
- redisinsight/api/test/api/database-recommendations/GET-databases-id-recommendations.test.ts
- redisinsight/api/test/api/database-recommendations/PATCH-databases-id-recommendations-id.test.ts
- redisinsight/api/test/api/database-recommendations/PATCH-databases-id-recommendations-read.test.ts
- redisinsight/api/test/api/database-recommendations/constants.ts
- redisinsight/api/test/helpers/constants.ts
- redisinsight/api/test/helpers/local-db.ts
#RI-4327 - Upvote extended recommendations
> #RI-4327 - Upvote extended recommendations

- redisinsight/api/src/constants/recommendations.ts
- redisinsight/api/src/modules/browser/services/set-business/set-business.service.spec.ts
- redisinsight/api/src/modules/browser/services/set-business/set-business.service.ts
- redisinsight/api/src/modules/database-recommendation/models/index.ts
- redisinsight/api/src/modules/database-recommendation/models/integersInSet.ts
- redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/integer-in-set.strategy.ts
- redisinsight/api/src/modules/recommendation/recommendation.service.ts
- redisinsight/api/src/utils/cli-helper.spec.ts
- redisinsight/api/src/utils/cli-helper.ts
- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
#RI-4081 - Use only integers in sets
> #RI-4081 - Use only integers in sets

- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/key-details/KeyDetailsWrapper.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/slices/browser/hash.ts
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/browser/list.ts
- redisinsight/ui/src/slices/browser/set.ts
- redisinsight/ui/src/slices/browser/zset.ts
- redisinsight/ui/src/slices/interfaces/keys.ts
- redisinsight/ui/src/slices/tests/browser/hash.spec.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
- redisinsight/ui/src/slices/tests/browser/list.spec.ts
- redisinsight/ui/src/slices/tests/browser/set.spec.ts
- redisinsight/ui/src/slices/tests/browser/zset.spec.ts
- tests/e2e/tests/regression/browser/ttl-format.e2e.ts
- tests/e2e/tests/regression/tree-view/tree-view.e2e.ts
#RI-4355 - disable delete button after clicking
> #RI-4354 - fix error when deleting key from tree view

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
- redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
- redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.tsx
- redisinsight/ui/src/components/recommendation-voting/styles.module.scss
- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
- redisinsight/ui/src/slices/interfaces/recommendations.ts
- redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss
- redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss
#RI-4361 - fix redisStack recommendations
#RI-4362 - fix titles
#RI-4365 - fix background color for voting btn
#RI-4359 - fix recommendations collapse
#RI-4360 - fix multiple telemetry events
> fix: #RI-4361 #RI-4362 #RI-4365 #RI-4359 #RI-4360

- redisinsight/api/src/common/constants/index.ts
- redisinsight/api/src/common/constants/recommendations.ts
- redisinsight/api/src/constants/recommendations.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.spec.ts
- redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/graph-visualization.strategy.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-visualization.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/search-visualization.strategy.ts
- redisinsight/api/src/modules/recommendation/recommendation.service.ts
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
#RI-4086 - [FE+BE] Recommend Workbench visualizations in CLI
> #RI-4086 - [FE+BE] Recommend Workbench visualizations in CLI

- redisinsight/ui/src/packages/clients-list/src/components/json-view/JSONView.tsx
#RI-4400 - [FE] Primitive JSON values aren't parsed
> #RI-4400 - [FE] Primitive JSON values aren't parsed

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
> #RI-4289 - remove eye icon

- redisinsight/api/src/modules/database-recommendation/database-recommendation.controller.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
- redisinsight/api/src/modules/database-recommendation/dto/delete.database-recommendation.dto.ts
- redisinsight/api/src/modules/database-recommendation/dto/delete.database-recommendation.response.ts
- redisinsight/api/src/modules/database-recommendation/dto/index.ts
- redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/providers/database-recommendation.provider.ts
- redisinsight/api/test/api/database-recommendations/DELETE-databases-id-recommendations.test.ts
#RI-4370 - [BE] Snooze recommendations
> #RI-4370 - [BE] Snooze recommendations

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss
- redisinsight/ui/src/components/recommendation-voting/RecommendationVoting.tsx
- redisinsight/ui/src/components/recommendation-voting/styles.module.scss
- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
- redisinsight/ui/src/mocks/handlers/recommendations/recommendationsHandler.ts
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx
- redisinsight/ui/src/slices/recommendations/recommendations.ts
- redisinsight/ui/src/slices/tests/recommendations/recommendations.spec.ts
#RI-4370 - [FE] Snooze recommendations
> #RI-4370 - [FE] Snooze recommendations

- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsInfo/BulkActionsInfo.tsx
- redisinsight/ui/src/pages/browser/components/bulk-actions/BulkUpload/BulkUpload.tsx
- redisinsight/ui/src/slices/browser/bulkActions.ts
- redisinsight/ui/src/slices/tests/browser/bulkActions.spec.ts
#RI-4416 - add error notification
#RI-4417 - clear input file after start new
#RI-4418 - fix buttons, margins
> [bugfix] - #RI-4416 #RI-4417 #RI-4418

- redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
#RI-4368 - change from 95% to 99% rts recommendation
> #RI-4368 - change from 95% to 99% rts recommendation

- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
- redisinsight/ui/src/pages/databaseAnalysis/components/data-nav-tabs/styles.module.scss
- redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/Recommendations.tsx
- redisinsight/ui/src/pages/databaseAnalysis/components/recommendations-view/styles.module.scss
#RI-4415 - fix double scroll on recommendations
> #RI-4415 - fix styles

- redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/rts.strategy.ts
#RI-4431 - [BE] Recommendation displayed when % of time series data >99
> #RI-4431 - [BE] Recommendation displayed when % of time series data >99

- redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/styles.module.scss
- redisinsight/ui/src/constants/recommendations.ts
- redisinsight/ui/src/pages/databaseAnalysis/components/header/Header.spec.tsx
- redisinsight/ui/src/pages/databaseAnalysis/components/header/Header.tsx
#RI-4413 - Automatically trigger database analysis
> #RI-4413 - Automatically trigger database analysis

- redisinsight/api/src/modules/browser/dto/keys.dto.ts
- redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
- redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/cluster.strategy.ts
- redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.spec.ts
- redisinsight/api/src/modules/browser/services/keys-business/scanner/strategies/standalone.strategy.ts
- redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.spec.ts
- redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.ts
- redisinsight/api/test/api/keys/POST-databases-id-keys-get_infos.test.ts
- redisinsight/api/test/api/keys/POST-databases-id-keys.test.ts
#RI-4204 - [BE] Do not run multiple type commands
> #RI-4204 - [BE] Do not run multiple type commands

- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
- redisinsight/ui/src/slices/browser/keys.ts
- redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-4204 - [FE] Do not run multiple type commands
> #RI-4204 - [FE] Do not run multiple type commands

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/popover-run-analyze/PopoverRunAnalyze.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/popover-run-analyze/PopoverRunAnalyze.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/popover-run-analyze/index.ts
- redisinsight/ui/src/components/live-time-recommendations/components/popover-run-analyze/styles.module.scss
- redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
- redisinsight/ui/src/components/live-time-recommendations/components/welcome-screen/styles.module.scss
- redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
#RI-4452 - [FE] User is unable to run DB Analysis from the bottom link
> #RI-4452 - [FE] User is unable to run DB Analysis from the bottom link

- redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
- redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/use-smaller-keys.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/use-smaller-keys.strategy.ts
#RI-4449 - [BE] Use smaller keys
> #RI-4449 - [BE] Use smaller keys

- tests/e2e/pageObjects/dialogs/onboarding-cards-dialog.ts
- tests/e2e/tests/critical-path/memory-efficiency/memory-efficiency.e2e.ts
- tests/e2e/tests/critical-path/memory-efficiency/recommendations.e2e.ts
- tests/e2e/tests/regression/browser/onboarding.e2e.ts
- tests/e2e/tests/regression/insights/live-recommendations.e2e.ts
> E2e/feature/ri 4075 livetime recommendations/text fix

- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/avoid-lua-scripts.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/avoid-lua-scripts.strategy.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/redis-version.strategy.ts
- redisinsight/api/src/modules/database/database-connection.service.spec.ts
- redisinsight/api/src/modules/database/database-connection.service.ts
- redisinsight/api/src/modules/database/dto/redis-info.dto.ts
- redisinsight/api/src/modules/database/providers/database-info.provider.ts
- redisinsight/api/test/api/database/GET-databases-id-info.test.ts
#RI-4448 - [BE] Avoid dynamic Lua scripts
> #RI-4448 - [BE] Avoid dynamic Lua scripts

- redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.spec.ts
- redisinsight/api/src/modules/browser/services/keys-business/keys-business.service.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-string.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-string.strategy.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/compression-for-list.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/compression-for-list.strategy.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
* #RI-4475 - [BE] Avoid large strings
* #RI-4479 - [BE] Enable compression for the list
> #RI-4475, #RI-4479

- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/recommendation.provider.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-amount-connected-clients.strategy.spec.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/big-amount-connected-clients.strategy.ts
- redisinsight/api/src/modules/database-recommendation/scanner/strategies/index.ts
- redisinsight/api/src/modules/database/database-connection.service.spec.ts
- redisinsight/api/src/modules/database/database-connection.service.ts
#RI-4450 - [BE] bigAmountOfConnectedClients for Insights panel
> #RI-4450 - [BE] bigAmountOfConnectedClients for Insights panel

- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx
- redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/live-time-recommendations/styles.module.scss
> #RI-4473 - Do not display the "hidden" option when there are no hidden recommendations

- .circleci/config.yml
#RI-4491 - Add virus check for new builds
> #RI-4491 - Add virus check for new builds

- redisinsight/ui/src/constants/dbAnalysisRecommendations.json
#RI-4522 - [FE] Incorrect recommendation text
> #RI-4522 - [FE] Incorrect recommendation text

- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/LibrariesPage.tsx
- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.spec.tsx
- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/LibrariesList.tsx
- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/styles.module.scss
#RI-4635 - add spinner
#RI-4631 - fix telemetry event data
> #RI-4635, #RI-4631

- redisinsight/api/src/modules/triggered-functions/dto/upload-library.dto.ts
- redisinsight/api/src/modules/triggered-functions/triggered-functions.service.spec.ts
- redisinsight/api/src/modules/triggered-functions/triggered-functions.service.ts
Replace config with configuration
> #RI-4646 - replace config with configuration

- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibrariesList/styles.module.scss
- redisinsight/ui/src/pages/triggeredFunctions/pages/Libraries/components/LibraryDetails/styles.module.scss
#RI-4663 - fix scroll
#RI-4664 - fix styles for long list
> fix #RI-4663, #RI-4664 

- redisinsight/ui/src/setup-env.ts
> fix ui tests

- redisinsight/api/package.json
- redisinsight/api/src/constants/telemetry-events.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.spec.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.analytics.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.module.ts
- redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
- redisinsight/api/src/modules/database-recommendation/repositories/local.database.recommendation.repository.ts
#RI-4667 - Telemetry improvements
> #RI-4667 - Telemetry improvements

- redisinsight/api/src/modules/browser/services/redisearch/redisearch.service.ts
#RI-4721 - [Prod][BE] Index creation error for redis 7.1+
> #RI-4721 - [Prod][BE] Index creation error for redis 7.1+

- redisinsight/api/src/constants/error-messages.ts
- redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts
- redisinsight/api/src/modules/database/providers/database-info.provider.ts
#RI-4699 - 500 error on connecting to user with -@dangerous rule
> #RI-4699 - 500 error on connecting to user with -@dangerous rule

- scripts/build-statics.cmd
- scripts/build-statics.sh
#RI-4506 - recommendations from GitHub repository
> #RI-4506 - recommendations from GitHub repository

- redisinsight/api/src/modules/cloud/job/jobs/cloud-job.ts
- redisinsight/api/src/modules/cloud/job/jobs/create-free-database.cloud-job.ts
- redisinsight/api/src/modules/cloud/job/models/cloud-job-info.ts
#RI-4759 - Display detailed statuses for the progress
> #RI-4759 - Display detailed statuses for the progress

- redisinsight/api/src/modules/profiler/profiler.controller.ts
- redisinsight/ui/src/components/monitor/MonitorLog/MonitorLog.spec.tsx
- redisinsight/ui/src/components/monitor/MonitorLog/MonitorLog.tsx
- redisinsight/ui/src/setup-tests.ts
- redisinsight/ui/src/slices/cli/cli-output.ts
- redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts
- redisinsight/ui/src/utils/dom/downloadFile.ts
- redisinsight/ui/src/utils/tests/dom/downloadFile.spec.ts
#RI-4840 - [Regression] Profiler logs download failure
> #RI-4840 - [Regression] Profiler logs download failure

- electron-builder.json
> perMachine: false

- redisinsight/api/src/__mocks__/feature.ts
- redisinsight/api/src/modules/analytics/analytics.service.spec.ts
- redisinsight/api/src/modules/analytics/analytics.service.ts
- redisinsight/api/src/modules/server/server.service.spec.ts
- redisinsight/api/src/modules/server/server.service.ts
- redisinsight/ui/src/telemetry/interfaces.ts
- redisinsight/ui/src/telemetry/telemetryUtils.ts
#RI-4842 - Add application version to all telemetry events
> #RI-4842 - Add application version to all telemetry events

- tests/e2e/test-data/formatters-data.ts
- tests/e2e/tests/critical-path/browser/formatters.e2e.ts
> add verification for bigInt

- redisinsight/ui/src/utils/formatters/bufferFormatters.ts
Fixes: https://github.com/RedisInsight/RedisInsight/issues/2147
After:
> RI-4852 - Fix java serialized string object

- redisinsight/api/src/modules/database/database-connection.service.ts
#RI-4927 - telemetry event sent if redis<7
> #RI-4927 - telemetry event sent if redis<7

- redisinsight/ui/src/constants/durationUnits.tsx
- redisinsight/ui/src/mocks/data/oauth.ts
- redisinsight/ui/src/mocks/handlers/index.ts
- redisinsight/ui/src/mocks/handlers/oauth/cloud.ts
- redisinsight/ui/src/mocks/handlers/oauth/index.ts
- redisinsight/ui/src/pages/settings/components/cloud-settings/CloudSettings.spec.tsx
- redisinsight/ui/src/pages/slowLog/SlowLogPage.tsx
- redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx
#RI-4928 - ms not changed to msec below slow-log-slower-than input in configurations
> #RI-4928 - ms not changed to msec below slow-log-slower-than input in configurations

- redisinsight/api/src/constants/app-events.ts
- redisinsight/api/src/modules/analytics/analytics.controller.ts
- redisinsight/api/src/modules/analytics/analytics.module.ts
- redisinsight/api/src/modules/analytics/analytics.service.spec.ts
- redisinsight/api/src/modules/analytics/analytics.service.ts
- redisinsight/api/src/modules/analytics/dto/analytics.dto.ts
- redisinsight/api/test/api/analytics/POST-analytics-send-event.test.ts
- redisinsight/api/test/api/analytics/POST-analytics-send-page.test.ts
- redisinsight/api/test/helpers/constants.ts
#RI-4865 - [BE] send frontend events in batches
> #RI-4865 - [BE] send frontend events in batches

- redisinsight/api/src/constants/custom-error-codes.ts
- redisinsight/api/src/constants/error-messages.ts
- redisinsight/api/src/modules/database-import/database-import.service.spec.ts
- redisinsight/api/src/modules/database-import/database-import.service.ts
- redisinsight/api/src/modules/database/database.controller.ts
- redisinsight/api/src/modules/database/database.service.ts
- redisinsight/api/src/modules/database/exeptions/database-already-exists.exception.ts
- redisinsight/api/src/modules/database/exeptions/index.ts
- redisinsight/api/src/modules/database/repositories/database.repository.ts
- redisinsight/api/src/modules/database/repositories/local.database.repository.spec.ts
- redisinsight/api/src/modules/database/repositories/local.database.repository.ts
- redisinsight/api/src/modules/database/repositories/stack.databases.repository.ts
- redisinsight/api/src/modules/encryption/model.encryptor.ts
- redisinsight/api/test/api/database/POST-databases.test.ts
- redisinsight/api/test/helpers/constants.ts
#RI-4813 - [BE] Do not duplicate Cloud databases
> #RI-4813 - [BE] Do not duplicate Cloud databases

- redisinsight/ui/src/components/notifications/success-messages.tsx
- redisinsight/ui/src/constants/customErrorCodes.ts
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.spec.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DatabaseForm.tsx
- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/form-components/DbInfo.tsx
- redisinsight/ui/src/slices/app/url-handling.ts
- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/slices/tests/instances/instances.spec.ts
#RI-4813 - [FE] Do not duplicate Cloud databases
> #RI-4813 - [FE] Do not duplicate Cloud databases

- redisinsight/desktop/src/lib/app/app.handlers.ts
- redisinsight/desktop/src/lib/app/deep-link.handlers.ts
- redisinsight/desktop/src/lib/tray/tray.ts
- redisinsight/desktop/src/lib/window/window.handlers.ts
- redisinsight/desktop/src/utils/index.ts
- redisinsight/desktop/src/utils/showOrCreateWindow.ts
#RI-4881 - [Regression] Application can be opened via application icon if the application is in tray
> #RI-4881 - Application can be opened via application icon if the application is in tray

- redisinsight/ui/src/pages/home/components/AddDatabases/AddDatabasesContainer.tsx
- redisinsight/ui/src/slices/instances/instances.ts
* #RI-4975 - DB tries to connect if user added the db for the second time
* #RI-4976 - 'Add Db manually' the form is not cleared up if I open other forms
> #RI-4975, #RI-4976

- redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
#RI-4919 - [FE] Black screen is displayed if cancel connection
> #RI-4919 - [FE] Black screen is displayed if cancel connection

- redisinsight/api/config/features-config.json
- redisinsight/api/src/modules/cloud/subscription/cloud-subscription.api.service.spec.ts
- redisinsight/api/src/modules/cloud/subscription/cloud-subscription.api.service.ts
> #RI-4988 add feature config for plan filters

- redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx
#RI-5000 - [FE] Popup message text not visible for the light theme
> #RI-5000 - [FE] Popup message text not visible for the light theme

- redisinsight/desktop/src/lib/updater/updater.ts
* #RI-5001 - [FE][Win] Successful update message is not displayed
* #RI-5002 - [Win] Installation folder selection window is displayed after clicking on Restart
> #RI-5001, #RI-5002

- Dockerfile
#RI-5052 - [Regression] 'Build docker image' is failed
> #RI-5052 - [Regression] 'Build docker image' is failed

- redisinsight/ui/src/slices/instances/instances.ts
- redisinsight/ui/src/utils/tests/transformers/transformQueryParams.spec.ts
- redisinsight/ui/src/utils/transformers/transformQueryParams.ts
#RI-5011 - cover false values for query params
> #RI-5006 - fix closing infinite message on connect to db error

- package.json
- yarn.lock
> update pickleparser to supports Pickle protocol 5

- redisinsight/ui/src/pages/home/HomePage.tsx
- redisinsight/ui/src/pages/home/components/databases-list-component/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/home/components/databases-list-component/databases-list/DatabasesList.tsx
- redisinsight/ui/src/pages/home/components/databases-list-component/databases-list/utils.spec.ts
- redisinsight/ui/src/pages/home/components/databases-list-component/databases-list/utils.ts
- redisinsight/ui/src/pages/home/components/databases-list-component/styles.module.scss
- redisinsight/ui/src/pages/home/components/welcome-component/WelcomeComponent.tsx
- redisinsight/ui/src/pages/home/components/welcome-component/styles.module.scss
- redisinsight/ui/src/pages/home/styles.module.scss
#RI-5349 - fix borders
#RI-5350 - add title to welcome page
> #RI-5348 - change logic to hide columns

- redisinsight/desktop/src/lib/updater/updater.handlers.ts
- redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/CodeButtonBlock/CodeButtonBlock.tsx
- redisinsight/ui/src/components/onboarding-features/OnboardingFeatures.spec.tsx
- redisinsight/ui/src/components/onboarding-features/OnboardingFeatures.tsx
- redisinsight/ui/src/pages/autodiscover-cloud/redis-cloud-databases-result/styles.module.scss
- redisinsight/ui/src/pages/autodiscover-cloud/redis-cloud-databases/styles.module.scss
- redisinsight/ui/src/pages/autodiscover-cloud/redis-cloud-subscriptions/styles.module.scss
- redisinsight/ui/src/pages/autodiscover-sentinel/sentinel-databases-result/components/SentinelDatabasesResult/styles.module.scss
- redisinsight/ui/src/pages/autodiscover-sentinel/styles.module.scss
- redisinsight/ui/src/pages/home/components/databases-list-component/styles.module.scss
- redisinsight/ui/src/pages/redis-cluster/styles.module.scss
#RI-5369 - fix height for the list of pages
#RI-5370 - fix onboarding
> #RI-5372 - fix message showing

- redisinsight/desktop/src/lib/app/deep-link.handlers.ts
- redisinsight/ui/src/components/global-url-handler/GlobalUrlHandler.tsx
- redisinsight/ui/src/electron/components/ConfigElectron/ConfigElectron.tsx
- redisinsight/ui/src/utils/parseRedisUrl.ts
- redisinsight/ui/src/utils/tests/parseRedisUrl.spec.ts
#RI-5408, #RI-5409 - fix url encoding
> #RI-5407 - fix parsing url regex

- redisinsight/desktop/src/lib/server/server.ts
#RI-5435 - RedisInsight connection error "Undefined window id"
> #RI-5435 - RedisInsight connection error "Undefined window id"

- redisinsight/ui/src/pages/home/components/sentinel-connection/sentinel-connection-form/SentinelConnectionForm.tsx
- redisinsight/ui/src/pages/home/utils/form.tsx
#RI-5436 - [Regression] Add 'Requires TLS Client' form is not expaned
> #RI-5436 - [Regression] Add 'Requires TLS Client' form is not expaned

- redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/Code/Code.tsx
- redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/CodeButtonBlock/CodeButtonBlock.spec.tsx
- redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/CodeButtonBlock/CodeButtonBlock.tsx
- redisinsight/ui/src/slices/instances/instances.ts
#RI-5437 - fix confirmation popover showing
> #RI-5445 - do not display run commands confirmation for free databases

- redisinsight/ui/src/pages/browser/components/redisearch-key-list/styles.module.scss
- redisinsight/ui/src/pages/home/components/sentinel-connection/sentinel-connection-form/SentinelConnectionForm.tsx
- redisinsight/ui/src/pages/home/utils/form.tsx
- redisinsight/ui/src/styles/base/_overrides.scss
* #RI-5444 - enlarge the search index drop down
* #RI-5436 - [Regression] Add 'Requires TLS Client' form is not expaned
> #RI-5444, #RI-5436

- redisinsight/ui/src/pages/browser/components/redisearch-key-list/styles.module.scss
#RI-5465 - [Regression] Index arrow in to fix the screen
> #RI-5465 - [Regression] Index arrow in to fix the screen

- redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
- redisinsight/ui/src/components/query-card/QueryCardHeader/styles.module.scss
Reverts RedisInsight/RedisInsight#3106
> Revert "#RI-5473 - fix query card header"

- redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/hash-details-table/HashDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/list-details/list-details-table/ListDetailsTable.tsx
- redisinsight/ui/src/slices/browser/list.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
#RIVS-162 - editing element is not cancelled after search
> #RIVS-162 - editing element is not cancelled after search

- LICENSE
This reverts commit 456c1bdf7a35a0f3addd58180005ef1dd02570c1.
> Fix license to copyright MongoDB

- redisinsight/api/config/staging.ts
> #RI-5280 - fix stage config

- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/assistance-chat/AssistanceChat.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/expert-chat/ExpertChat.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/welcome-ai-assistant/WelcomeAiAssistant.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/welcome-ai-assistant/styles.module.scss
- redisinsight/ui/src/slices/app/features.ts
- redisinsight/ui/src/slices/panels/aiAssistant.ts
#RI-5678 - fix send request for history
* fix container overflow
> #RI-5670 - fix loading history after changing account

- redisinsight/ui/src/pages/autodiscover-cloud/redis-cloud-databases/RedisCloudDatabasesPage.tsx
- redisinsight/ui/src/slices/oauth/cloud.ts
#RI-5697 - fix authorization error messages
> #RI-5696 - fix log out on autodiscovery

- package.json
- yarn.lock
Bump protobuf version.
This fixes - https://github.com/RedisInsight/RedisInsight/security/dependabot/377.
> Bump protobuf version

- redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.tsx
- redisinsight/ui/src/components/oauth/oauth-sso-handler-dialog/OAuthSsoHandlerDialog.tsx
- redisinsight/ui/src/components/oauth/oauth-sso/oauth-create-db/OAuthCreateDb.spec.tsx
- redisinsight/ui/src/components/oauth/oauth-sso/oauth-create-db/OAuthCreateDb.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/welcome-ai-assistant/WelcomeAiAssistant.tsx
- redisinsight/ui/src/electron/components/ConfigOAuth/ConfigOAuth.tsx
- redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.spec.tsx
- redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.tsx
- redisinsight/ui/src/slices/interfaces/cloud.ts
- redisinsight/ui/src/utils/oauth/cloudSsoUtm.tsx
#RI-5714 - fix event
#RI-5738 - fix event source
> #RI-5719 - fix oauth callback

- redisinsight/ui/src/pages/rdi/home/empty-message/EmptyMessage.tsx
> fix line-height

- redisinsight/ui/src/electron/components/ConfigOAuth/ConfigOAuth.tsx
- redisinsight/ui/src/slices/interfaces/cloud.ts
- redisinsight/ui/src/utils/oauth/cloudSsoUtm.tsx
#RI-5757 - add utm to cloud/me
> #RI-5719 - handle double callback

- redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.spec.tsx
- redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.tsx
- redisinsight/ui/src/components/shortcuts-flyout/styles.module.scss
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/shared/error-message/ErrorMessage.spec.tsx
- redisinsight/ui/src/constants/apiErrors.ts
- redisinsight/ui/src/utils/tests/transformers/formatDate.spec.ts
- redisinsight/ui/src/utils/transformers/formatDate.ts
> #RI-5781 - change format of seconds for rate limit

- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/shared/chat-history/ChatHistory.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/shared/markdown-message/MarkdownMessage.tsx
- redisinsight/ui/src/components/table-column-search-trigger/styles.module.scss
- redisinsight/ui/src/components/virtual-table/styles.module.scss
- redisinsight/ui/src/pages/database-analysis/components/top-keys/styles.module.scss
- redisinsight/ui/src/styles/base/_base.scss
- redisinsight/ui/src/styles/base/_overrides.scss
#RI-5786 - fix styles
#RI-5787 - change parsing from human message
> bugfix #RI-5786, #RI-5787

- redisinsight/ui/src/components/global-subscriptions/CommonAppSubscription/CommonAppSubscription.spec.tsx
- redisinsight/ui/src/components/global-subscriptions/CommonAppSubscription/CommonAppSubscription.tsx
- redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.spec.tsx
- redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.tsx
#RI-5798 - [Regression] 401 error from WS is not handled
> #RI-5798 - [Regression] 401 error from WS is not handled

- redisinsight/api/config/features-config.json
RDI feature should be unavailable in redis stack
> add rdi feature filter neq redis_stack

- redisinsight/api/src/modules/cluster-monitor/strategies/cluster-shards.info.strategy.ts
- redisinsight/api/src/modules/redis/client/redis.client.ts
> RI-5539: Consume tls-port in cluster shard node retrieval

- redisinsight/ui/src/components/navigation-menu/NavigationMenu.tsx
- redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/components/recommendation/Recommendation.tsx
- redisinsight/ui/src/pages/workbench/components/query/Query/styles.module.scss
#RI-5898 - fix nav meni redirect
#RI-5899 - fix go to workbench button from recommendation
> #RI-5903 - fix suggestions for workbench editor

- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-details/RejsonDetails.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-scalar/RejsonScalar.tsx
- redisinsight/ui/src/slices/browser/rejson.ts
- redisinsight/ui/src/telemetry/telemetryUtils.ts
#RIVS-202 - No TREE_VIEW_JSON_PROPERTY_EDITED event
> #RIVS-202 - No TREE_VIEW_JSON_PROPERTY_EDITED event

- redisinsight/ui/src/components/home-tabs/HomeTabs.tsx
- redisinsight/ui/src/constants/featuresHighlighting.tsx
- redisinsight/ui/src/slices/interfaces/app.ts
Fix for #5937 (bug from #5924)
> Fixed rdi page not open

- redisinsight/ui/src/constants/telemetry.ts
- redisinsight/ui/src/pages/browser/BrowserPage.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/KeyDetails.tsx
- redisinsight/ui/src/pages/cluster-details/ClusterDetailsPage.tsx
- redisinsight/ui/src/pages/database-analysis/DatabaseAnalysisPage.tsx
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/pub-sub/PubSubPage.spec.tsx
- redisinsight/ui/src/pages/pub-sub/PubSubPage.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/config/Config.spec.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/config/Config.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/JobWrapper.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/JobsWrapper.spec.tsx
- redisinsight/ui/src/pages/rdi/statistics/StatisticsPage.spec.tsx
- redisinsight/ui/src/pages/rdi/statistics/StatisticsPage.tsx
- redisinsight/ui/src/pages/slow-log/SlowLogPage.tsx
- redisinsight/ui/src/pages/workbench/WorkbenchPage.tsx
- redisinsight/ui/src/telemetry/interfaces.ts
- redisinsight/ui/src/telemetry/telemetryUtils.ts
> Fix provider is not added to some telemetry events

- redisinsight/api/config/default.ts
> move to a new 2.54 statics

- redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/key-details-subheader/KeyDetailsSubheader.tsx
> RI-5959 fixed showttl not working

- redisinsight/ui/src/components/upload-file/UploadFile.tsx
Fix double send telemetry event BROWSER_JSON_VALUE_IMPORT_CLICKED
> Fix double send telemetry event BROWSER_JSON_VALUE_IMPORT_CLICKED

- redisinsight/ui/src/pages/search/components/query/Query.tsx
- redisinsight/ui/src/pages/search/components/query/constants.ts
- redisinsight/ui/src/pages/search/components/query/utils.ts
- redisinsight/ui/src/utils/monaco/monacoRedisMonarchTokensProvider.ts
- redisinsight/ui/src/utils/monaco/monacoThemes.ts
- redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokens.ts
> #RI-5982 - add tokenizer for search and query

- redisinsight/ui/src/utils/errors.tsx
> RI 6011 empty error appears

- redisinsight/ui/src/components/json-viewer/JSONViewer.tsx
- redisinsight/ui/src/constants/string.ts
- redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/hash-details-table/HashDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/list-details/list-details-table/ListDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/set-details/set-details-table/SetDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/zset-details/zset-details-table/ZSetDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/shared/formatted-value/FormattedValue.tsx
- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
- redisinsight/ui/src/utils/longNames.tsx
> RI-6005 tooltip content should be formatted the same as value

- redisinsight/ui/src/components/json-viewer/JSONViewer.tsx
- redisinsight/ui/src/constants/string.ts
- redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/HashDetails.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/hash-details-table/HashDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/list-details/list-details-table/ListDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/set-details/set-details-table/SetDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/string-details-value/StringDetailsValue.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/zset-details/zset-details-table/ZSetDetailsTable.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/shared/formatted-value/FormattedValue.spec.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/shared/formatted-value/FormattedValue.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/shared/formatted-value/index.ts
- redisinsight/ui/src/pages/browser/modules/key-details/shared/index.ts
- redisinsight/ui/src/utils/formatters/bufferFormatters.ts
- redisinsight/ui/src/utils/formatters/utils.ts
- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
- redisinsight/ui/src/utils/longNames.tsx
- redisinsight/ui/src/utils/tests/formatters/bufferFormatters.spec.ts
- redisinsight/ui/src/utils/tests/formatters/valueFormatters.spec.ts
- tests/e2e/test-data/formatters-data.ts
- tests/e2e/tests/web/critical-path/browser/formatters.e2e.ts
Vector formatters format only values with unprintable elements
> RI-5998 added improvements in vector formatters

- .circleci/deps-licenses-report.js
- redisinsight/api/config/default.ts
- redisinsight/api/esbuild.js
#RIVS-261 - minified be with defaults
> #RIVS-261 - minified be with defaults

- redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
In `WelcomeScreen.tsx`, wrap the controls in ternary conditional, because `FeatureFlagComponent` accepts as children only `JSX.Element | JSX.Element[]` and expression of type `{ conditional && <Component/> }` cause TypeScript errors
> wrap analyze database controls in FeatureFlagComponent.

- redisinsight/ui/src/pages/settings/components/general-settings/datetime-formatter/DateTimeFormatter.tsx
> RI-6039 change description text for timezone

- redisinsight/ui/src/constants/datetime.ts
> RI-6038 Added space to format

- redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
> RI-6043 streams default time value, when no settings applied

- redisinsight/ui/src/pages/search/components/query/Query.tsx
- redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokens.ts
#RI-6093 - fix expression suggestions
> #RI-6091 - fix highlighting

- redisinsight/ui/src/pages/search/components/query/Query.tsx
- redisinsight/ui/src/pages/search/utils/query.ts
- redisinsight/ui/src/pages/search/utils/tests/query.spec.ts
#RI-6086 - fix number of args next to count
#RI-6088 - fix multiple arguments
> fix #RI-6088, #RI-6086 

- redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
- redisinsight/ui/src/pages/browser/components/browser-left-panel/styles.module.scss
- redisinsight/ui/src/services/apiService.ts
- redisinsight/ui/src/slices/browser/keys.ts
When there is connection error, display it in the UI as well as in the notification
> Provide better UI for connection errors

- redisinsight/ui/src/templates/rdi-instance-page-template/styles.module.scss
> RI-6138 fixed css for rdi

- redisinsight/ui/src/pages/search/components/query/Query.tsx
- redisinsight/ui/src/pages/search/components/query/constants.ts
- redisinsight/ui/src/pages/search/components/query/utils.ts
- redisinsight/ui/src/pages/search/utils/query.ts
- redisinsight/ui/src/slices/app/context.ts
- redisinsight/ui/src/slices/interfaces/app.ts
- redisinsight/ui/src/slices/tests/app/context.spec.ts
> #RI-6135 - cover no indexes case

- redisinsight/ui/src/components/side-panels/components/copilot-panel/CopilotPanel.spec.tsx
- redisinsight/ui/src/components/side-panels/components/copilot-panel/CopilotPanel.tsx
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/ai-chat/AiChat.tsx
- redisinsight/ui/src/components/triggers/copilot-trigger/CopilotTrigger.spec.tsx
- redisinsight/ui/src/components/triggers/copilot-trigger/CopilotTrigger.tsx
> RI-6206, RI-6207 telemetry fixes

- redisinsight/ui/src/constants/monaco/monacoRedis.ts
- redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx
- redisinsight/ui/src/pages/workbench/utils/suggestions.ts
> #RI-6170 - fix word pattern

- redisinsight/ui/src/constants/monaco/monaco.ts
- redisinsight/ui/src/constants/monaco/theme.ts
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx
- redisinsight/ui/src/pages/workbench/utils/monaco.ts
- redisinsight/ui/src/pages/workbench/utils/query.ts
- redisinsight/ui/src/utils/monaco/monacoUtils.ts
- redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokensSubRedis.ts
- redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokensTemplates.ts
#RI-6250 - fix form jumping
#RI-6253 - fix highlighting
#RI-6250 - fix suggestions
#RI-6264 - do not show list of commands automatically 
#RI-6266 - fix help widget highlighted text
> fix fe bugs

- redisinsight/ui/src/pages/workbench/utils/monaco.ts
- redisinsight/ui/src/pages/workbench/utils/searchSuggestions.ts
- redisinsight/ui/src/utils/monaco/monacoRedisMonarchTokensProvider.ts
- redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokensSubRedis.ts
> #RI-6277 - fix incorrect highlighting

- .github/workflows/aws.yml
- .github/workflows/build.yml
- .github/workflows/deploy-pages.yml
- .github/workflows/pipeline-build-docker.yml
- .github/workflows/pipeline-build-linux.yml
- .github/workflows/pipeline-build-macos.yml
- .github/workflows/pipeline-build-windows.yml
- .github/workflows/release-prod.yml
- .github/workflows/release-stage.yml
- .github/workflows/remove-artifacts.yml
- .github/workflows/tests-backend.yml
- .github/workflows/tests-e2e-appimage.yml
- .github/workflows/tests-e2e-docker.yml
- .github/workflows/tests-frontend.yml
- .github/workflows/tests-integration.yml
- .github/workflows/tests.yml
- .gitignore
- jest.config.cjs
- package.json
- redisinsight/api/package.json
- redisinsight/api/src/modules/cloud/session/repositories/local.cloud.session.repository.spec.ts
- redisinsight/api/yarn.lock
- tests/e2e/.desktop.env
- tests/e2e/desktop.runner.ci.ts
- tests/e2e/desktop.runner.ts
- tests/e2e/desktop.runner.win.ts
- tests/e2e/package.json
- tests/e2e/web.runner.ci.ts
- tests/e2e/web.runner.ts
- yarn.lock
#RI-6251 - Enhance GitHub actions
Example of a new Test workflow
https://github.com/RedisInsight/RedisInsight/actions/runs/11628132469
> #RI-6251 - Enhance GitHub actions

- redisinsight/ui/src/utils/formatters/valueFormatters.tsx
- redisinsight/ui/src/utils/tests/formatters/valueFormatters.spec.ts
- tests/e2e/tests/web/regression/browser/formatters.e2e.ts
> check PR 4025

- redisinsight/ui/src/helpers/constructKeysToTree.ts
- redisinsight/ui/src/pages/browser/components/virtual-tree/VirtualTree.tsx
- redisinsight/ui/src/pages/browser/components/virtual-tree/components/Node/Node.tsx
- redisinsight/ui/src/pages/browser/components/virtual-tree/components/Node/styles.module.scss
#RI-6340 - All delimiters between each node item name of folder description tooltip
> #RI-6340 - All delimiters between each node item name of folder description tooltip

- redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/LiveTimeRecommendations.tsx
- redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/components/welcome-screen/WelcomeScreen.tsx
- redisinsight/ui/src/pages/database-analysis/components/header/Header.tsx
- redisinsight/ui/src/slices/analytics/dbAnalysis.ts
- redisinsight/ui/src/slices/tests/analytics/dbAnalysis.spec.ts
- redisinsight/ui/src/slices/tests/app/context.spec.ts
#RI-6352 - "Delimiter must be a string" error for db analysis
> #RI-6352 - "Delimiter must be a string" error for db analysis

- redisinsight/ui/src/contexts/themeContext.tsx
- redisinsight/ui/src/pages/database-analysis/components/top-keys/Table.tsx
- redisinsight/ui/src/pages/database-analysis/components/top-namespace/Table.tsx
> Fe/bugfix/release 2.62 fixes

- redisinsight/api/src/__mocks__/databases.ts
- redisinsight/api/src/modules/database/constants/overview.ts
- redisinsight/api/src/modules/database/database-info.controller.ts
- redisinsight/api/src/modules/database/database-info.service.spec.ts
- redisinsight/api/src/modules/database/database-info.service.ts
- redisinsight/api/src/modules/database/providers/database-overview.provider.spec.ts
- redisinsight/api/src/modules/database/providers/database-overview.provider.ts
#RIVS-31 - Display keys from logical databases
> #RIVS-31 - Display keys from logical databases

- .github/workflows/tests-integration.yml
fix path to docker image for IT
> fix path to docker image for IT

- redisinsight/ui/src/pages/home/components/connection-url/ConnectionUrl.tsx
- redisinsight/ui/src/pages/home/components/database-panel-dialog/DatabasePanelDialog.tsx
- redisinsight/ui/src/pages/home/components/form/Messages.tsx
- redisinsight/ui/src/pages/home/components/styles.module.scss
#RI-6377 - fix host
#RI-6378 - fix links colors
> #RI-6377, #RI-6378 - defect fixing

- .github/workflows/tests-e2e-appimage.yml
> fix gh actions e2e appimage

- redisinsight/api/src/__mocks__/databases.ts
- redisinsight/api/src/modules/database/database.analytics.spec.ts
- redisinsight/api/src/modules/database/database.analytics.ts
- redisinsight/api/src/modules/database/database.service.ts
#RI-6452 - No server_name parameter into CONFIG_DATABASES_DATABASE_ADDED
> #RI-6452 - No server_name parameter into CONFIG_DATABASES_DATABASE_ADDED

- redisinsight/ui/src/components/messages/module-not-loaded-minimalized/ModuleNotLoadedMinimalized.tsx
see https://redislabs.atlassian.net/browse/RI-6537?focusedCommentId=1862035
> RI-6537: applying suggested change in comments

- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/InstancesNavigationPopover.tsx
- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/components/instances-list/InstancesList.tsx
- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/styles.module.scss
- redisinsight/ui/src/constants/index.ts
- redisinsight/ui/src/constants/sorting.ts
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.test.tsx
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/rdi/home/instance-list/RdiInstancesListWrapper.tsx
- redisinsight/ui/src/utils/instance/index.ts
- redisinsight/ui/src/utils/instance/instanceNavigation.ts
- redisinsight/ui/src/utils/tests/instance/instanceNavigation.spec.ts
RI-6577, RI-6578, RI-6579, RI-6580 (bugfixes for RI-6371)
> RI-6371 fix sorting, added empty list view

- redisinsight/ui/src/pages/browser/modules/key-details/components/unsupported-type-details/UnsupportedTypeDetails.tsx
> RI-6540: Change message for unsupported data types

- redisinsight/ui/src/pages/browser/components/browser-search-panel/BrowserSearchPanel.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.spec.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx
- redisinsight/ui/src/pages/browser/components/filter-key-type/constants.ts
- redisinsight/ui/src/slices/interfaces/instances.ts
- tests/e2e/helpers/constants.ts
- tests/e2e/tests/web/critical-path/browser/filtering.e2e.ts
bugfixes for RI-5547 (RI-6592, RI-6593)
> RI-5547 not show graph key when no graph module

- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/InstancesNavigationPopover.tsx
- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/components/instances-list/InstancesList.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/Job.spec.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/JobsWrapper.spec.tsx
- redisinsight/ui/src/slices/tests/rdi/pipeline.spec.ts
> RI-6615 fixed tests and navigation close when switch btw dbs

- redisinsight/api/src/main.ts
#RI-6509 - Create a free Cloud db
> #RI-6509 - Create a free Cloud db

- redisinsight/api/test/api/rdi/POST-rdi.test.ts
fix integration tests for RDI after adding "status" call to obtain vrrsion
> Fix ITests

- redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/components/instances-list/InstancesList.tsx
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
- redisinsight/ui/src/pages/instance/InstancePage.spec.tsx
- redisinsight/ui/src/pages/rdi/instance/InstancePage.spec.tsx
- redisinsight/ui/src/slices/app/context.ts
> RI-6651 fix empty cli opened when switching btw dbs

- .gitignore
- .vscode/launch.json
- redisinsight/api/package.json
- redisinsight/api/src/__mocks__/rdi.ts
- redisinsight/api/test/api/.mocharc.yml
- redisinsight/api/test/api/plugins/POST-databases-id-plugins-command_executions.test.ts
- redisinsight/api/test/helpers/data/redis.ts
- redisinsight/api/test/helpers/redis.ts
Allows easier tests debugging and fixes test ts issues
> API Integration test: fix types + add vscode debugger config

- redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/messages-view/MessageClaimPopover/MessageClaimPopover.spec.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/messages-view/MessageClaimPopover/MessageClaimPopover.tsx
It is required to be at least 1 consumer (not 2) after filtering consumers list
> RI-6823 fix claim button

- .github/e2e/test.app-image.sh
- tests/e2e/.testcafe-electron-rc.js
- tests/e2e/helpers/common.ts
- tests/e2e/tests/electron/critical-path/a-first-start-form/autodiscovery.e2e.ts
- tests/e2e/tests/electron/critical-path/database/add-ssh-db.e2e.ts
- tests/e2e/tests/electron/critical-path/files-auto-update/enablement-area-autoupdate.e2e.ts
- tests/e2e/tests/electron/critical-path/files-auto-update/promo-button-autoupdate.e2e.ts
- tests/e2e/tests/electron/critical-path/workbench/json-workbench.e2e.ts
- tests/e2e/tests/web/regression/database/navigation.e2e.ts
- skip unstable tests
- add skipComments
- add no-sandbox execution for app image for local Ubuntu execution
> Unifying local and CI runs for e2e test

- .github/build/build_modules.sh
- redisinsight/api/package.json
- redisinsight/api/patches/redis-parser+3.0.0.patch
- redisinsight/api/yarn.lock
Apply latest changes to the patch itself
Fix docker build errors due to postinstall script
> RI-6707 move back patch-package to RI main part

- redisinsight/api/src/modules/analytics/analytics.service.spec.ts
- redisinsight/api/src/modules/analytics/analytics.service.ts
- redisinsight/api/src/utils/converter.spec.ts
- redisinsight/api/src/utils/converter.ts
Rewrite function which converts sessionId string to a positive integer to match analytics tool schema
> RI-6928 fix sessionId calculation to match schema requirements

- tests/e2e/helpers/keys.ts
- tests/e2e/helpers/scripts/generate-big-data.ts
For some tests we need very big databases, since import in the cloud does not work well, this PR is adding generating and sending commands to appropriately sized DB
> RI-6425: generate big data

- Dockerfile
Just a proper fix of the root Dockerfile related to this issue https://github.com/RedisInsight/RedisInsight/issues/4404 + EUI icons patch fix
> RI-6930 fix root dockerfile

- redisinsight/api/src/modules/settings/settings.analytics.spec.ts
- redisinsight/api/src/modules/settings/settings.analytics.ts
- redisinsight/api/src/modules/settings/settings.service.spec.ts
- redisinsight/api/src/modules/settings/settings.service.ts
* fix imports
* fix tests
* fix tests
> Bugfix/be/release 2.68.0 (#4441)

- redisinsight/ui/src/pages/home/HomePage.tsx
Add instancesWithTagsCount data to the DATABSE_LIST_PAGE event
> Add instancesWithTagCount telemetry data to the DATABASE_LIST_PAGE event

- package.json
- redisinsight/ui/src/components/base/utils/FocusTrap.tsx
- redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/components/add-item/AddItem.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/components/edit-entire-item-action/EditEntireItemAction.tsx
- yarn.lock
replace EuiFocusTrap with custom implementation
> RI-6999 focus trap

- redisinsight/ui/src/packages/ri-explain/src/Explain.tsx
- redisinsight/ui/src/packages/ri-explain/src/main.tsx
- redisinsight/ui/src/packages/ri-explain/test-data/result-explain-pd.json
In some occasions visualization result is missing some connecting edges. This happens only when result is partially visualized, therefore always showing full result is a fix. Also added the option to pan the result in case it is too big for the viewing area
> RI-6966: fix incorrect visualization of explain results

- redisinsight/ui/src/pages/home/components/database-manage-tags-modal/ManageTagsModal.spec.tsx
- redisinsight/ui/src/pages/home/components/database-manage-tags-modal/ManageTagsModal.tsx
- redisinsight/ui/src/pages/home/components/database-manage-tags-modal/constants.ts
> RI-6384: limit tag's key and value lengths

- redisinsight/ui/src/components/item-list/ItemList.tsx
- redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
Same functionality as the source branch, PR - https://github.com/RedisInsight/RedisInsight/pull/4457 , just refactoring the database list wrapper and item list components columns logic to use useMemo.
> RI-6904: columns display hide refactor

- redisinsight/ui/src/slices/browser/rejson.ts
- redisinsight/ui/src/slices/tests/browser/rejson.spec.ts
The same logic as before, but with reversed conditions + tests.
> RI-6921: Don't fetch raw JSONs when their length is above threshold

- redisinsight/ui/src/pages/browser/modules/key-details/components/change-editor-type-button/ChangeEditorTypeButton.spec.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/change-editor-type-button/ChangeEditorTypeButton.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/change-editor-type-button/index.ts
- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-details/RejsonDetails.spec.tsx
- redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-details/RejsonDetails.tsx
Mode = `editable` when the flag is ON
Mode = `readOnly` when the flag is OFF
> RI-7015: Enable ChangeEditorTypeButton on envDependent flag

- redisinsight/ui/src/pages/home/components/database-list-header/DatabaseListHeader.tsx
- remove unneeded fragment 
- add missing flex grow property so columns and databases search are aligned right in the header
> Align search and column buttons to the right

- redisinsight/desktop/app.ts
- redisinsight/desktop/src/config/configMain.ts
- redisinsight/desktop/src/lib/aboutPanel/aboutPanel.ts
Adds "Enterprise - " prefix to the version number of Enterprise electron builds
> RI-7115: change enterprise build version prefix

- .github/workflows/aws-upload-enterprise.yml
- .github/workflows/enforce-branch-name-rules.yml
backport of https://github.com/RedisInsight/RedisInsight/pull/4558
> RI-7129: fix Enterprise build upload workflow

- redisinsight/ui/src/components/base/display/call-out/CallOut.tsx
- redisinsight/ui/src/components/consents-settings/ConsentsSettings.tsx
- redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndex.tsx
- redisinsight/ui/src/pages/settings/SettingsPage.tsx
> RI-7045: replace EuiCallOut

- redisinsight/api/yarn.lock
Coming after merging this snyk dependencies https://github.com/RedisInsight/RedisInsight/pull/4578, without the lock file being updated
> DEV: Fix lockfile

- redisinsight/ui/src/config/default.ts
- redisinsight/ui/vite.config.mjs
* RI-7103 add app info
* RI-7091 change env name to built-in one
* RI-7103 make appInfo available on runtime
(cherry picked from commit ff73f3984f19933e5140be447e85d804e910a3e3)
> Feature/ri 7103 split UI (#4583)

- redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.spec.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.tsx
popup was shown while loading was in progress
> RI-7187 fix behavior after verification. 

- redisinsight/ui/src/pages/browser/components/action-footer/ActionFooter.tsx
- redisinsight/ui/src/pages/browser/components/action-footer/index.ts
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyHash/AddKeyHash.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyList/AddKeyList.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyReJSON/AddKeyReJSON.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeySet/AddKeySet.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyStream/AddKeyStream.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyString/AddKeyString.tsx
- redisinsight/ui/src/pages/browser/components/add-key/AddKeyZset/AddKeyZset.tsx
Fixed the space between cancel/add row. Extracted it into a single components as we had plenty of copy-pasted places with the exact same code block
> RI-7228 - key details - space is missing between Add / Cancel

- redisinsight/ui/src/components/query/query-card/QueryCardHeader/styles.module.scss
Also fixes the time stamp being clipped for all dates
> RI-7239 - Workbench results - the execution time has a broken layout

- .github/workflows/code-coverage.yml
- redisinsight/ui/src/pages/database-analysis/components/header/Header.spec.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.spec.tsx
- redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.tsx
Recent merge broke the tests workflow
> fix invalid workflow

- redisinsight/ui/src/pages/vector-search/create-index/steps/styles.ts
> RI-7299: Fix "Command preview" spacing

- redisinsight/ui/src/pages/vector-search/manage-indexes/DeleteConfirmationButton.spec.tsx
- redisinsight/ui/src/pages/vector-search/manage-indexes/DeleteConfirmationButton.tsx
- redisinsight/ui/src/pages/vector-search/manage-indexes/IndexSection.spec.tsx
- redisinsight/ui/src/pages/vector-search/manage-indexes/IndexSection.tsx
- redisinsight/ui/src/pages/vector-search/manage-indexes/styles.ts
https://github.com/user-attachments/assets/79be1a2e-d2c1-4fad-9e0c-20ba21487e08
> RI-7298: Rework delete confirmation

- redisinsight/ui/src/pages/vector-search/query/HeaderActions.styles.ts
- redisinsight/ui/src/pages/vector-search/query/HeaderActions.tsx
- redisinsight/ui/src/pages/vector-search/query/StartWizardButton.spec.tsx
- redisinsight/ui/src/pages/vector-search/query/StartWizardButton.tsx
https://github.com/user-attachments/assets/5d278819-d496-442e-be79-946ca9e2cded
> RI-7317: Add Wizard flow start button

- .github/workflows/release-stage.yml
removing group_tests that were removed in this commit https://github.com/redis/RedisInsight/commit/4de818057c3f18cfcf728823666eb6ab1208937f leading to a break in the workflow
> Fixing broken workflow

- redisinsight/ui/src/components/oauth/shared/oauth-social-buttons/OAuthSocialButtons.tsx
> RI-7332 - Authentication options are not centered with their corresponding icons

- redisinsight/ui/src/components/base/external-link/ExternalLink.tsx
- redisinsight/ui/src/components/navigation-menu/hooks/useNavigation.ts
- redisinsight/ui/src/components/side-panels/components/header/styles.module.scss
- redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/expert-chat/components/no-indexes-initial-message/NoIndexesInitialMessage.tsx
- redisinsight/ui/src/components/side-panels/styles.module.scss
- redisinsight/ui/src/utils/formatters/markdown/remarkLink.ts
[Updated texts as per Olga's request](https://github.com/redis/RedisInsight/commit/4552aacb097d7f373de233062f44bc924ab0c51c)
[fixed tab spacing due to flex grow and a giant link in the copilot chat](https://github.com/redis/RedisInsight/commit/877800147340f625af09dc472ed5abdebb809a9d)
> RI-0000 bug fixes

- redisinsight/ui/src/components/notifications/Notifications.tsx
- redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx
Changed size of titles
Chnaged type of the toast from notice to informative
Clear all current Infinite messages when new ones arrive
> Ri-7333 infinite notifications

- redisinsight/ui/src/components/messages/module-not-loaded/ModuleNotLoaded.tsx
- redisinsight/ui/src/components/messages/module-not-loaded/styles.module.scss
- redisinsight/ui/src/components/oauth/oauth-connect-free-db/OAuthConnectFreeDb.tsx
- remove button icon;
- increase button size to match the components around it
| ---- | ---- |
| <img width="497" height="774" alt="image" src="https://github.com/user-attachments/assets/1b1e7808-00f3-4b3c-8f53-0c8cefd1b273" /> | <img width="495" height="775" alt="image-20250827-214746" src="https://github.com/user-attachments/assets/374c7f32-da79-462f-a9ab-1d43d56474e9" /> |
> RI-7376: Remove launch database icon

- redisinsight/ui/src/components/query/query-card/QueryCardHeader/QueryCardHeader.tsx
- redisinsight/ui/src/pages/vector-search/components/QueryCard.tsx
- redisinsight/ui/src/pages/vector-search/components/commands-view/CommandsView/CommandsView.tsx
- redisinsight/ui/src/pages/vector-search/create-index/steps/AddDataStep.tsx
- redisinsight/ui/src/pages/vector-search/create-index/steps/CreateIndexStep.tsx
- redisinsight/ui/src/pages/vector-search/create-index/steps/PreviewCommandDrawer.tsx
- redisinsight/ui/src/pages/vector-search/pages/VectorSearchCreateIndexPage.tsx
- redisinsight/ui/src/pages/vector-search/pages/VectorSearchPage.tsx
- redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx
- tests/playwright/helpers/conf.ts
- tests/playwright/helpers/utils.ts
- tests/playwright/pageObjects/pages/vector-search/create-index-page.ts
- tests/playwright/pageObjects/pages/vector-search/vector-search-page.ts
- tests/playwright/tests/vector-search/query.spec.ts
- tests/playwright/types/databases.ts
Created e2e tests to verify the queries on the "**Vector Search**" page:
- it should verify executing queries from the editor (and clearing the editor + the results)
- it should verify all action buttons in the query results (full-screen, delete, re-run, collapse/uncollapse)
- We have page objects that define selectors for all the main elements we need to use in our tests. These page object classes also provide helper utilities that we can use in our test cases to keep them concise yet informative about what’s happening. They serve as a layer of abstraction.
- We have a setup step that initializes the environment and prepares a Redis instance suitable for our tests. Then, we open the correct page (navigate through the UI until we reach it) and prepare the necessary steps required by the …
> RI-7275 Create e2e tests for queries on the "Vector Search" page

- redisinsight/ui/src/components/virtual-table/VirtualTable.tsx
- redisinsight/ui/src/pages/browser/components/key-tree/styles.module.scss
> RI-7431: No results found

- redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx
- redisinsight/ui/src/utils/index/generateFtCreateCommand.spec.ts
- redisinsight/ui/src/utils/index/generateFtCreateCommand.ts
| Before                                                                                                                                                        | After                                                                                                                                                         |
| ------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <img width="556" height="51" alt="Screenshot 2025-09-25 at 14 36 18" src="https://github.com/user-attachments/assets/01e706c9-342f-497e-9de9-a60e6c30a8f1" …
> RI-7548,RI-7499: Vector search polishment

- redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-formatter/KeyDetailsHeaderFormatter.styles.tsx
> RI-7610: remove purple color while hovering on formatters select
