redisinsight/ui/src/utils/commands.ts, redisinsight/ui/src/utils/tests/commands.spec.ts
#RI-2065 - handle the case when complexity is an array of strings
=> fix/ Short complexity notation

tests/e2e/pageObjects/cli-page.ts, tests/e2e/tests/regression/cli/cli-command-helper.e2e.ts
The following tests are added:
- Verify that user can see in Command helper and click on new group "Search", can choose it and see list of commands in the group;
- Verify that user can see in Command helper and click on new group "JSON", can choose it and see list of commands in the group.
=> Command Helper E2E tests 

redisinsight/api/src/__mocks__/analytics.ts, redisinsight/api/src/constants/telemetry-events.ts, redisinsight/api/src/modules/shared/services/instances-business/instances-analytics.service.spec.ts, redisinsight/api/src/modules/shared/services/instances-business/instances-analytics.service.ts, redisinsight/api/src/modules/shared/services/instances-business/instances-business.service.ts
* #RI-1608 - add InstanceListReceivedEvent
* #RI-1608 - update event data for InstanceAddedEvent
=> Improve/ Databases events

redisinsight/api/src/__mocks__/analytics.ts, redisinsight/api/src/constants/telemetry-events.ts, redisinsight/api/src/modules/cli/controllers/cli.controller.ts, redisinsight/api/src/modules/cli/services/cli-analytics/cli-analytics.service.spec.ts, redisinsight/api/src/modules/cli/services/cli-analytics/cli-analytics.service.ts, redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.spec.ts, redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts, redisinsight/api/src/modules/cli/services/cli-tool/cli-tool.service.ts, redisinsight/api/src/modules/shared/services/base/redis-consumer.abstract.service.spec.ts, redisinsight/api/src/modules/shared/services/base/redis-consumer.abstract.service.ts, redisinsight/api/src/utils/redis-connection-helper.spec.ts, redisinsight/api/src/utils/redis-connection-helper.ts, redisinsight/ui/src/slices/workbench/wb-settings.ts
#RI-1100 - add telemetry events for the workbench
=> Feature/ Workbench - telemetry events

redisinsight/ui/src/pages/home/HomePage.tsx, redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx, redisinsight/ui/src/pages/home/constants/help-links.ts, redisinsight/ui/src/slices/instances.ts, redisinsight/ui/src/styles/components/_callout.scss, redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss, redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss, redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
#RI-2078 - close edit mode after db deletion
#RI-2103 - fix text of button
#RI-2110 - fix styles for callout for light theme
=> #RI-2078, #RI-2103, #RI-2110 

redisinsight/ui/src/components/navigation-menu/NavigationMenu.tsx, redisinsight/ui/src/components/shortcuts-flyout/ShortcutsFlyout.spec.tsx, redisinsight/ui/src/components/shortcuts-flyout/ShortcutsFlyout.tsx
=> Added test ids for e2e tests

redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/EnablementArea.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/InternalPage/InternalPage.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/LazyInternalPage/LazyInternalPage.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementAreaCollapse/EnablementAreaCollapse.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementAreaWrapper.tsx
#RI-2101 [Telemetry] Cover additional events in Workbench
=> #RI-2101 [Telemetry] Cover additional events in Workbench

redisinsight/ui/src/components/query/Query/Query.tsx, redisinsight/ui/src/constants/monacoRedis.ts, redisinsight/ui/src/styles/base/_monaco.scss, redisinsight/ui/src/utils/monacoRedisMonarchTokensProvider.ts
* #RI-2150 - Hints with arguments are opened on Ctrl+Space together with commands suggestions list
* #RI-2079 - Line for argument in autocomplete in Workbench
* #RI-2151 - Command suggestion list is not displayed for FT. commands after command correction
=> #RI-2150, #RI-2079, #RI-2151

redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/EnablementArea.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/Group/Group.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/Group/styles.scss, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/InternalLink/InternalLink.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/PlainText/PlainText.tsx, redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/styles.module.scss
#RI-2162 refactor enablement area tree view
=> Fix/ EA tree view items

tests/e2e/tests/regression/cli/cli-command-helper.e2e.ts
The following tests are added:
-Verify that user can see HyperLogLog title in Command Helper for this command group;
-Verify that user can see all separated groups for AI json file (model, tensor, inference, script).
=> [E2E] Tests with AI groups and changed command group name added

tests/e2e/pageObjects/help-center-page.ts, tests/e2e/pageObjects/index.ts, tests/e2e/pageObjects/my-redis-databases-page.ts, tests/e2e/pageObjects/shortcuts-page.ts, tests/e2e/tests/regression/shortcuts/shortcuts.e2e.ts
New e2e test with shortcuts page is added
=> E2E test with Shortcuts is added

redisinsight/main.dev.ts, redisinsight/menu.ts, redisinsight/ui/src/components/cli/components/cli-helper/CliHelper/styles.module.scss, redisinsight/ui/src/pages/workbench/components/wb-view/WBView/styles.module.scss, redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.spec.tsx, redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx, redisinsight/ui/src/slices/workbench/wb-settings.ts
* #RI-2135 - Request POST /api/instance/{id}/cli//send-command is sent for command execution in Workbench
* #RI-2169 - Area's layout has shifted
=> #RI-2169, #RI-2135

tests/e2e/pageObjects/workbench-page.ts, tests/e2e/tests/regression/workbench/autocomplete.e2e.ts, tests/e2e/tests/regression/workbench/empty-command-history.e2e.ts
The following tests were added:
- Verify that user can see placeholder text in Workbench history if no commands have not been run yet
- Verify that user can see static list of arguments is displayed when he enters the command in Editor in Workbench
- Verify that user can close the static list of arguments by pressing “ESC”
- Verify that user can see the static list of arguments when he uses “Ctrl+Shift+Space” combination for already entered command for Windows
=> [E2E] Workbench tests are added

redisinsight/ui/src/pages/workbench/components/enablament-area/EnablementArea/components/InternalPage/InternalPage.tsx, tests/e2e/pageObjects/workbench-page.ts, tests/e2e/tests/regression/workbench/default-scripts-area.e2e.ts, tests/e2e/tests/regression/workbench/scripting-area.e2e.ts
The following tests are added:
- Verify that user can see saved article in Enablement area when he leaves Workbench page and goes back again;
- Verify that user can see an indication (green triangle) of commands from the left side of the line numbers.
=> [E2E] Command indicator and context saving for Workbench tests added

redisinsight/api/src/modules/cli/services/cli-business/cli-business.service.ts
* #RI-2142 - fix WORKBENCH_COMMAND_ERROR_RECEIVED telemetry event
* #RI-2138 - fix WORKBENCH_CLIENT_CONNECTION_ERROR telemetry event
=> Fix/ Workbench Telemetry events

redisinsight/api/src/dto/server.dto.ts, redisinsight/api/src/modules/core/providers/server-on-premise/server-on-premise.service.spec.ts, redisinsight/api/src/modules/core/providers/server-on-premise/server-on-premise.service.ts, redisinsight/api/src/modules/core/services/analytics/analytics.service.spec.ts, redisinsight/api/src/modules/core/services/analytics/analytics.service.ts, redisinsight/api/test/api/info/GET-info.test.ts, redisinsight/ui/src/components/config/Config.tsx, redisinsight/ui/src/telemetry/interfaces.ts, redisinsight/ui/src/telemetry/segment.ts
#RI-2203 - add Session ID for telemetry events
=> Fix/ Amplitude Session ID

redisinsight/ui/src/components/bottom-group-components/components/bottom-group-minimized/BottomGroupMinimized.tsx, redisinsight/ui/src/components/command-helper/CommandHelperHeader/CommandHelperHeader.spec.tsx, redisinsight/ui/src/components/command-helper/CommandHelperHeader/CommandHelperHeader.tsx, redisinsight/ui/src/pages/home/components/AddInstanceControls/AddInstanceControls.tsx, redisinsight/ui/src/pages/home/components/AddInstanceControls/styles.module.scss, redisinsight/ui/src/pages/workbench/components/module-not-loaded/ModuleNotLoaded.tsx, redisinsight/ui/src/pages/workbench/components/module-not-loaded/styles.module.scss, redisinsight/ui/src/pages/workbench/constants.ts, redisinsight/ui/src/slices/cli/cli-settings.ts, redisinsight/ui/src/slices/interfaces/cli.ts, redisinsight/ui/src/slices/tests/cli/cli-settings.spec.ts, redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss, redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss, redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss, redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
* #RI-2241 - CLI and Command helper icons are not in blue when hidden
* #RI-2245 - Background is not fully displayed inside of the button
* #RI-2246 - Link to the Cloud is not correct
=> #RI-2241, #RI-2245, #RI-2246

redisinsight/ui/src/components/cli/components/cli-body/CliBody/CliBody.tsx, redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.spec.tsx, redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx, redisinsight/ui/src/components/cli/components/cli-input/CliInputWrapper.tsx, redisinsight/ui/src/constants/cliOutput.tsx, redisinsight/ui/src/pages/instance/InstancePage.tsx, redisinsight/ui/src/pages/workbench/components/wb-view/WBViewWrapper.tsx, redisinsight/ui/src/slices/cli/cli-output.ts, redisinsight/ui/src/slices/tests/cli/cli-output.spec.ts, redisinsight/ui/src/utils/cliHelper.tsx, redisinsight/ui/src/utils/commands.ts, redisinsight/ui/src/utils/monacoRedisComplitionProvider.ts, redisinsight/ui/src/utils/monacoUtils.ts, redisinsight/ui/src/utils/tests/monacoUtils.spec.ts
* #RI-2167 - Allow repeating commands
=> * #RI-2167 - Allow repeating commands

redisinsight/ui/src/components/monitor-config/MonitorConfig.spec.tsx, redisinsight/ui/src/components/monitor-config/MonitorConfig.tsx, redisinsight/ui/src/constants/socketEvents.ts
#RI-2332 handle socket reconnect
=> Fix/ Handle socket reconnect

redisinsight/ui/src/components/database-list-modules/DatabaseListModules.tsx, redisinsight/ui/src/components/database-list-modules/styles.module.scss, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/styles.module.scss, redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx, redisinsight/ui/src/pages/home/components/DatabasesListComponent/styles.module.scss, redisinsight/ui/src/pages/home/styles.scss, redisinsight/ui/src/utils/redistack.ts, redisinsight/ui/src/utils/tests/redistack.spec.ts
#RI-2513 - Edit mode doesn't have modules list
#RI-2514 - Number of icons should be depend on screen resolution
#RI-2515 - Hovering over each module icon, tooltip hides and appears again
#RI-2516 - On Browser page module icon should display tooltip with info per 1 module
#RI-2517 - +N number should be displayed only when N>=2
#RI-2521 - When user adds new DB with port not 6379 but with relevant list of modules, DB is highlighted
=> #RI-2513, #RI-2514, #RI-2515, #RI-2516, #RI-2517, #RI-2521

redisinsight/ui/src/constants/keys.ts, redisinsight/ui/src/constants/prop-types/keys.ts, redisinsight/ui/src/pages/browser/components/filter-key-type/constants.ts, redisinsight/ui/src/pages/browser/components/key-details/KeyDetails/KeyDetails.tsx, redisinsight/ui/src/pages/browser/components/modules-type-details/ModulesTypeDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/modules-type-details/ModulesTypeDetails.tsx, redisinsight/ui/src/pages/browser/components/unsupported-type-details/UnsupportedTypeDetails.tsx, redisinsight/ui/src/pages/browser/components/unsupported-type-details/styles.module.scss
#RI-2457 - Update message in Browser for TimeSeries and Graph data types
=> #RI-2457 - Update message in Browser for TimeSeries and Graph data types

redisinsight/ui/src/components/query/DedicatedEditor/DedicatedEditor.tsx, redisinsight/ui/src/components/query/Query/Query.tsx
#RI-2579 - fix clearing dedicated editor
=> #RI-2576 - add indents for dedicated editor

redisinsight/ui/src/packages/redisgraph/src/graphd3.ts, redisinsight/ui/src/packages/redisgraph/src/utils.ts
=> [RedisGraph Plugin] Add support for node label text wrapping

redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
Use `id` of node when no `name` and `title`
=> [RedisGraph] Use Id when no `name` and `title`

redisinsight/ui/src/packages/redisgraph/src/constants.ts, redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
```cypher
graph.DELETE test
graph.QUERY test "CREATE (n1:L1), (n2), (n3:L3)"
graph.QUERY test "MATCH (n3:L3), (n) MERGE (n3)<-[r0:T1]-(n)"
graph.QUERY test "MATCH (n), (n1:L1) MERGE (n)<-[r1:T2]-(n1)"
graph.QUERY test "MATCH p = (x1)-[r]-(x2) return p"
```
=> [RedisGraph] Add support for multiple edges from a node

redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.spec.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx
=> #RI-2727 - UI for SNI

redisinsight/ui/src/components/monitor/Monitor/Monitor.tsx, redisinsight/ui/src/components/monitor/Monitor/styles.module.scss, redisinsight/ui/src/components/monitor/MonitorLog/MonitorLog.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx
#RI-2738 - add state with borders when monitor is running
#RI-2390 - change label
=> #RI-2745 - fix showing log

redisinsight/ui/src/components/cli/components/cli-body/CliBodyWrapper.tsx, redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
* #RI-2660 - ">" symbol displayed in wrong way in CLI
* #RI-2698 - Autoselect for keys works incorrectly when using filter by key type
=> #RI-2660, #RI-2698

redisinsight/ui/src/packages/redisgraph/src/Graph.tsx, redisinsight/ui/src/packages/redisgraph/src/graphd3.ts, redisinsight/ui/src/packages/redisgraph/src/styles/styles.less, redisinsight/ui/src/packages/redisgraph/src/utils.ts
https://user-images.githubusercontent.com/20211167/165246592-32e3c010-d715-4a96-931f-6aae5e3f92fb.mp4
=> [RedisGraph] Support for node grouping and pulsing

redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx, redisinsight/ui/src/components/inline-item-editor/styles.module.scss, redisinsight/ui/src/pages/browser/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/pages/browser/components/stream-details/StreamDetails/StreamDetails.tsx, redisinsight/ui/src/pages/browser/components/stream-details/StreamDetailsWrapper.tsx, redisinsight/ui/src/pages/slowLog/components/Actions/Actions.tsx, redisinsight/ui/src/pages/slowLog/components/SlowLogConfig/SlowLogConfig.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/utils/tests/validations.spec.ts, redisinsight/ui/src/utils/validations.ts
* #RI-2856 - The 'three dots' button shouldn't be visible
* #RI-2857 - The 'Entry ID' column header should be hidden when there are no entries in the Stream
* #RI-2854 - The delete button position shifts to the right after deletion of entry when the number of fields decreases
* #RI-2879 - The incorrect rate is applied in the auto-refresh value after reload of the page
=> #RI-2856, #RI-2857, #RI-2854, #RI-2879

redisinsight/ui/src/components/range-filter/RangeFilter.spec.tsx, redisinsight/ui/src/components/range-filter/RangeFilter.tsx, redisinsight/ui/src/components/range-filter/styles.module.scss, redisinsight/ui/src/components/virtual-table/styles.module.scss, redisinsight/ui/src/pages/browser/components/stream-details/StreamDetails/StreamDetails.tsx, redisinsight/ui/src/slices/browser/stream.ts
#RI-2912 update stream range filter controls cursor
#RI-2913 fix stream details table height 
add onMouseUp event to range filter
add cancel request for stream
=> #RI-2913-table height, fetchstream requests,  #RI-2912-cursor

redisinsight/ui/src/pages/browser/components/rejson-details/JSONScalar/JSONScalar.tsx, redisinsight/ui/src/pages/browser/components/rejson-details/RejsonDetailsWrapper.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/rejson.ts, redisinsight/ui/src/slices/interfaces/instances.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-2965 - fix duplication requests after add key
#RI-2966 - fix json display value
=> #RI-2965, #RI-2966

redisinsight/api/src/constants/redis-error-codes.ts, redisinsight/api/src/modules/browser/browser.module.ts, redisinsight/api/src/modules/browser/constants/browser-tool-commands.ts, redisinsight/api/src/modules/browser/controllers/stream/consumer-group.controller.ts, redisinsight/api/src/modules/browser/controllers/stream/consumer.controller.ts, redisinsight/api/src/modules/browser/dto/stream.dto.ts, redisinsight/api/src/modules/browser/services/stream/consumer-group.service.ts, redisinsight/api/src/modules/browser/services/stream/consumer.service.ts
#RI-2933 BE implementation for consumer groups list
=> #RI-2931 BE implementation for create new consumer group(s)

redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx, redisinsight/ui/src/pages/browser/components/stream-details/consumers-view/ConsumersViewWrapper.tsx, redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsView/styles.module.scss, redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsViewWrapper.tsx, redisinsight/ui/src/pages/browser/components/stream-details/messages-view/MessagesView/styles.module.scss, redisinsight/ui/src/pages/browser/components/stream-details/messages-view/MessagesViewWrapper.tsx
* #RI-2999 - The Group name column is not visible in small screen
* #RI-3003 - The Group name with long value is not truncated
* #RI-3005 - The long Consumer name is not truncated
=> #RI-2999, #RI-3003, #RI-3005

redisinsight/ui/src/pages/browser/components/stream-details/constants.ts, redisinsight/ui/src/pages/browser/components/stream-details/stream-tabs/StreamTabs.tsx, redisinsight/ui/src/pages/browser/components/stream-details/stream-tabs/styles.module.scss
* #RI-3004 - The navigation icon in the tabs list is wider then on mockups
* #RI-3006 - There is no space between the opened Pending message and arrow icon in the navigation
=> #RI-3004, #RI-3006 

redisinsight/ui/src/packages/redisgraph/src/Graph.tsx, redisinsight/ui/src/packages/redisgraph/src/graphd3.ts, redisinsight/ui/src/packages/redisgraph/src/styles/styles.less
Related to: https://github.com/RedisInsight/RedisInsight/issues/500
Demo:
https://user-images.githubusercontent.com/20211167/172401692-870c292f-402e-4dc2-b817-e7ad8e5f85ff.mp4
=> RedisGraph - Toggle visibility of automatically retrieved edges

redisinsight/ui/src/pages/pubSub/components/messages-list/MessagesList/MessagesList.spec.tsx, redisinsight/ui/src/pages/pubSub/components/messages-list/MessagesList/MessagesList.tsx, redisinsight/ui/src/pages/pubSub/components/messages-list/MessagesList/styles.module.scss, redisinsight/ui/src/pages/pubSub/components/messages-list/MessagesListWrapper.tsx, redisinsight/ui/src/pages/pubSub/styles.module.scss
=> #RI-2988 - PubSub debug mode

redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
#RI-3081 - Event AUTO_REFRESH_ENABLED should be sent when user changes rate
#RI-3082 - Event KEY_DETAILS_AUTO_REFRESH_DISABLED doesn't contain length
=> #RI-3081, #RI-3082

redisinsight/ui/src/packages/redisgraph/src/Graph.tsx, redisinsight/ui/src/packages/redisgraph/src/graphd3.ts
Refer: https://redislabs.atlassian.net/browse/RI-3062?focusedCommentId=1591713
=> [RedisGraph] Have graph automatic edges visibility disabled by default

redisinsight/ui/src/pages/browser/components/stream-details/StreamDetailsWrapper.tsx, redisinsight/ui/src/slices/browser/stream.ts, redisinsight/ui/src/utils/streamUtils.ts
* #RI-3130 - Number of consumers are not updated when user goes between tabs in stream
* #RI-3131 - Consumer groups are cached when user creates new stream
=> #RI-3130, #RI-3131

redisinsight/ui/src/components/virtual-tree/components/Node/Node.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteContent/BulkDeleteContent.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
* #RI-3292 - Error messages overlappses if key name is too long
* #RI-3287 - Switching between tree view and browser, doesn't apply filters
* #RI-3288 - New part of keys are not displayed in Tree View when user scans more
=> #RI-3292, #RI-3287, #RI-3288

redisinsight/ui/src/components/multi-search/MultiSearch.tsx, redisinsight/ui/src/components/virtual-grid/VirtualGrid.tsx, redisinsight/ui/src/components/virtual-grid/utils.tsx, redisinsight/ui/src/constants/cliOutput.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsInfo/BulkActionsInfo.tsx, redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/key-details/KeyDetailsWrapper.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx, redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx, redisinsight/ui/src/slices/cli/cli-settings.ts
* #RI-3304 - JSON key is not updated when user changes value in CLI
* #RI-3308 - Clicking on search keys button user gets "Something went wrong" 
* #RI-3170 - Stream grid is brocken when user opens full screen
* #RI-3304 - JSON key is not updated when user changes value in CLI
* #RI-3311 - Promotion message should be displayed only once when user opens CLI
=> #RI-3304, #RI-3308, #RI-3170, #RI-3304, #RI-3311

redisinsight/ui/src/pages/browser/components/stream-details/groups-view/GroupsView/GroupsView.tsx
#RI-3370 - Consumer Group sorting not working
=> #RI-3370 - Consumer Group sorting not working

redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/KeyValueFormatter.tsx, redisinsight/ui/src/pages/browser/components/key-details-header/components/Formatter/constants.ts, redisinsight/ui/src/utils/formatters/bufferFormatters.ts, redisinsight/ui/src/utils/formatters/valueFormatters.tsx, redisinsight/ui/src/utils/tests/formatters/bufferFormatters.spec.ts
-  add HEX formatter
- hex string validation: (no spaces, no /n, % 2 === 0, includes only 0-9 and a-f symbols, A-F symbols
=> #RI-3223-add hex formatter

redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActions.tsx, redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx, redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx, redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx
* #RI-3390 - Value in key field tooltip is displayed in Ascii for Ascii formatter
* #RI-3389 - When bulk deleted completed, new selected data type is displayed on screen results
=> #RI-3389, #RI-3390

redisinsight/ui/src/pages/browser/styles.module.scss
#RI-3403 - Layout for scanned keys info is brocken for smaller screen resolution
=> #RI-3403 - Layout for scanned keys info is brocken for smaller screen resolution

redisinsight/ui/src/utils/formatters/bufferFormatters.ts
#RI-3423 - ASCII redundantly escapes symbols after saving edit mode
=> #RI-3423 - ASCII redundantly escapes symbols after saving edit mode

redisinsight/ui/src/packages/redisearch/src/utils/parseResponse.ts
#RI-3416 - Command result with nocontent option is not correct
=> #RI-3416 - Command result with nocontent option is not correct

tests/e2e/tests/critical-path/cli/cli-critical.e2e.ts
update for test
Verify that when user enters in CLI RediSearch/JSON commands (FT.CREATE, FT.DROPINDEX/JSON.GET, JSON.DEL), he can see hints with arguments
=> fixes for failed test

redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/hash-details/styles.module.scss, redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/list-details/styles.module.scss, redisinsight/ui/src/styles/base/_helpers.scss
#RI-3430 - Edit field with unprintable characters are not highlighted in yellow
=> #RI-3430 - Edit field with unprintable characters are not highlighted  in yellow

redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx, redisinsight/ui/src/pages/browser/components/string-details/styles.module.scss
#RI-3430 - Edit field with unprintable characters are not highlighted in yellow
=> #RI-3430 - Edit field with unprintable characters are not highlighted in yellow

redisinsight/ui/src/pages/browser/components/key-list/KeyList.spec.tsx, redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-3438 - Some Keys are displayed with empty names when page was scrolled and then reopened
=> #RI-3438 - Some Keys are displayed with empty names 

redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/hash-details/styles.module.scss, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/list-details/styles.module.scss, redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx, redisinsight/ui/src/services/storage.ts
* change storage get item method
=> #RI-3447 - add space for formatter editor buttons, change calculating height behavior

redisinsight/ui/src/slices/browser/keys.ts
#RI-3584 - Tree view is displayed on Browser page by default when switching between databases
=> #RI-3584 - Tree view is displayed on Browser page by default

redisinsight/ui/src/components/charts/area-chart/AreaChart.tsx
#RI-3643 - Graph line is displayed in the middle of graph when all keys with no expiry
=> #RI-3643 - Graph line is displayed in the middle of graph

tests/e2e/tests/smoke/browser/add-keys.e2e.ts, tests/e2e/tests/smoke/browser/edit-key-name.e2e.ts, tests/e2e/tests/smoke/browser/edit-key-value.e2e.ts, tests/e2e/tests/smoke/browser/filtering.e2e.ts, tests/e2e/tests/smoke/browser/hash-field.e2e.ts, tests/e2e/tests/smoke/browser/json-key.e2e.ts, tests/e2e/tests/smoke/browser/list-key.e2e.ts, tests/e2e/tests/smoke/browser/list-of-keys-verifications.e2e.ts, tests/e2e/tests/smoke/browser/set-key.e2e.ts, tests/e2e/tests/smoke/browser/set-ttl-for-key.e2e.ts, tests/e2e/tests/smoke/browser/verify-key-details.e2e.ts, tests/e2e/tests/smoke/browser/verify-keys-refresh.e2e.ts, tests/e2e/tests/smoke/browser/zset-key.e2e.ts, tests/e2e/tests/smoke/cli/cli-command-helper.e2e.ts, tests/e2e/tests/smoke/cli/cli.e2e.ts, tests/e2e/tests/smoke/database/add-db-from-welcome-page.e2e.ts, tests/e2e/tests/smoke/database/add-sentinel-db.e2e.ts, tests/e2e/tests/smoke/database/add-standalone-db.e2e.ts, tests/e2e/tests/smoke/database/connecting-to-the-db.e2e.ts, tests/e2e/tests/smoke/database/delete-the-db.e2e.ts, tests/e2e/tests/smoke/database/edit-db.e2e.ts, tests/e2e/tests/smoke/workbench/json-workbench.e2e.ts, tests/e2e/tests/smoke/workbench/scripting-area.e2e.ts
Refactoring of e2e smoke tests from https://redislabs.atlassian.net/browse/RI-3530
Fixed:
1) Many small tests are merged to save test execution time
2) Comments are reduced to one formatting
3) chance.word() replaced by common.generateWord()
4) Error messages of expects are fixed (previously most of them were incorrect)
5) "rte: rte.standalone" moved from tests meta to fixture meta
6) Different updates for some tests
=> RI-3530 smoke tests refactoring

.gitignore, redisinsight/api/src/modules/browser/controllers/keys/keys.controller.ts, redisinsight/api/test/api/keys/POST-instance-id-keys.test.ts
#RI-3650 - [BE] status error on get big key
=> #RI-3650 - [BE] status error on get big key

redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts
#RI-3650 - [FE] 431 status error on get big key
=> #RI-3650 - [FE] 431 status error on get big key

redisinsight/ui/src/components/charts/bar-chart/BarChart.spec.tsx, redisinsight/ui/src/components/charts/bar-chart/BarChart.tsx, redisinsight/ui/src/components/charts/bar-chart/index.ts, redisinsight/ui/src/components/charts/bar-chart/styles.module.scss, redisinsight/ui/src/components/charts/index.ts, redisinsight/ui/src/components/inline-item-editor/styles.module.scss, redisinsight/ui/src/pages/databaseAnalysis/components/analysis-ttl-view/ExpirationGroupsView.spec.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/analysis-ttl-view/ExpirationGroupsView.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/analysis-ttl-view/styles.module.scss, redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss, redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss, redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss, redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
#RI-3646 - Change the Expiration timeline to bar charts
#RI-3721 - Buttons cancel/save are not visible fully
=> #RI-3646, #RI-3721 

redisinsight/ui/src/pages/databaseAnalysis/components/analysis-data-view/AnalysisDataView.spec.tsx, redisinsight/ui/src/slices/interfaces/instances.ts, redisinsight/ui/src/utils/cliHelper.tsx
#RI-3725 - Module is not found when RediSearch Light is loaded
=> #RI-3725 - Module is not found when RediSearch Light is loaded

redisinsight/ui/src/components/analytics-tabs/constants.ts, redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/header/Header.spec.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/header/Header.tsx, redisinsight/ui/src/slices/app/context.ts, redisinsight/ui/src/slices/interfaces/app.ts, redisinsight/ui/src/slices/tests/app/context.spec.ts
#RI-3748 - Loading endless spinner in Browser displayed when a user creates keys in Workbench
=> #RI-3748 - Loading endless spinner in Browser displayed when user creates keys in Workbench

redisinsight/ui/src/components/cli/components/cli-body/CliBody/CliBody.tsx, redisinsight/ui/src/constants/cliOutput.tsx
=> #RI-3740 - allow selecting text by double-click in cli

redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/redisearch.ts, redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts
* #RI-3756 - Scan more button is displayed after switching from Browser
* #RI-3763 - DB not scanned when returning from redisearch mode tree view
=> #RI-3756, #RI-3763

redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/redisearch.ts, redisinsight/ui/src/slices/tests/browser/hash.spec.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts, redisinsight/ui/src/slices/tests/browser/list.spec.ts, redisinsight/ui/src/slices/tests/browser/redisearch.spec.ts, redisinsight/ui/src/slices/tests/browser/set.spec.ts, redisinsight/ui/src/slices/tests/browser/zset.spec.ts
#RI-3764 - List of keys not refreshed after deleting key in redisearch mode
=> #RI-3764 - List of keys not refreshed after deleting key in redisearch mode

redisinsight/ui/src/components/query/QueryWrapper.tsx, redisinsight/ui/src/constants/keys.ts, redisinsight/ui/src/pages/browser/BrowserPage.tsx, redisinsight/ui/src/pages/browser/components/filter-key-type/constants.ts, redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/components/key-details/KeyDetails/KeyDetails.tsx, redisinsight/ui/src/pages/browser/components/key-details/KeyDetailsWrapper.tsx, redisinsight/ui/src/pages/browser/styles.module.scss, redisinsight/ui/src/slices/browser/hash.ts
#RI-3744 - fix telemetry event
#RI-3749 - fix hash key context after deletion last field 
#RI-3743 - fix tooltip truncation
#RI-3741 - fix key types display
=> bug fix #RI-3744 #RI-3749 #RI-3743 #RI-3741

redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.spec.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceForm/InstanceForm.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.spec.tsx, redisinsight/ui/src/pages/home/components/AddInstanceForm/InstanceFormWrapper.tsx, redisinsight/ui/src/pages/home/components/DatabaseAlias/DatabaseAlias.tsx, redisinsight/ui/src/slices/instances/instances.ts, redisinsight/ui/src/slices/instances/sentinel.ts, redisinsight/ui/src/slices/interfaces/instances.ts, redisinsight/ui/src/slices/tests/instances/instances.spec.ts, redisinsight/ui/src/slices/tests/instances/sentinel.spec.ts
* #RI-3606 - [FE][Docker] User cannot rename database
* #RI-3608 - [FE][Docker] No Redis Stack icon on Edit screen
* #RI-3610 - [FE][Docker] Error on Sentinel cloning
* fix some tipes
=> #RI-3606, #RI-3608, #RI-3610

redisinsight/ui/src/pages/redisStack/components/edit-connection/EditConnection.tsx
#RI-3828 - Connection page in Redis Stack has no DB info
=> #RI-3828 - Connection page in Redis Stack has no DB info

redisinsight/ui/src/pages/home/components/DatabasesListComponent/DatabasesListWrapper.tsx
#RI-3843 - Indexed keys from previous DB are displayed when user connects to another DB
=> #RI-3843 - Indexed keys from previous DB are displayed 

redisinsight/ui/src/components/query/QueryWrapper.tsx, redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx, redisinsight/ui/src/pages/browser/components/key-list/KeyList.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/top-keys/Table.tsx, redisinsight/ui/src/pages/databaseAnalysis/components/top-namespace/Table.tsx, redisinsight/ui/src/pages/workbench/WorkbenchPage.spec.tsx, redisinsight/ui/src/slices/app/context.ts, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/redisearch.ts, redisinsight/ui/src/slices/interfaces/app.ts, redisinsight/ui/src/slices/tests/app/context.spec.ts
* #RI-3848 - Button is displayed with incorrect scanned parameters
* Upper case for all commands in workbench
=> * #RI-3848 - Button is displayed with incorrect scanned parameters

redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
#RI-3862 -  Null index error message is displayed when the user switches between views in Search
=> #RI-3862 -  Null index error message is displayed when the user switches between views in Search

redisinsight/ui/src/packages/redisgraph/src/Graph.tsx
A tiny regression occured due to this: https://github.com/RedisInsight/RedisInsight/pull/1444
Now that we consider graph Ids as integer as received by redisgraph, when rendering label on a node, convert the id from integer to string if id is chosen as label.
=> [RedisGraph] Convert id to string before rendering node label

redisinsight/ui/src/pages/browser/components/key-tree/KeyTree.tsx
#RI-3893 - Wrong key is displayed sometimes when switching between browser/tree view a several times
=> #RI-3893 - Wrong key is displayed sometimes

.circleci/config.yml, redisinsight/api/src/__mocks__/database-import.ts, redisinsight/api/src/common/utils/certificate-import.util.ts, redisinsight/api/src/common/utils/index.ts, redisinsight/api/src/constants/error-messages.ts, redisinsight/api/src/modules/database-import/certificate-import.service.ts, redisinsight/api/src/modules/database-import/database-import.module.ts, redisinsight/api/src/modules/database-import/database-import.service.spec.ts, redisinsight/api/src/modules/database-import/database-import.service.ts, redisinsight/api/src/modules/database-import/dto/import.database.dto.ts, redisinsight/api/src/modules/database-import/exceptions/index.ts, redisinsight/api/src/modules/database-import/exceptions/invalid-ca-certificate-body.exception.ts, redisinsight/api/src/modules/database-import/exceptions/invalid-certificate-name.exception.ts, redisinsight/api/src/modules/database-import/exceptions/invalid-client-certificate-body.exception.ts, redisinsight/api/src/modules/database-import/exceptions/invalid-client-private-key.exception.ts, redisinsight/api/src/modules/database/database-connection.service.ts, redisinsight/api/src/modules/database/entities/database.entity.ts, redisinsight/api/src/modules/database/models/database.ts, redisinsight/api/src/modules/redis-sentinel/redis-sentinel.service.spec.ts, redisinsight/api/src/modules/redis-sentinel/redis-sentinel.service.ts, redisinsight/api/src/modules/redis/redis.service.ts
#RI-3684 - Base BE implementation. Import certs from files
=> #RI-3728 - Base BE implementation. Import certs by plain values

redisinsight/api/src/modules/browser/services/rejson-rl-business/rejson-rl-business.service.spec.ts, redisinsight/api/src/modules/browser/services/rejson-rl-business/rejson-rl-business.service.ts, redisinsight/api/test/api/rejson-rl/POST-databases-id-rejson_rl-get.test.ts
#RI-3898 - Do not use JSON.DEBUG MEMORY when it is not allowed
=> #RI-3898 - Do not use JSON.DEBUG MEMORY when it is not allowed

redisinsight/api/src/modules/database/database.service.ts, redisinsight/api/src/modules/database/providers/database.factory.ts, redisinsight/api/test/api/database/PUT-databases-id.test.ts
#RI-3940 - When we edit db name, we are getting "new indicator"
=> #RI-3940 - When we edit db name, we are getting "new indicator"

redisinsight/ui/src/components/instance-header/InstanceHeader.tsx, redisinsight/ui/src/pages/browser/BrowserPage.tsx, redisinsight/ui/src/pages/browser/components/browser-left-panel/BrowserLeftPanel.tsx
#RI-3986 - fix refresh keys after change index
#RI-3985 - remove selected key after changing index
=> #RI-3986, #RI-3985

redisinsight/ui/src/pages/workbench/WorkbenchPage.spec.tsx, redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx, redisinsight/ui/src/utils/monaco/monacoUtils.ts, redisinsight/ui/src/utils/tests/monaco/monacoUtils.spec.ts, redisinsight/ui/src/utils/tests/workbench.spec.ts, redisinsight/ui/src/utils/workbench.ts
* #RI-4011 - WORKBENCH_COMMAND_SUBMITTED event has incorrect "command" parameter value if command contains number of runs
* #RI-4013 - Parameters are not applied if there is any text on the same row
* #RI-4010 - WORKBENCH_COMMAND_RUN_AGAIN event should have the same parameters as WORKBENCH_COMMAND_SUBMITTED
=> #RI-4011, #RI-4010, #RI-4013

redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.spec.tsx, redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx
Reverts RedisInsight/RedisInsight#1633
=> Revert "#RI-4021 - Update telemetry WORKBENCH_COMMAND_COPY event"

redisinsight/ui/src/packages/ri-explain/src/Explain.tsx, redisinsight/ui/src/packages/ri-explain/src/parser.ts, redisinsight/ui/src/packages/ri-explain/src/styles/styles.less
- Properly parse tags exprs - [RI-4162]
- Fix profile info width - [RI-4159]
- Don't render execution info for redisgraph
=> RI-4162, RI-5159, RI-4101, Profile/Explain plugin bug fixes

jest.config.js, package.json, redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.spec.tsx, redisinsight/ui/src/constants/browser.ts, redisinsight/ui/src/constants/keys.ts, redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/set-details/SetDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/set-details/SetDetails.tsx, redisinsight/ui/src/pages/browser/components/stream-details/StreamDetailsWrapper.spec.tsx, redisinsight/ui/src/pages/browser/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx, redisinsight/ui/src/pages/browser/components/string-details/StringDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx, redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/zset-details/ZSetDetails.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/interfaces/keys.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts, redisinsight/ui/src/utils/decompressors/decompressors.ts, redisinsight/ui/src/utils/decompressors/index.ts, redisinsight/ui/src/utils/formatters/bufferFormatters.ts, redisinsight/ui/src/utils/tests/decompressors/decompressors.spec.ts, yarn.lock
#RI-4142 - Decompressed GZIP data
=> #RI-4142 - Decompressed GZIP data

redisinsight/ui/src/packages/ri-explain/src/parser.ts
=> Profile/Explain plugin - Add support for Parsing GEO tags in RediSearch

redisinsight/ui/src/packages/redisearch/package.json
This lets Profile Plugin the default view for `FT.PROFILE` since RediSearch Plugin's `FT.PROFILE` is non-default
=> [RI-4194] Profile Plugin - Show profile tab by default

redisinsight/api/test/api/database/GET-databases-id-info.test.ts, tests/e2e/rte.docker-compose.yml, tests/e2e/rte/oss-cluster-7-rs/Dockerfile, tests/e2e/rte/oss-cluster-7-rs/cluster-create.sh, tests/e2e/rte/oss-cluster-7-rs/creator.Dockerfile, tests/e2e/rte/oss-cluster-7-rs/redis.conf
In addittion ignore /databases/:id/info ITest for big data since it might not always work due to data sync delays
=> #RI-4188 add redisearch 2.6.5 for redis 7.0.6 oss cluster

redisinsight/ui/src/packages/ri-explain/src/Explain.tsx, redisinsight/ui/src/packages/ri-explain/src/Node.tsx, redisinsight/ui/src/packages/ri-explain/src/constants.ts
- Add port support which distinguishes when the node has multiple outputs.
- Add arrow for targets
=> [RI-4101] Profile/Explain Plugin - Add edge split port when multiple targets, add arrow for target ends

redisinsight/ui/src/components/query-card/QueryCardHeader/QueryCardHeader.tsx, redisinsight/ui/src/packages/ri-explain/package.json, redisinsight/ui/src/packages/ri-explain/src/App.tsx, redisinsight/ui/src/packages/ri-explain/src/Explain.tsx, redisinsight/ui/src/packages/ri-explain/src/Node.tsx, redisinsight/ui/src/packages/ri-explain/src/parser.ts, redisinsight/ui/src/packages/ri-explain/src/styles/styles.less, redisinsight/ui/src/packages/ri-explain/yarn.lock, scripts/build-statics.sh
- Remove edge target marker
- Add support for LEXRANGE, IDS, NOT, OPTION, EXACT, FUZZY, WILDCARD, and PREFIX expressions (All of the expressions' parsing is based on RediSearch's latest source code) - https://github.com/RediSearch/RediSearch/blob/master/src/query.c
- Parse Vector Expressions
- Parse tag identifiers with numbers
- Properly skip backslash if exsits (multiple backslash appears)
- Parse identifiers with pipe character
- Make TAG expressions be parsed via expand expression parser since it might contain children
- Remove support for FT.PROFILE on cluster
- Add max-cap zoom
=> [RI-3726] Profile Plugin - Add support for leftoff RediSearch expressions

redisinsight/ui/src/pages/browser/components/hash-details/HashDetails.tsx, redisinsight/ui/src/pages/browser/components/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/components/list-details/ListDetails.tsx, redisinsight/ui/src/pages/browser/components/string-details/StringDetails.spec.tsx, redisinsight/ui/src/pages/browser/components/string-details/StringDetails.tsx, redisinsight/ui/src/slices/browser/string.ts, redisinsight/ui/src/slices/interfaces/string.ts, redisinsight/ui/src/slices/tests/browser/string.spec.ts, redisinsight/ui/src/utils/decompressors/decompressors.ts, redisinsight/ui/src/utils/tests/decompressors/decompressors.spec.ts
#RI-4274 - Can not edit key even it is not compressed
=> #RI-4274 - Can not edit key even it is not compressed

redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.spec.tsx, redisinsight/ui/src/components/live-time-recommendations/LiveTimeRecommendations.tsx, redisinsight/ui/src/components/live-time-recommendations/components/recommendation/Recommendation.spec.tsx, redisinsight/ui/src/components/live-time-recommendations/components/recommendation/styles.module.scss, redisinsight/ui/src/slices/recommendations/recommendations.ts, redisinsight/ui/src/slices/tests/recommendations/recommendations.spec.ts
* #RI-4386 - [FE] Button has incorrect name
* #RI-4388 - [FE] Parameters are not displayed in the INSIGHTS_RECOMMENDATIONS_OPENED event
=> #RI-4386, #RI-4388

redisinsight/ui/src/packages/clients-list/src/App.tsx, redisinsight/ui/src/packages/clients-list/src/main.tsx, redisinsight/ui/src/styles/components/_json_view.scss
* #RI-4396 - [FE] Long text doesn't wrap
* #RI-4397 - [FE] JSON isn't parsed in the Raw mode
* #RI-4398 - [FE] Error isn't handled if user tries to get not existing key
=> #RI-4396, #RI-4397, #RI-4398

redisinsight/ui/src/components/notifications/styles.module.scss, redisinsight/ui/src/components/notifications/success-messages.tsx, redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/RedisUploadButton/RedisUploadButton.tsx, redisinsight/ui/src/pages/workbench/components/enablement-area/EnablementArea/components/RedisUploadButton/styles.module.scss, redisinsight/ui/src/styles/themes/dark_theme/_dark_theme.lazy.scss, redisinsight/ui/src/styles/themes/light_theme/_light_theme.lazy.scss
#RI-4464 - fix light theme styling
=> #RI-4465 - fix multiple tooltips

.circleci/config.yml, .circleci/virustotal-report.js, package.json
#RI-4462 - [CircleCI] Add Virus check to release branch builds
=> #RI-4462 - [CircleCI] Add Virus check to release branch builds

redisinsight/ui/src/pages/browser/components/browser-right-panel/BrowserRightPanel.tsx, redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndex.tsx, redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndexWrapper.tsx, redisinsight/ui/src/pages/browser/components/create-redisearch-index/styles.module.scss, redisinsight/ui/src/pages/browser/components/filter-key-type/styles.module.scss, redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.spec.tsx, redisinsight/ui/src/pages/browser/components/redisearch-key-list/RediSearchIndexesList.tsx, redisinsight/ui/src/pages/browser/components/redisearch-key-list/styles.module.scss, redisinsight/ui/src/pages/workbench/components/module-not-loaded/ModuleNotLoaded.tsx
#RI-4597 - fix grid for search panel
#RI-4598 - back button for create index
#RI-4610 - fix search mode settings
* fix tests
=> fix #RI-4597, #RI-4598, #RI-4610

redisinsight/ui/src/components/oauth-select-account-dialog/OAuthSelectAccountDialog.spec.tsx, redisinsight/ui/src/components/oauth-select-account-dialog/OAuthSelectAccountDialog.tsx, redisinsight/ui/src/components/oauth-social/OAuthSocial.tsx, redisinsight/ui/src/electron/utils/ipcAuth.ts
* #RI-4754 - Source parameter “auto-discovery” not added to sso telemetry events
* #RI-4754 - [FE] Active account is not preselected by default
* #RI-4748 - [FE] Waiting message displayed endlessly with error when connecting to account with no write access
* #RI-4751 - [FE] Waiting message not displayed after selecting account
=> #RI-4754, #RI-4748, #RI-4751, #RI-4753

redisinsight/ui/src/components/oauth-sign-in-dialog/OAuthSignInDialog.spec.tsx, redisinsight/ui/src/components/oauth-sign-in-dialog/OAuthSignInDialog.tsx, redisinsight/ui/src/components/oauth-social/OAuthSocial.spec.tsx, redisinsight/ui/src/components/oauth-social/OAuthSocial.tsx
#RI-4754 - Source parameter “auto-discovery” not added to sso telemetry events
=> #RI-4754 - Source parameter “auto-discovery” not added to sso telemetry

package.json, redisinsight/api/package.json, redisinsight/api/src/common/models/client-metadata.ts, redisinsight/api/src/modules/browser/dto/browser-history/create.browser-history.dto.ts, redisinsight/api/src/modules/browser/dto/browser-history/get.browser-history.dto.ts, redisinsight/api/src/modules/browser/dto/redisearch.ts, redisinsight/api/src/modules/bulk-actions/dto/create-bulk-action.dto.ts, redisinsight/api/src/modules/bulk-actions/models/bulk-action-filter.ts, redisinsight/api/src/modules/cloud/autodiscovery/dto/add-cloud-database.dto.ts, redisinsight/api/src/modules/cloud/autodiscovery/dto/get-cloud-subscription-database.dto.ts, redisinsight/api/src/modules/cloud/autodiscovery/dto/get-cloud-subscription-databases.dto.ts, redisinsight/api/src/modules/cloud/autodiscovery/models/cloud-database-details.ts, redisinsight/api/src/modules/custom-tutorial/models/custom-tutorial.manifest.ts, redisinsight/api/src/modules/database-analysis/models/scan-filter.ts, redisinsight/api/src/modules/database-recommendation/dto/modify.database-recommendation.dto.ts, redisinsight/api/src/modules/database/dto/update.database.dto.ts, redisinsight/api/src/modules/database/models/database.ts, redisinsight/api/src/modules/pub-sub/dto/subscription.dto.ts, redisinsight/api/test/helpers/test.ts, redisinsight/api/yarn.lock, redisinsight/ui/src/packages/redistimeseries-app/package.json, redisinsight/ui/src/packages/redistimeseries-app/yarn.lock, redisinsight/yarn.lock, tests/e2e/package.json, tests/e2e/yarn.lock, yarn.lock
Fixes
- minimist
- class-validator
- socket.io-parser
- http-cache-semantics
- minimatch
- axios
- word-wrap
- engine.io
- nanoid
=> Dependabot fixes

redisinsight/ui/src/components/oauth/oauth-select-plan/OAuthSelectPlan.tsx
#RI-4857 - [FE] Triggers and functions region not preselected by default
=> #RI-4857 - [FE] Triggers and functions region not preselected by default

redisinsight/ui/src/packages/redistimeseries-app/src/components/Chart/ChartConfigForm.tsx, redisinsight/ui/src/packages/redistimeseries-app/src/styles/styles.less
Use the new custom select to render chart point modes, cause the enum select component that comes with Eui messes up with the chart dimensions, which causes the chart legends to compact.
=> RI-4792: Fix redistimeseries graphic legend overlapping

redisinsight/ui/src/packages/clients-list/src/components/json-view/components/json-array/JsonArray.tsx
#RI-4868 - String in json format isn't displayed in Workbanch
=> #RI-4868 - String in json format isn't displayed in Workbanch

redisinsight/ui/src/components/oauth/oauth-select-plan/OAuthSelectPlan.tsx, redisinsight/ui/src/components/oauth/oauth-select-plan/styles.module.scss, redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/WBResults.tsx, redisinsight/ui/src/pages/workbench/components/wb-results/WBResults/styles.module.scss, tests/e2e/tests/regression/insights/feature-flag.e2e.ts
#RI-4885 - add tooltip for TF icon
#RI-4887 - fix scrolling behavior for WB history
=> fix RI-4885, RI-4887

redisinsight/ui/src/utils/formatters/valueFormatters.tsx
Fixes https://github.com/RedisInsight/RedisInsight/issues/1646
Sample data:
```
O:8:"stdClass":3:{s:3:"one";s:1:"1";s:3:"two";s:3:"...";s:5:"three";i:3;} 
```
Before:
After:
=> RI-4852: Do non strict php unserialization

package.json, redisinsight/ui/src/utils/formatters/valueFormatters.tsx, redisinsight/ui/src/utils/tests/formatters/valueFormatters.spec.ts, yarn.lock
Fixes https://github.com/RedisInsight/RedisInsight/issues/2391
Test data:
```
echo '98A44E6F6E6581A15499CD07E7CCE9090408CE26DFE89700000081A15499CD07E7CCE9090409CE05B137F3000000B26C73612F7069755F61737369676E5F7266738192AD637573746F6D65725F6E616D65C081AA556E7265736F6C766564A87B2E2F6E616D657D8081A573746570739080' | xxd -r -p | redis-cli -x SET msg-pack-complex-2
```
Before:
After:
=> RI-4852 - Use msgpackr alternative library to encode/decode msgpack contents

redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.spec.tsx, redisinsight/ui/src/pages/slowLog/components/EmptySlowLog/EmptySlowLog.tsx
#RI-4960 - ms not changed to msec in No Slow Logs message
=> #RI-4960 - ms not changed to msec in No Slow Logs message

redisinsight/ui/src/components/oauth/oauth-select-plan/OAuthSelectPlan.tsx, redisinsight/ui/src/components/oauth/oauth-select-plan/styles.module.scss, redisinsight/ui/src/components/oauth/oauth-sso-handler-dialog/OAuthSsoHandlerDialog.tsx, redisinsight/ui/src/pages/home/components/HomeHeader/HomeHeader.tsx
#RI-4939 - [Regression][FE] CREATE_FREE_CLOUD_DATABASE_CLICKED event is sent when SSO feature available
#RI-4934 - Add more information to the provider selection step
=> #RI-4939, #RI-4934

redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx, redisinsight/ui/src/components/notifications/styles.module.scss, redisinsight/ui/src/slices/instances/instances.ts, redisinsight/ui/src/telemetry/checkAnalytics.ts, redisinsight/ui/src/telemetry/telemetryUtils.ts
* #RI-4983 - [Regression] Events are sent if Analytics is turned off
* #RI-4991 - [Regression] Navigate to the page from url if user connects to existing db
* #RI-4993 - [Regression] Cancel button is not visible with white theme
=> #RI-4983, #RI-4991, #RI-4993

redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/pages/browser/components/no-keys-found/styles.module.scss, redisinsight/ui/src/pages/browser/components/virtual-tree/VirtualTree.tsx, redisinsight/ui/src/pages/browser/components/virtual-tree/components/Node/Node.tsx, redisinsight/ui/src/pages/browser/components/virtual-tree/components/Node/styles.module.scss, redisinsight/ui/src/pages/browser/components/virtual-tree/interfaces.ts, yarn.lock
* #RI-5095 - [FE] Scrollbar is displayed for "No keys" panel in tree view when clicked
* #RI-5096 - [FE] Delete popup moved at the top left corner when hovering on the key below in list and delete popup opened
* #RI-5097 - [FE] Multiple tooltips can be displayed at the same time when hovering over different namespaces after scrolling
* #RI-5098 - [FE] Key details are opened for the key in tree view automatically when it wasn't opened in list view
* #RI-5100 - [FE] Namespaces folders collapsed after refresh
=> #RI-5095, #RI-5096, #RI-5097, #RI-5098, #RI-5100

redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/StringDetails.spec.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/StringDetails.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/string-details-table/StringDetailsTable.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/string-details-table/styles.module.scss
#RI-5207 - fix string details heights
=> #RI-5206 - fix button state for editing

redisinsight/ui/src/components/database-side-panels/DatabaseSidePanels.test.tsx, redisinsight/ui/src/components/database-side-panels/DatabaseSidePanels.tsx, redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/EnablementArea.spec.tsx, redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/EnablementArea.tsx, redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/InternalPage/InternalPage.spec.tsx, redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/InternalPage/InternalPage.tsx, redisinsight/ui/src/components/database-side-panels/panels/enablement-area/EnablementArea/components/LazyInternalPage/LazyInternalPage.tsx, redisinsight/ui/src/components/oauth/oauth-connect-free-db/OAuthConnectFreeDb.spec.tsx, redisinsight/ui/src/components/oauth/oauth-connect-free-db/OAuthConnectFreeDb.tsx, redisinsight/ui/src/services/capability.ts, redisinsight/ui/src/services/index.ts, redisinsight/ui/src/slices/app/context.ts, redisinsight/ui/src/slices/interfaces/app.ts, redisinsight/ui/src/slices/tests/app/context.spec.ts, redisinsight/ui/src/utils/capability.ts, redisinsight/ui/src/utils/tests/capability.spec.ts
* #RI-5302 - Pop-over is still displayed if user opens cloud db after user has already launched it
* #RI-5304 - The list of tutorial is not displayed if user does not have a relevant tutorial
* #RI-5306 - Telemetry event is duplicated
* #RI-5307 - Telemetry event is sent if db in not free and popover is not displayed
* #RI-5308 - CAPABILITY_POPOVER_DISPLAYED is sent when 'Compatibility are not available' popover appears
=> #RI-5302, #RI-5304, #RI-5306, #RI-5307, #RI-5308

redisinsight/ui/src/components/database-side-panels/DatabaseSidePanels.test.tsx, redisinsight/ui/src/components/database-side-panels/DatabaseSidePanels.tsx, redisinsight/ui/src/services/capability.ts
#RI-5311 - Popover appears after Triggers and Functions
=> #RI-5311 - Popover appears after Triggers and Functions

configs/webpack.config.web.dev.ts, package.json, redisinsight/api/yarn.lock, redisinsight/ui/src/packages/clients-list/yarn.lock, redisinsight/ui/src/packages/redisearch/yarn.lock, redisinsight/ui/src/packages/redisgraph/yarn.lock, redisinsight/ui/src/packages/redistimeseries-app/yarn.lock, redisinsight/ui/src/packages/ri-explain/yarn.lock, redisinsight/yarn.lock, tests/e2e/yarn.lock, yarn.lock
This should fix 12 alerts.
- Bumps specific packages to remove the 'ip' package
- Also, remove the 'ip' package and use a custom function to get the local IP address
- Bumps the 'msgpackr' library
- Bumps Axios package
=> Dependabot fixes - 2024-02 

redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.spec.tsx, redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.tsx
#RI-5497 - Insights_panel_opened/closed not sent when clicking on "Explore Redis" button
=> #RI-5497 - Insights_panel_opened/closed not sent 

redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.spec.tsx, redisinsight/ui/src/pages/home/components/capability-promotion/CapabilityPromotion.tsx
#RI-5572 - Explore Redis button opens not only Explore tab
=> #RI-5572 - Explore Redis button opens not only Explore tab

redisinsight/ui/src/components/json-viewer/JSONViewer.tsx, redisinsight/ui/src/utils/formatters/valueFormatters.tsx
Allow non-native big integers in JSONBigInt to convert large decimals. This can be the case for some language models that use large decimals in data. JSONBigInt will fall back to non-native big integers if they can't be packed in the native ones, so we still have support for the old ones. The support is explicitly added to Vector 32-bit and Vector 64-bit data.
When viewing some vector data that uses large numbers, which are often decimals, we try to pack them into javascript's native big int. Javascript's native big int doesn't support Big decimals yet. - https://github.com/sidorares/json-bigint/issues/88
We have two options:
1. Add support for non-native big integers when native big integers are not supported
2. Raise an exception and show the data in UTF8
This PR chooses 1. Please check …
=> [RI-5545] [RI-5543] Add support for non-native big integers and allow non-native big integers for Vector formatting

redisinsight/api/config/default.ts, redisinsight/api/src/main.ts
The usage is for URLs which always need a `/`. So we can directly use the `posix.join` method to have a cross-platform implementation that works fine on Windows, too.
=> Use posix join for combining paths

.circleci/config.yml, redisinsight/ui/src/styles/base/_base.scss, redisinsight/ui/src/styles/components/_popover.scss, redisinsight/ui/src/styles/mixins/_eui.scss, redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss, redisinsight/ui/src/styles/themes/dark_theme/darkTheme.scss, redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss, redisinsight/ui/src/styles/themes/light_theme/lightTheme.scss
* #RI-5667 - No scrollbar when editing long value
* revert resource to Intel for circleci macos job
=> #RI-5667 - No scrollbar when editing long value

redisinsight/ui/src/pages/browser/modules/key-details-header/KeyDetailsHeader.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/RejsonDetailsWrapper.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/components/edit-entire-item-action/EditEntireItemAction.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/interfaces.ts, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-details/RejsonDetails.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-object/RejsonObject.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/rejson-scalar/RejsonScalar.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/styles.module.scss, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/rejson.ts
#RI-5574 - fix opening object values
fix work with big length json
=> #RI-5568 - fix editing null value

.circleci/config.yml
This changes pushes the image to v1 repo - `redislabs/redisinsight`
- Creds are populated in CircleCI project environment variables.
=> Push to v1 docker repo

redisinsight/ui/src/components/global-subscriptions/CommonAppSubscription/CommonAppSubscription.spec.tsx, redisinsight/ui/src/components/global-subscriptions/CommonAppSubscription/CommonAppSubscription.tsx, redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx, redisinsight/ui/src/components/notifications/components/infinite-messages/styles.module.scss, redisinsight/ui/src/components/oauth/oauth-sso/oauth-create-db/OAuthCreateDb.spec.tsx, redisinsight/ui/src/components/oauth/oauth-sso/oauth-create-db/OAuthCreateDb.tsx, redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/texts.tsx
* #RI-5793  - [Regression] Create database popup for authorized account doesn't close after creating db
* #RI-5794 - [Regression] There is no spinner for info dialogs during sso login
* #RI-5798 - [Regression] 401 error from WS is not handled
* #RI-5799 - [Regression] Incorrect text for database chatbot
=> #RI-5793,  #RI-5794, #RI-5798, #RI-5799

redisinsight/api/config/default.ts, redisinsight/api/migration/1718260230164-ai-history.ts, redisinsight/api/migration/index.ts, redisinsight/api/src/__mocks__/ai.ts, redisinsight/api/src/__mocks__/cloud-session.ts, redisinsight/api/src/__mocks__/cloud-user.ts, redisinsight/api/src/modules/ai/query/ai-query.service.spec.ts, redisinsight/api/src/modules/ai/query/ai-query.service.ts, redisinsight/api/src/modules/ai/query/entities/ai-query.message.entity.ts, redisinsight/api/src/modules/ai/query/exceptions/a-queryi.error.handler.spec.ts, redisinsight/api/src/modules/ai/query/exceptions/ai-query.error.handler.ts, redisinsight/api/src/modules/ai/query/models/ai-query.common.ts, redisinsight/api/src/modules/ai/query/models/ai-query.message.ts, redisinsight/api/src/modules/ai/query/providers/ai-query.provider.spec.ts, redisinsight/api/src/modules/ai/query/providers/ai-query.provider.ts, redisinsight/api/src/modules/ai/query/providers/auth/local.ai-query-auth.provider.spec.ts, redisinsight/api/src/modules/ai/query/repositories/in-memory.ai-query.context.repository.spec.ts, redisinsight/api/src/modules/ai/query/repositories/local.ai-query.message.repository.spec.ts, redisinsight/api/src/modules/ai/query/utils/context.util.spec.ts, redisinsight/api/src/modules/ai/query/utils/context.util.ts
#RI-5802 - limiter for RUN_QUERY + rollback query fix #RI-5828 - converation id
=> #RI-5723 - cover with tests

redisinsight/api/src/modules/redis/connection/ioredis.redis.connection.strategy.ts
https://github.com/RedisInsight/RedisInsight/issues/3429
The excessively short default slots refresh timeout, connect error occur when responses are delayed. 
Therefore, the timeout has been extended to 5s to ensure that such delays do not result in connection abnormalities.
=> Extend slots refresh timeout to 5s 

redisinsight/api/src/middleware/subpath-proxy.middleware.ts
Fix #3295
The current subpath proxy implementation handles only HTML files. I added a check that also checks for JS files.
=>  Handle JS files in the subpath proxy

redisinsight/api/src/modules/profiler/models/profiler.client.ts
Strip of '[' and the trailing data if there's any in the MONITOR timestamp.
A timestamp is coming with '[' on Alibaba Redis's monitor - #2915.
=> RI-5336: Fix profiler timestamp if its invalid

redisinsight/api/src/app.module.ts, redisinsight/api/src/middleware/x-frame-options.middleware.ts, redisinsight/api/src/modules/statics-management/statics-management.module.ts
Fixes https://github.com/RedisInsight/RedisInsight/issues/3087
=> Set X-Frame-Options header to routes

redisinsight/ui/src/utils/formatters/utils.ts, redisinsight/ui/src/utils/formatters/valueFormatters.tsx, redisinsight/ui/src/utils/tests/validations.spec.ts, redisinsight/ui/src/utils/validations.ts
Bugfix for RI-5965
Fixed convert negative timestamp
Added convert to seconds (microseconds, nanoseconds) to DateTime
=> RI-5970 fix convert negative timestamp, timestamp in seconds

redisinsight/ui/src/constants/keys.ts, redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-formatter/constants.ts, redisinsight/ui/src/utils/formatters/utils.ts, redisinsight/ui/src/utils/formatters/valueFormatters.tsx, redisinsight/ui/src/utils/tests/formatters/valueFormatters.spec.ts, redisinsight/ui/src/utils/tests/validations.spec.ts, redisinsight/ui/src/utils/validations.ts, tests/e2e/test-data/formatters-data.ts, tests/e2e/test-data/formatters/DataTime.ts, tests/e2e/tests/web/critical-path/browser/formatters.e2e.ts
RI-5965 (only timestamp (the number of milliseconds since January 1, 1970, UTC) should be transformed)
=> RI-5965 Added a new timestamp formatter

redisinsight/api/src/__mocks__/databases.ts, redisinsight/api/src/modules/bulk-actions/bulk-actions.module.ts, redisinsight/api/src/modules/cloud/job/cloud-job.factory.ts, redisinsight/api/src/modules/cloud/job/cloud-job.module.ts, redisinsight/api/src/modules/cloud/job/jobs/create-free-database.cloud-job.ts, redisinsight/api/src/modules/cloud/job/jobs/create-free-subscription-and-database.cloud-job.ts, redisinsight/api/src/modules/database/database-info.service.spec.ts, redisinsight/api/src/modules/database/database-info.service.ts, redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts, redisinsight/api/src/modules/database/providers/database-info.provider.ts, redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx, redisinsight/ui/src/components/oauth/oauth-jobs/OAuthJobs.tsx, redisinsight/ui/src/slices/oauth/cloud.ts, redisinsight/ui/src/slices/tests/oauth/cloud.spec.ts
=> RI-5955 auto-load data for empty free cloud database

redisinsight/api/src/modules/pub-sub/pub-sub.analytics.service.spec.ts, redisinsight/api/src/modules/pub-sub/pub-sub.analytics.service.ts, redisinsight/api/src/modules/pub-sub/pub-sub.service.ts, redisinsight/ui/src/pages/pub-sub/PubSubPage.tsx, redisinsight/ui/src/pages/pub-sub/components/subscription-panel/SubscriptionPanel.spec.tsx, redisinsight/ui/src/pages/pub-sub/components/subscription-panel/SubscriptionPanel.tsx, redisinsight/ui/src/pages/pub-sub/components/subscription-panel/styles.module.scss, redisinsight/ui/src/slices/pubsub/pubsub.ts, redisinsight/ui/src/slices/tests/pubsub/pubsub.spec.ts, tests/e2e/pageObjects/pub-sub-page.ts, tests/e2e/tests/web/regression/pub-sub/pub-sub-oss-cluster-7.ts
#RI-6097 - Subscribe to a specific pub/sub channel
=> #RI-6097 - Subscribe to a specific pub/sub channel

redisinsight/ui/src/pages/search/utils/query.ts, redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx, redisinsight/ui/src/pages/workbench/data/supported_commands.json, redisinsight/ui/src/pages/workbench/utils/query.ts, redisinsight/ui/src/pages/workbench/utils/searchSuggestions.ts, redisinsight/ui/src/pages/workbench/utils/tests/query.spec.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/common.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/ft-aggregate.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/ft-search.ts, redisinsight/ui/src/utils/monaco/monacoUtils.ts, redisinsight/ui/src/utils/tests/monaco/monacoUtils.spec.ts
#RI-6218 - fix cypher editor
* small refactoring
=> #RI-6217 - fix suggestions

redisinsight/ui/src/components/database-overview/components/OverviewMetrics/OverviewMetrics.tsx, redisinsight/ui/src/utils/tests/transformers/formatBytes.spec.ts, redisinsight/ui/src/utils/transformers/formatBytes.ts
Fix #3779 
Shows the following formats:
```
['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB']
```
=> Dynamically show multiple byte formats

redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx, redisinsight/ui/src/pages/workbench/types.ts, redisinsight/ui/src/pages/workbench/utils/monaco.ts, redisinsight/ui/src/pages/workbench/utils/query.ts, redisinsight/ui/src/pages/workbench/utils/searchSuggestions.ts, redisinsight/ui/src/pages/workbench/utils/suggestions.ts, redisinsight/ui/src/pages/workbench/utils/tests/monaco.spec.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/common.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/ft-aggregate.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/ft-search.ts, redisinsight/ui/src/utils/monaco/monacoRedisMonarchTokensProvider.ts, redisinsight/ui/src/utils/monaco/monarchTokens/redisearchTokensSubRedis.ts
#RI-6211 - fix highlighting when there are several the same args
=> #RI-6208 - improve switch between redis and search syntax, add command scope

redisinsight/ui/src/pages/workbench/constants.ts, redisinsight/ui/src/pages/workbench/utils/searchSuggestions.ts, redisinsight/ui/src/pages/workbench/utils/suggestions.ts, redisinsight/ui/src/pages/workbench/utils/tests/test-cases/ft-search.ts, redisinsight/ui/src/utils/monaco/monacoUtils.ts
#RI-6244 - fix finding of command
=> #RI-6226 - add sorting for list of commands

redisinsight/ui/src/contexts/themeContext.tsx, redisinsight/ui/src/electron/utils/index.ts, redisinsight/ui/src/electron/utils/ipcThemeChange.ts, redisinsight/ui/src/services/storage.ts, redisinsight/ui/src/services/theme.ts
#RIVS-6156 - Change theme key of local storage
=> #RIVS-6156 - Change theme key of local storage

redisinsight/api/config/default.ts, redisinsight/api/src/modules/encryption/strategies/keytar-encryption.strategy.ts
#RI-6146 - POC migrate BE from keytar to electron.safeStorage
=> #RI-6146 - POC migrate BE from keytar to electron.safeStorage

redisinsight/api/test/test-runs/oss-st-6-tls-auth-ssh/docker-compose.yml, tests/e2e/rte.docker-compose.yml
#RI-6370 - SSH doesn't work for desktop app tests and web
=> #RI-6370 - SSH doesn't work for desktop app tests and web

redisinsight/ui/src/config/default.ts, redisinsight/ui/src/pages/instance/InstancePage.tsx
default 60 seconds
In case that WS connection does not work in cloud
=> CR-189 add configuration to trigger recommendation fetch on set interval

redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/utils/utils.spec.ts, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/utils/utils.ts, redisinsight/ui/src/slices/browser/rejson.ts
Updated branch name as per suggestion from the original one https://github.com/RedisInsight/RedisInsight/pull/4192
=> RI-6442 - String value is parsed as a number in JSON

redisinsight/ui/src/pages/home/components/connection-url/ConnectionUrl.spec.tsx, redisinsight/ui/src/pages/home/components/connection-url/ConnectionUrl.tsx, redisinsight/ui/src/pages/home/components/connection-url/components/connectivity-options/ConnectivityOptions.tsx, redisinsight/ui/src/pages/home/components/connection-url/components/connectivity-options/styles.module.scss
#RI-6443 - Change button colors and add a default value
=> #RI-6443 - Change button colors and add a default value

redisinsight/api/config/default.ts, redisinsight/ui/src/App.tsx, redisinsight/ui/src/components/bulk-actions-config/BulkActionsConfig.tsx, redisinsight/ui/src/components/global-subscriptions/CommonAppSubscription/CommonAppSubscription.tsx, redisinsight/ui/src/components/global-subscriptions/GlobalSubscriptions.tsx, redisinsight/ui/src/components/monitor-config/MonitorConfig.tsx, redisinsight/ui/src/components/pub-sub-config/PubSubConfig.tsx, redisinsight/ui/src/services/hooks/useIoConnection.ts, redisinsight/ui/src/services/wsService.ts, redisinsight/ui/src/utils/common.ts
With this PR, the interface of establishing socket connection is being unified in one place, in order to make it much simpler to use.
`getSocketApiUrl` - required because of how routing on cluster works
`useIoConnection` - extract common logic, that would of been needed in every component that establishes io connection
`wsService` - Connection it-self is established in wsService (WebSocket Service), and because there is some condititional logic for where to put CSRF token, it is also being called via custom hook.
=> CR-132: web socket connection

redisinsight/ui/src/utils/common.ts
fix: get base url from api url origin instead of replacing path.
Whenever there is no path - `http://localhost` - then path becomes `/` and is being replaced in http:// part and breaks the url like `http:/localhost`
=> bugfix web sockets

redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/string-details-value/StringDetailsValue.spec.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/string-details/string-details-value/StringDetailsValue.tsx, redisinsight/ui/src/utils/formatters/bufferFormatters.ts
#RI-6522 - [Regression] Long vector string is not displayed
=> #RI-6522 - [Regression] Long vector string is not displayed

.circleci/build/build.Dockerfile, .github/build/build.Dockerfile, .github/workflows/tests-integration.yml, redisinsight/api/test/test-runs/docker.build.env, redisinsight/api/test/test-runs/docker.build.yml
- Switch to the `redisinsight` image instead of `riv2`, as this is the one built in the [pipeline-build-docker.yml](https://github.com/RedisInsight/RedisInsight/blob/main/.github/workflows/pipeline-build-docker.yml#L82).  
- Mount the `/data` directory to containers since it’s where `redisinsight` stores all the required files.  
- Update the backend URL to disable SSL support: Again, the goal is to get everything running first, and then address this.  
- Tests are currently failing because they need updates. For example, in [this run](https://github.com/RedisInsight/RedisInsight/actions/runs/12551271839), the test suite with passing tests generates all required files, which is why it succeeds. The failing tests don’t produce a `test-run-coverage.json` file, leading to their failure. …
=> RI-5362 Fix nightly tests running

redisinsight/ui/src/utils/formatters/valueFormatters.tsx
#RI-6532 - Empty value is displayed as an array
=> #RI-6532 - Empty value is displayed as an array

.github/workflows/tests.yml
We currently expect the development of the fe and be parts of any task to be done separately. There are some tasks for which this doesn't make sense and will only prolong the development cycle and require some hacks from the developer to do it.
I am proposing we extend the current test functionality to support these cases while also working for the previous ones.
=> Unit and Integration tests proposal for change in the workflow

redisinsight/api/src/modules/rdi/rdi.service.spec.ts, redisinsight/api/src/modules/rdi/rdi.service.ts, redisinsight/ui/src/pages/rdi/pipeline-management/pages/config/Config.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/Job.tsx, redisinsight/ui/src/pages/rdi/statistics/status/Status.tsx
This task has 3 sub-tasks:
- First is to hide the RDI version on the `Status page` as it's incorrect.
- The second one is to display the proper version of RDI on the connections screen.
- And the third to update few texts related to the task.
=> RI-6457: Display proper RDI version

redisinsight/ui/src/packages/redisearch/src/components/TableResult/TableResult.tsx, redisinsight/ui/src/packages/redisearch/src/styles/styles.scss, redisinsight/ui/src/styles/mixins/_eui.scss
RI-6547 Apply multiline ellipsis to the table tooltip text that overflows, instead of the scroll.
The scroll was the auto behavior when the tooltip text was too long and it lead to the tooltip container height to exceed the one on the table result plugin container. So when attempted to scroll and view the whole text, it was impossible because when focus was lost, the tooltip disappears. 
Implemented the multiline ellipsis solution where maximum 7 lines of text are shown in the tooltip and if longer, ends with "...". If the users wants to view the description,  they can copy it using the copy icon or switch to text view.
Before:
After:
Verified in both browser and desktop.
=> RI-6547 Apply multiline ellipsis to the table tooltip

.github/workflows/nightly-virustotal-analyze.yml
⚠️ The nighlty part would come in next PR. A.k.a.
```
on:
schedule:
- cron: 0 0 * * * # <---------------------- this
workflow_dispatch:
inputs:
....
```
this PR is to merge the `.yml` file in order to be able to test it inside GitHub. That's why it has manual trigger via `workflow_dispatch`.
We want to run nightly checks on our downloadables:
```
https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-mac-x64.dmg
https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-mac-arm64.dmg
https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-win-installer.exe
https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-linux-x86_64.AppImage
https://s3.amazonaws.com/redisinsight.download/public/latest/Redis-Insight-linux-amd6 …
```
=> RI-5395 Add Nightly Virustotal Analyze

redisinsight/api/test/README.md
Well, nothing more to describe 😸 - just what I know synthesized in a readme.
=> DEV: Add integration tests readme

.github/workflows/nightly-virustotal-analyze.yml
As described in #4305 this flow will run every night.
Additional functionality in this PR is to select either
- `single` and provide `URL` to check
- `all` which runs VirusTotal checks on all our downloadables
As a final touch, VT support basically 2 strategies of providing the files for testing:
- by URL (which was my initial idea)
- by manual upload (which is implemented here)
The change happened because VT reported issues when files were provided with URL. You can check the run [here](https://github.com/RedisInsight/RedisInsight/actions/runs/12931828504/job/36066634008).
Or how these changes run:
- `all`: https://github.com/RedisInsight/RedisInsight/actions/runs/12949211821
- `single`: https://github.com/RedisInsight/RedisInsight/actions/runs/12949748659
=> RI-5395: Run VirusTotal Analyze as crone job + support batch validation

redisinsight/api/src/modules/database-recommendation/database-recommendation.service.ts
@KIvanow Let's create task to deeper investigate why `checkMulti` method might fail in e2e tests
=> RI-6667 better handle errors for recommendations to avoid crashes

redisinsight/ui/src/slices/browser/keys.ts
This is not even the fix but some kind of workaround to reduce % of affected users.
@KIvanow we need to investigate deeper and fix more general problem when `state.user.settings.config?.scanThreshold` might be `undefined` after page refresh when fetching keys. I assume this might affect core logic and produce more regression. Hope current approach enough for now
=> RI-6661 apply "count" arg before applying DEFAULT_COUNT value for threshold

redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/stream-data-view/StreamDataViewWrapper.tsx
When stream entry's key is not valid timestamp and exceeds certain length (25 chars), it is not being displayed as date string and only as id string. If that key is long - 30+ characters, it does not look good
So with this PR, the key is truncated to one line and minimum cell height is applied, because otherwise it ruins the layout of the trash button at the end of the grid
=> RI-5337 bad display of long keys

redisinsight/ui/src/pages/home/components/form/sentinel/PrimaryGroupSentinel.tsx
Since it seems that changing primary group name during cloning is breaking the app, I have decided to disable the field until better solution is found
=> RI-6591: disable primary group name field

redisinsight/ui/src/pages/browser/BrowserPage.spec.tsx, redisinsight/ui/src/pages/browser/BrowserPage.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.spec.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts
Problem:
- Redis instance is created and keys are added to it.  One key is selected and displayed in the right panel. 
- When cli command `flushdb` is ran, it deletes all the keys.
- The opened key in the right panel does not disappear when keys are refreshed (left panel) or when navigated away from the db instance and navigating back to it. Error message is displayed "key does not exist".
Solution:
- Right panel state is cleared when refreshing the keys in the left panel and is still clear when navigating back to the db instance.
Dev testing: 
- Fixed and enhanced existing unit tests for the BrowserPage, keys.ts and create new test for KeysHeader component. 
Manual testing: browser and desktop, when having one and two DB instances. 
**See the use cases in the video provided in the …
=> RI-5883: Keys displayed after cli -> flushdb

redisinsight/api/src/modules/pub-sub/model/redis-client-subscriber.spec.ts, redisinsight/api/src/modules/pub-sub/model/redis-client-subscriber.ts, redisinsight/api/src/modules/pub-sub/model/user-session.spec.ts
`client.quit` is async function which wasn't handled properly
=> RI-6605 handle Redis.quit rejection

redisinsight/api/src/constants/agreements-spec.json, redisinsight/api/src/modules/settings/settings.service.ts
Required in https://github.com/RedisInsight/Redis-for-VS-Code/pull/255
For VSCExtension we have a custom agreements spec file, however it was not being picked up during settings save, this fixes it
=> RI-6508: fix custom agreements spec import

redisinsight/api/test/api/stream/PATCH-databases-id-streams-consumer_groups.test.ts, redisinsight/api/test/api/stream/POST-databases-id-streams-consumer_groups.test.ts
Given the upcoming release for Redis 8, we want to make sure that all Redis Insight features work fine.
However, consumer group tests need reworking due to some changes in their contracts which occurred in Redis 7, more precisely two new properties were added to the post and patch consumer group responses:
- entries_read
- lag
Changes applied:
- Separate the same tests to run when Redis < 7 and Redis >=7 with the appropriate response body expectations
Same was done for the redisearch tests -> https://github.com/RedisInsight/RedisInsight/pull/4314 
Verified on: redis:8.0-M02-alpine, redis:7.2.4 , redis: 6.2.17
=> RI-6614: Rework Consumer Group integration tests

redisinsight/api/src/modules/browser/keys/keys.service.spec.ts, redisinsight/api/src/modules/browser/keys/keys.service.ts, redisinsight/api/test/api/keys/DELETE-databases-id-keys.test.ts
When delete is called on a key that has already been deleted, the error message should be "Key with that name does not exist".
e.g. key had expired after its details have been shown, and user can still click on the delete button.
=> RI-6775: Change key not found error message on delete

redisinsight/ui/src/components/auto-refresh/AutoRefresh.spec.tsx, redisinsight/ui/src/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/components/auto-refresh/styles.module.scss, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx
When in Redisearch / index search mode and index is not selected, an error is shown to the user which is not a good UX experience. Instead, the following was applied:
* Disabled the refresh button when index is not selected in redisearch mode, which stops the refresh / data init from happening
* Add a tooltip on the disabled refresh button - "Select an index to refresh keys."
* Add some styling to the arrow next to the refresh button so it is clear that is disabled when hovered.
=> RI-6806: Disable refresh when index not selected

redisinsight/ui/src/pages/browser/modules/key-details/components/hash-details/hash-details-table/HashDetailsTable.spec.tsx, redisinsight/ui/src/utils/formatters/valueFormatters.tsx
Editing values that are  `Hex` or `Binary` encoded has to be re-reworked in order to support the value conversion and validation rules. So for now we turn the editing off.
Here its enabled:
And here is not:
=> RI-6797: Prevent editing of Hex and Binary values

redisinsight/api/src/common/decorators/transform-to-map.decorator.spec.ts, redisinsight/api/src/common/decorators/transform-to-map.decorator.ts, redisinsight/api/src/modules/rdi/client/api.rdi.client.spec.ts, redisinsight/api/src/modules/rdi/client/api.rdi.client.ts, redisinsight/api/src/modules/rdi/dto/rdi-test-connections.response.dto.ts, redisinsight/api/test/api/rdi/pipeline/POST-rdi-id-pipeline-test-connections.test.ts, redisinsight/ui/src/pages/rdi/pipeline-management/components/test-connections-log/TestConnectionsLog.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/test-connections-log/TestConnectionsLog.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/test-connections-log/styles.module.scss, redisinsight/ui/src/slices/tests/rdi/testConnections.spec.ts, redisinsight/ui/src/utils/tests/transformers/transformRdiPipeline.spec.ts, redisinsight/ui/src/utils/transformers/transformRdiPipeline.ts
As additional work to #4368, here you can test multiple sources.
Maybe going commit by commit would be easier to review.
=> RI-6382: Test multiple source connections

yarn.lock
For some reason this wasn't committed, most probably by me (as I'm the one who introduced `ajv` in the src code, the one for e2e tests is comming from eslint and it's different version).
How to test it?
1. Checkout to `main`
2. Run `yarn install`
3. If you see changes in the lock file - they should look like the changes from the PR.
=> DEV: fix yarn.lock file

redisinsight/ui/src/components/analytics-tabs/AnalyticsTabs.tsx, redisinsight/ui/src/components/hooks/useConnectionType.spec.ts, redisinsight/ui/src/components/hooks/useConnectionType.ts, redisinsight/ui/src/pages/analytics/AnalyticsPage.tsx, redisinsight/ui/src/pages/pub-sub/components/messages-list/MessagesList/MessagesList.tsx, redisinsight/ui/src/pages/pub-sub/components/messages-list/MessagesListWrapper.tsx, redisinsight/ui/src/pages/pub-sub/components/publish-message/PublishMessage.tsx, redisinsight/ui/src/pages/slow-log/components/SlowLogConfig/SlowLogConfig.tsx, redisinsight/ui/src/utils/test-utils.tsx
RI-6879
When database connection in RI is marked as `forceStandalone`, it must be treated as standalone connection (unless it is Sentinel connection)
The behavior of some components is related to this information and with this PR, I am providing correct "connectionType" wherever it is used
=> RI-6879: cluster page force standalone

redisinsight/api/src/__mocks__/bulk-actions.ts, redisinsight/api/src/modules/bulk-actions/bulk-import.service.spec.ts, redisinsight/api/src/modules/bulk-actions/bulk-import.service.ts, redisinsight/api/src/modules/bulk-actions/interfaces/bulk-action-summary-overview.interface.ts, redisinsight/api/src/modules/bulk-actions/models/bulk-action-summary.spec.ts, redisinsight/api/src/modules/bulk-actions/models/bulk-action-summary.ts, redisinsight/api/src/modules/bulk-actions/models/bulk-action.spec.ts, redisinsight/api/src/modules/bulk-actions/models/bulk-action.ts, redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.spec.ts, redisinsight/api/src/modules/bulk-actions/models/runners/simple/abstract.bulk-action.simple.runner.ts, redisinsight/ui/src/components/bulk-actions-config/BulkActionsConfig.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkActionsInfo/BulkActionsInfo.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDelete.spec.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDelete.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteSummaryButton/BulkDeleteSummaryButton.spec.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteSummaryButton/BulkDeleteSummaryButton.tsx, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/BulkDeleteSummaryButton/index.ts, redisinsight/ui/src/pages/browser/components/bulk-actions/BulkDelete/styles.module.scss
Well, people want to see what they deleted. Truncated keys won't be addressed in this PR, so when you test it, make sure you are using plain text keys (no truncating).
`bulk-delete-report-1742302606422.txt`
```
Pattern: *
Keys type: List
Keys:
sample_jobQueue:waitingList
```
=> RI-6564: Download bulk delete report

redisinsight/api/src/constants/telemetry-events.ts, redisinsight/api/src/modules/settings/constants/settings.ts, redisinsight/api/src/modules/settings/dto/settings.dto.ts, redisinsight/api/src/modules/settings/models/agreements.interface.ts, redisinsight/api/src/modules/settings/settings.analytics.spec.ts, redisinsight/api/src/modules/settings/settings.analytics.ts, redisinsight/api/src/modules/settings/settings.service.spec.ts, redisinsight/api/src/modules/settings/settings.service.ts, redisinsight/ui/src/components/consents-settings/ConsentsSettings.tsx, redisinsight/ui/src/components/oauth/shared/oauth-agreement/OAuthAgreement.tsx, redisinsight/ui/src/components/oauth/shared/oauth-form/OAuthForm.tsx, redisinsight/ui/src/slices/user/user-settings.ts
If the event is triggered by accepting consents, reason is `install`, if it is because of `sso\social-login\oauth` reasons, appropriate strategy is sent `google | github | sso`. One last place where analytics is being enabled is in OAuthAgreement.tsx, where reason is sent as `oauth-agreement`
=> RI-6864: add `reason` to `ANALYTICS_PERMISSION` event.

redisinsight/ui/src/components/markdown/CloudLink/CloudLink.tsx, redisinsight/ui/src/components/oauth/oauth-sso/oauth-create-db/styles.module.scss, redisinsight/ui/src/constants/help-texts.tsx, redisinsight/ui/src/constants/links.ts, redisinsight/ui/src/pages/browser/components/add-key/AddKey.spec.tsx, redisinsight/ui/src/slices/interfaces/cloud.ts
Changing the action of this button:
Currently, it opens a new browser tab - [https://redis.io/try-free/](https://redis.io/try-free/). This will still be the case when cloudSso is false. But when it is true we want the sso dialog to open:
Changes applied:
- Replace the "free trial redis cloud database" JSON link with the CloudLink component which still does what the link did when ssoCloud=false (open a browser tab with /try-free), and opens the SSO dialog when ssoCloud=true.
- Add UTM properties for the link
- Center the "Free trial Cloud database" title
Prerequisites:
- The database does not contain JSON module (ex. not a redis stack db, just simple redis 7 server)
- cloudSso is set to true
- cloudAds is set to true - this is true by default
=> RI-7026: Add JSON key -> Create free db dialog

redisinsight/ui/src/constants/keys.ts, redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-size-length/KeyDetailsHeaderSizeLength.spec.tsx
=> RI-6952: Change length label to top-level values for ReJSONs

redisinsight/ui/src/pages/home/components/database-manage-tags-modal/TagSuggestions.tsx
Issue: tags didn't work in build.
Reason: we bundle with lodash-es as opposed to what we use in dev (lodash) and chain doesn't work there
Solution: replace chain with uniqBy
=> RI-6384: fix tags crash in build

redisinsight/ui/src/pages/browser/components/add-key/AddKey.tsx
While fixing another bug in this PR - https://github.com/RedisInsight/RedisInsight/pull/4339, I introduced a regression.
When user has opened the add key form but clicks on the cancel button (right next to the Add button), an toast message appears:
It attempts to add the empty key object, or even if there is some input for the name to the state, not considering that it may be canceled. 
Applying this changes so  If add key panel is closed by clicking cancel, do not pass the key name to the add key panel handler above, otherwise, include it - as is.
=> Fix Add Key panel cancel regression

redisinsight/api/.eslintrc.js, redisinsight/api/src/modules/ai/chat/providers/conv-ai.provider.ts
Strip any line breaks in content sent to copilot.
not related to the issue, but changed eslint rules not to flag unused variables starting with underscore
In order to test that this is working a production build is required.
The way I did test is with `yarn package:mac:arm` 
If dev build is used, there is no difference with or without new lines, since the issue is with prod copilot API and staging copilot API is just fine with line breaks
=> RI-6865 copilot multiline input

redisinsight/ui/src/pages/home/components/database-manage-tags-modal/ManageTagsModal.tsx, redisinsight/ui/src/pages/home/components/database-manage-tags-modal/TagInputField.tsx, redisinsight/ui/src/pages/home/components/database-manage-tags-modal/constants.ts, redisinsight/ui/src/pages/home/components/database-manage-tags-modal/utils.ts
|  | |
| ------------- | ------------- |
| <img width="433" alt="Screenshot 2025-04-16 at 16 26 50" src="https://github.com/user-attachments/assets/511c2d62-5460-4b84-9fb3-a05f759ccaa3" />  | <img width="382" alt="Screenshot 2025-04-16 at 16 26 37" src="https://github.com/user-attachments/assets/b177e409-dfc8-466b-94ab-0a72744677a3" />  |
| <img width="378" alt="Screenshot 2025-04-16 at 16 25 50" src="https://github.com/user-attachments/assets/d8defd95-d9de-4532-8ffc-ae0e40939faf" />  | <img width="387" alt="Screenshot 2025-04-16 at 16 25 44" src="https://github.com/user-attachments/assets/737145d5-e4dc-4536-a19d-ef7caf7906a9" />  |
=> RI-6384: add unique tag validation errors

redisinsight/ui/src/components/instance-header/components/user-profile/UserProfileBadge.tsx, redisinsight/ui/src/utils/links.ts, redisinsight/ui/src/utils/tests/links.spec.ts
When opening an instance in RI cloud, we want to be able to open it in RI desktop as well, by clicking the user icon and 'Open in Redis Insight Desktop version' button:
after that, user gets prompted to click 'Open RedisInsight.app':
Attaching all kinds of query params as well to the RI desktop link.
Note: password is not available in the state so it has been decided not to set it in the URL. When opening in the desktop app, user will be prompt to input it manually.
=> RI-6964: Add link to Redis Insight desktop

redisinsight/api/src/modules/browser/rejson-rl/rejson-rl.service.spec.ts, redisinsight/api/src/modules/browser/rejson-rl/rejson-rl.service.ts
You can get more context on ReJSON path from the [official documentation.](https://redis.io/docs/latest/develop/data-types/json/path/#legacy-path-syntax).
But if you want just the TL;DR:
- ReJSON v2 uses `$.this.syntax`
- ReJSON v1 uses `.this.syntax` and this one is also supported in ReJSON v2, but it's considered legacy.
So with this PR:
- if ReJSON version is not reported - we fallback to legacy path option (a.k.a. `.`)
- if ReJSON version is 1 - again, the `.` path
- if ReJSON version is 2 - `$`
=> RI-7076: Use legacy ReJSON path

redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
Issue: When you search for a database, then sort by a column, then remove the search, then you try to sort by column, nothing happens.
Expected behavior: Should be able to sort by column regardless of filters
Solution: force react rerender whenever sort direction changes
=> RI-6992: fix databases list sorting and filtering issue

yarn.lock
Looks like with the new deps from this branch https://github.com/RedisInsight/RedisInsight/pull/4503 we missed the `yarn.lock` file.
=> DEV: Fix lockfile

redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/RejsonDetailsWrapper.spec.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/RejsonDetailsWrapper.tsx, redisinsight/ui/src/slices/browser/keys.ts, redisinsight/ui/src/slices/browser/rejson.ts, redisinsight/ui/src/slices/tests/browser/keys.spec.ts, redisinsight/ui/src/slices/tests/browser/rejson.spec.ts
3 major things are happening in this PR.
1. `forceRetrieve` flag used for the `ApiEndpoints.REJSON_GET` call is `true` when the selected editor is Monaco.
2. When the selected editor changes, the `ApiEndpoints.REJSON_GET` gets called (because, based on the editor, the result is going to be different).
3. When the selected Redis key is changed, the selected editor resets to the default value.
With these constraints, the logic inside `RejsonDetailsWrapper` gets a bit complicated, so we should rework the data flow to make the component dummy.
=> RI-6950: Fetch whole json when Monaco editor is selected

redisinsight/ui/src/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/components/database-overview/DatabaseOverview.spec.tsx, redisinsight/ui/src/components/database-overview/DatabaseOverview.tsx, redisinsight/ui/src/components/database-overview/components/OverviewMetrics/MetricItem.tsx, redisinsight/ui/src/components/database-overview/components/OverviewMetrics/OverviewMetrics.tsx, redisinsight/ui/src/components/database-overview/hooks/useDatabaseOverview.spec.ts, redisinsight/ui/src/components/database-overview/hooks/useDatabaseOverview.ts, redisinsight/ui/src/components/instance-header/InstanceHeader.spec.tsx, redisinsight/ui/src/constants/apiErrors.ts, redisinsight/ui/src/mocks/handlers/instances/instancesHandlers.ts, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.spec.tsx, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/pages/rdi/instance/InstancePage.spec.tsx, redisinsight/ui/src/services/apiService.ts, redisinsight/ui/src/slices/instances/instances.ts, redisinsight/ui/src/slices/tests/instances/instances.spec.ts, redisinsight/ui/src/utils/test-utils.tsx
When DB connection is not working, we're sending telemetry messages. Since `/overview` endpoint is called repeatedly every 5 s by default, we're sending a lot of redundand telemetry messages 
With this PR, overview call is made only if there is no connectivity error registered.
Also small connection lost indicator is added.
=> RI-7081: database connection failed is sent multiple times

redisinsight/api/src/modules/database/database-connection.service.spec.ts, redisinsight/api/src/modules/database/database-connection.service.ts
Currently, the provider is recalculated when a database is created or edited. However, instances that were added before this logic was introduced still have outdated or missing provider values.
This PR enhances the “connect database” logic to handle those legacy instances. When a user connects to such a database, the system will:
- Check if the stored provider is part of the current Host Provider list.
- If not, recalculate the provider to align it with the recognized list.
- Update the database instance with the new provider value.
This recalculation happens only once per instance, the first time it is connected after this logic is deployed.
Notes
- This ensures backward compatibility and smooth transition for older instances.
- Helps maintain consistency in provider metadata across all …
=> RI-7094: Recalculate provider on db connect

redisinsight/ui/src/slices/browser/rejson.ts, redisinsight/ui/src/slices/tests/browser/rejson.setJsonDataAction.spec.ts, redisinsight/ui/src/telemetry/telemetryUtils.ts, redisinsight/ui/src/telemetry/tests/telemetryUtils.spec.ts
`rejson` slice is hard to test due to its architecture. As a temporary solution, I added a new test suite, where modules can be dynamically reloaded in order to use the `jest` mocks.  Ideally, the business logic from this slice should be extracted and properly tested.
Apart from the event properties, this CL fixes a bug with reporting the JSON path level of nesting.
=> RI-6953: Send telemetry events for ReJSON used editor

redisinsight/ui/src/pages/home/components/database-manage-tags-modal/TagSuggestions.spec.tsx, redisinsight/ui/src/pages/home/components/database-manage-tags-modal/TagSuggestions.tsx
Issue: having selected a tag key, up to one suggested value is present in the list, even if there are more
| Before  | After |
| ------------- | ------------- |
|  <img width="835" alt="Screenshot 2025-05-20 at 10 21 37" src="https://github.com/user-attachments/assets/9df086e3-a9a0-466c-8031-7be16f81e5aa" /> | <img width="829" alt="Screenshot 2025-05-20 at 10 21 12" src="https://github.com/user-attachments/assets/f9ebc1ad-3aad-4a9d-9765-344ef2571e25" /> |
=> RI-7138: fix suggested tag values list

redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/RejsonDetailsWrapper.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/monaco-editor/MonacoEditor.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/styles.module.scss, redisinsight/ui/src/pages/browser/modules/key-details/styles.module.scss
With this PR https://github.com/RedisInsight/RedisInsight/commit/fe7b8af51b26991ffc945dba5e9a471a2714b05f, I've broken the styles a bit.
Generally, there are a few magics in the JSON editor HTML + CSS structure, like `calc(100%—X)`, `:global()`, or `position: absolute` on elements, that can be aligned without changing their position property. Cleaning this up properly would require a larger refactor. So for now, this PR introduces separate classes for the two editors to apply different styles as a workaround.
Note: header height changed from 115 to 108
=> RI-7139: Fix json editor styles

redisinsight/api/src/modules/database/dto/redis-info.dto.ts, redisinsight/api/src/modules/database/providers/database-info.provider.spec.ts, redisinsight/api/src/modules/database/providers/database-info.provider.ts, redisinsight/ui/src/components/base/layout/list/Item.tsx, redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/components/instances-list/InstancesList.spec.tsx, redisinsight/ui/src/components/instance-header/components/instances-navigation-popover/components/instances-list/InstancesList.tsx, redisinsight/ui/src/components/oauth/oauth-connect-free-db/OAuthConnectFreeDb.spec.tsx, redisinsight/ui/src/components/oauth/oauth-connect-free-db/OAuthConnectFreeDb.tsx, redisinsight/ui/src/mocks/data/instances.ts, redisinsight/ui/src/mocks/handlers/instances/instancesHandlers.ts, redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.test.tsx, redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx, redisinsight/ui/src/pages/rdi/instance/InstancePage.spec.tsx, redisinsight/ui/src/services/database/instancesService.ts, redisinsight/ui/src/services/index.ts, redisinsight/ui/src/slices/instances/instances.ts, redisinsight/ui/src/slices/tests/instances/instances.spec.ts, redisinsight/ui/src/telemetry/telemetryUtils.ts
Add data to: `CONFIG_DATABASES_OPEN_DATABASE`
Data fields added: 
- redis_version
- uptime_in_days
- used_memory
- connected_clients
- maxmemory_policy
- instantaneous_ops_per_sec
- instantaneous_input_kbps:
- instantaneous_output_kbps
- totalKeys
- numberOfKeysRange
=> RI-7106: additiona data in config databases open database

redisinsight/ui/src/components/base/layout/flex/flex.styles.ts, redisinsight/ui/src/components/base/layout/flex/flex.tsx, redisinsight/ui/src/components/base/text/Health.tsx, redisinsight/ui/src/pages/browser/components/add-key/AddKey.tsx, redisinsight/ui/src/pages/browser/components/create-redisearch-index/CreateRedisearchIndex.tsx, redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx, redisinsight/ui/src/pages/browser/components/filter-key-type/styles.module.scss
=> RI-7056 replace eui health

redisinsight/api/src/utils/catch-redis-errors.ts
Looks like we missed this, and the current `main` branch isn't working.
=> DEV: Fix missing import

.github/workflows/tests-e2e.yml, .github/workflows/tests.yml
This should cause the e2e tests to run only if a PR is approved (or manually via dispatch). Upon first approval, a label is set, that is later checked for later approvals in order to not run the tests again
To be merged after the main PR (https://github.com/RedisInsight/RedisInsight/pull/4615) is approved and ready for merge
=> [RI-6570] Detach E2E workflows

redisinsight/ui/src/pages/workbench/components/wb-view/WBView/WBView.tsx
Fixing Workbench Page, which was not displayed correctly because the handle direction was not set to horizontal and it defaults to vertical.
=> RI-7006: fix handle direction to horizontal

.github/workflows/enforce-branch-name-rules.yml
I think it makes sense to support also
fe - for just front end changes (recently had something like that for an RDI fix) in which cases there is no point in running the BE and integrations tests be - for just api changes. It also happens from time to time and it doesn't make sense to run all of our FE tests, especially how flaky they are. e2e - just for e2e tests. No point in wasting a lot of time (physical and github) to run all of the other tests
=> Added more branch options to enforce-branch-name-rules.yml

redisinsight/ui/src/pages/browser/components/no-keys-found/NoKeysFound.tsx
**Testing steps**:
- add db instance with no keys
- open the form to add a key manually
- load the sample data while the form is still open
- loaded data is displayed
**Expected**: The add key form should close when sample data is loaded 
**Before**: The add key form is open after load sample data is clicked and displayed
=> Ri-7024: close the add key panel if open, after load sample data is executed

redisinsight/ui/src/pages/database-analysis/components/empty-analysis-message/EmptyAnalysisMessage.tsx, redisinsight/ui/src/pages/database-analysis/components/header/Header.spec.tsx, redisinsight/ui/src/pages/database-analysis/components/header/Header.tsx
- Rename **New Report** to **Analyze**
- Change the empty message from **Run New Analysis...** to **Click Analyze** when no reports are generated:
old:
new:
=> RI-7022: Rename New Report to Analyze

package.json, redisinsight/ui/vite.config.mjs, tests/playwright/.gitignore, tests/playwright/.nycrc.json, tests/playwright/README.md, tests/playwright/fixtures/test.ts, tests/playwright/package.json, tests/playwright/yarn.lock, yarn.lock
Integrating **NYC (Istanbul)** code coverage collection into our Playwright E2E test suite, enabling automatic frontend code coverage reporting during test execution.
* extended Playwright fixtures to automatically collect Istanbul coverage data after each test
* added NYC configuration to properly process and report coverage for the UI source code
* enhanced package.json scripts with coverage-specific commands for running tests and generating reports
```bash
yarn dev:ui:coverage
cd tests/playwright
yarn test:coverage
```
After running tests with coverage, reports are generated in `tests/playwright/coverage/`:
- **HTML Report**: Open `coverage/index.html` in your browser for an interactive coverage explorer
- **LCOV Report**: `coverage/lcov.info` for CI/CD integration (Codecov, etc.)
- …
=> RI-6570 Configure code coverage reports for the playwright e2e tests

redisinsight/ui/src/components/base/tooltip/RITooltip.tsx, redisinsight/ui/src/components/base/tooltip/RiTooltip.spec.tsx
If only title or only content is provided, the tooltip should render
=> RI-7226: fix RiTooltip when title/content is empty

redisinsight/ui/src/pages/rdi/pipeline-management/PipelineManagementPage.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/PipelineManagementPage.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/navigation/Navigation.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/navigation/Navigation.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/source-pipeline-dialog/SourcePipelineModal.tsx, redisinsight/ui/src/slices/rdi/pipeline.ts
Show deployed pipeline from RDI server by default otherwise show a popup as now
=> RI-7187 show deployed pipeline by default

tests/playwright/helpers/api/api-keys.ts, tests/playwright/helpers/utils.ts, tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-read.spec.ts
Add new E2E tests to check the read functionality for different key types in the **Browsers** module. These tests make sure that when you click on a key, all its details show up correctly in the Details Panel (name, value(s), TTL, etc.).
* First, prepare the data for the test using the Redis API (it's easier and faster and also, the UI flow for creating keys is already covered in another test suite)
* Then we open the **Details Panel** by clicking on the key we just added (in the table in the UI)
* Finally, we check that all the key information is displayed correctly, like "**Key name**", "**Value(s)**", "**TTL**", etc.
* Extend the API to support adding various key types, enabling us to easily assemble test data
* Extend browser page locators to provide helpers for checking the state of …
=> RI-6570 Verify read operations for all key types in the browsers module

redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesDrawer.spec.tsx, redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesDrawer.tsx, redisinsight/ui/src/pages/vector-search/query/HeaderActions.spec.tsx, redisinsight/ui/src/pages/vector-search/query/HeaderActions.styles.ts, redisinsight/ui/src/pages/vector-search/query/HeaderActions.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx
Introduce a simple Vector Search actions panel that can be later injected in the proper place in the UI:
- Added simple component to present the different action buttons, based on the Redis UI `TextButton` component ([docs](https://redislabsdev.github.io/redis-ui/?path=/docs/components-buttons-textbutton--docs))
- Added button for "**Manage Indexes**" to open a container, based on the Redis UI `Drawer` component [docs](https://redislabsdev.github.io/redis-ui/?path=/docs/components-drawer--docs)
- Added a placeholder button for "**Saved Queries**" drawer, which will be implemented separately
_Note: For now, the content of the drawer is blank, but it will be implemented in a separate pull request_
These are base components that will be included in the new wizard for the Vector Search, but …
=> RI-7197 Introduce vector search actions panel

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-delete.spec.ts
Add new E2E tests to check the delete functionalities for different key types in the Browsers module. These tests make sure that you can delete an existing key - both from the list and its details page.
- Then, we click on the delete icon button and verify whether the record is deleted successfully
_Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/feature/RI-6570 …
=> RI-6570 Verify delete operations for all key types in the browsers module

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-edit.spec.ts
Add new E2E tests to check the generic update functionalities in the Browsers module. These tests make sure that when you click on a key, you can update its name and TTL.
- After that, we go and update the key name and its TTL
_Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/feature/RI-6570/PlayWright) branch._
* Extend browser page locators to provide helpers …
=> RI-6570 Verify generic edit operations in the browsers module

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-edit/edit-list-key.spec.ts
Add new E2E tests to check the update functionalities for list key types in the Browsers module. These tests make sure that when you click on a key, you can update all of its details in the Details Panel.
- After that, we go and update the values, depending on the field type (and verify the change)
Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/feature/RI-6570/ …
=> RI-6570 Verify edit list key operations for in the browsers module

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-edit/edit-set-key.spec.ts, tests/playwright/tests/browser/keys-edit/edit-zset-key.spec.ts
Add new E2E tests to check the update functionalities for set and sorted set key types in the Browsers module. These tests make sure that when you click on a key, you can update all of its details in the Details Panel.
-  After that, we go and update the values, depending on the field type (and verify the change)
Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/f …
=> RI-6570 Verify edit set and sorted set keys operations for in the browsers module

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-edit/edit-hash-key.spec.ts
Add new E2E tests to check the update functionalities for hash key types in the Browsers module. These tests make sure that when you click on a key, you can update all of its details in the Details Panel.
- After that, we go and update the values, depending on the field type (and verify the change)
Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/feature/RI-6570/ …
=> RI-6570 Verify edit hash keys operations for in the browsers module

tests/playwright/pageObjects/browser-page.ts, tests/playwright/tests/browser/keys-edit/edit-json-key.spec.ts
Add new E2E tests to check the update functionalities for json key types in the Browsers module. These tests make sure that when you click on a key, you can update all of its details in the Details Panel.
- After that, we go and update the values, depending on the field type (and verify the change)
Note: Once [PR: 4723](https://github.com/redis/RedisInsight/pull/4723) is merged, make sure to update the target branch of this pull request to lead to [feature/RI-6570/PlayWright](https://github.com/redis/RedisInsight/tree/feature/RI-6570/ …
=> RI-6570 Verify edit json keys operations for in the browsers module

redisinsight/ui/src/components/new-index/create-index-step/CreateIndexStepWrapper.spec.tsx, redisinsight/ui/src/components/new-index/create-index-step/CreateIndexStepWrapper.styles.ts, redisinsight/ui/src/components/new-index/create-index-step/CreateIndexStepWrapper.tsx
Created a base wrapper for the "Create Index" step part of the new Vector Search
- Integrate the [ButtonGroup](https://redislabsdev.github.io/redis-ui/?path=/docs/components-buttongroup--docs) component from Redis UI to serve as a base wrapper and make it feel like the `Tabs` component
_PS: This is a follow-up of this PR: https://github.com/redis/RedisInsight/pull/4670_
This is a base component that will be included in the new wizard for the Vector Search, but it's currently a standalone component. So, you won't be able to find it integrated anywhere in the flow so far.
Here is an example implementation of how to use the component for the Vector Search feature. The idea is to be able to easily plug the `CreateIndexStepWrapper` component into the wizard later, once implemented.
```
// …
```
=> RI-7237 Rework tabs component for vector search flow

redisinsight/ui/src/components/base/layout/horizontal-spacer/HorizontalSpacer.spec.tsx, redisinsight/ui/src/components/base/layout/horizontal-spacer/horizontal-spacer.styles.ts, redisinsight/ui/src/components/base/layout/horizontal-spacer/horizontal-spacer.tsx, redisinsight/ui/src/components/base/layout/horizontal-spacer/index.ts, redisinsight/ui/src/components/base/layout/index.ts, redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/messages-view/MessageAckPopover/MessageAckPopover.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/stream-details/messages-view/MessageAckPopover/styles.module.scss
Removed the old sass styling.
Added a new horizontal spacer (similar to the existing spacer). The same thing could've been done with a margin, but I think we'll need some space here and there as well anyway.
Specifically for @pawelangelow there are a few small tests :) Including validating the parsing of the sizes
=> RI-7224 - in messages - ACK / CLAIM buttons need space between

redisinsight/ui/src/components/base/layout/flex/flex.styles.ts, redisinsight/ui/src/components/index.ts, redisinsight/ui/src/components/navigation-menu/NavigationMenu.tsx, redisinsight/ui/src/components/navigation-menu/app-navigation/AppNavigation.styles.ts, redisinsight/ui/src/components/navigation-menu/app-navigation/AppNavigation.tsx, redisinsight/ui/src/components/navigation-menu/hooks/useNavigation.ts, redisinsight/ui/src/components/navigation-menu/navigation.types.ts, redisinsight/ui/src/contexts/AppNavigationActionsProvider.tsx, redisinsight/ui/src/pages/browser/BrowserPage.spec.tsx, redisinsight/ui/src/pages/browser/BrowserPage.tsx, redisinsight/ui/src/pages/browser/components/actions/Actions.spec.tsx, redisinsight/ui/src/pages/browser/components/actions/Actions.tsx, redisinsight/ui/src/pages/browser/components/browser-search-panel/BrowserSearchPanel.spec.tsx, redisinsight/ui/src/pages/browser/components/browser-search-panel/BrowserSearchPanel.tsx, redisinsight/ui/src/pages/home/HomePage.tsx, redisinsight/ui/src/templates/instance-page-template/InstancePageTemplate.tsx
Top bar nav
<video src="https://github.com/user-attachments/assets/d44cda02-ce37-4fed-b408-142af2d157ba" width="300" />
=> RI-7235 new navigation

redisinsight/ui/src/components/base/forms/buttons/IconButton.tsx, redisinsight/ui/src/components/base/icons/RiIcon.tsx, redisinsight/ui/src/components/database-list-modules/DatabaseListModules.tsx, redisinsight/ui/src/components/recommendation/recommendation-voting/components/vote-option/VoteOption.tsx, redisinsight/ui/src/pages/home/components/database-list-component/DatabasesListWrapper.tsx
=> RI-7243 capabilities not displayed

redisinsight/ui/src/components/query/index.ts, redisinsight/ui/src/components/query/query-lite-actions/QueryActions.spec.tsx, redisinsight/ui/src/components/query/query-lite-actions/QueryLiteActions.tsx, redisinsight/ui/src/components/query/query-lite-actions/index.ts, redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx, redisinsight/ui/src/pages/workbench/components/query/QueryWrapper.tsx
This is a prerequisite PR for https://github.com/redis/RedisInsight/pull/4788
In order to match the design, we need a lite version of the `<Query />` actions. Since the final state isn't clear, I decided to "hack" the current component. After we get the bigger picture, we can think of proper refactoring.
=> RI-7195: Extend Query component

redisinsight/ui/src/components/base/forms/FormField.ts, redisinsight/ui/src/components/base/forms/FormField.tsx, redisinsight/ui/src/pages/rdi/home/connection-form/ConnectionForm.tsx, redisinsight/ui/src/styles/base/_inputs.scss
Refactored the formfield to handle the infoIconProps so we can use it for these cases.
=> RI-7240 - White-area-below-the-tooltip-in-connection-forms

redisinsight/ui/src/components/base/display/toast/RiToast.tsx, redisinsight/ui/src/components/notifications/Notifications.tsx, redisinsight/ui/src/slices/app/notifications.ts
since auto-remoal does not work with redis-ui Toast, we're storing a map of displayed components and if we attempt to display them again, simply remove them. This effectively shifts the `read` state outside the `message`
=> RI-7247: manage displayed notifications in Notifications.tsx

.github/workflows/aws-upload-enterprise.yml
This PR is to rename update the build names for Enterprise builds to include 'Enterprise' and build version. e.g. `Redis-Insight-Enterprise-v2-70-0-amd64.deb`
In scope of this PR generic function was added which simply find all files starting with `Redis-Insight*` and rename them. Besides that hash sum files `latest*.yml` modified to aligned with new file names
=> RI-7204 change enterprise build names

redisinsight/ui/src/components/base/layout/flex/flex.styles.ts, redisinsight/ui/src/pages/vector-search/VectorSearchPage.spec.tsx, redisinsight/ui/src/pages/vector-search/create-index/steps/CreateIndexStep.spec.tsx, redisinsight/ui/src/pages/vector-search/create-index/steps/CreateIndexStep.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx
- use correct play button
- revert flex gap (lost during last [update from eui branch](https://github.com/redis/RedisInsight/pull/4808))
=> [RI-7194] fix Create Index style issues

redisinsight/ui/src/components/base/icons/Icon.tsx, redisinsight/ui/src/pages/rdi/instance/components/header/components/buttons/deploy-pipeline-button/DeployPipelineButton.spec.tsx, redisinsight/ui/src/pages/rdi/instance/components/header/components/buttons/deploy-pipeline-button/DeployPipelineButton.tsx, redisinsight/ui/src/pages/rdi/instance/components/header/components/pipeline-actions/PipelineActions.spec.tsx, redisinsight/ui/src/pages/rdi/instance/components/header/components/pipeline-actions/PipelineActions.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/jobs-tree/JobsTree.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/jobs-tree/JobsTree.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/jobs-tree/styles.module.scss, redisinsight/ui/src/pages/rdi/pipeline-management/components/navigation/Navigation.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/tab/Tab.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/tab/Tab.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/validation-errors-list/ValidationErrorsList.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/components/validation-errors-list/ValidationErrorsList.tsx
Show validation errors in a tooltips and do not block deploy button in case of validation errors
=> RI-7217 allow to deplot rdi pipeline with validation errors

redisinsight/ui/src/pages/vector-search/query/HeaderActions.styles.ts, redisinsight/ui/src/pages/vector-search/styles.ts
| Before    | After |
| -------- | ------- |
| <img width="1085" height="541" alt="Screenshot 2025-08-07 at 14 13 04" src="https://github.com/user-attachments/assets/041b83a0-3293-4e5a-ba6f-f39f53a12037" /> | <img width="1076" height="500" alt="Screenshot 2025-08-07 at 14 11 10" src="https://github.com/user-attachments/assets/d8a3114e-0546-439a-9b50-fd2764377e45" /> |
| <img width="1076" height="520" alt="Screenshot 2025-08-07 at 14 13 13" src="https://github.com/user-attachments/assets/32e9db4d-094d-44e9-8617-49e8e12a8c90" /> | <img width="1077" height="428" alt="Screenshot 2025-08-07 at 14 11 27" src="https://github.com/user-attachments/assets/4c5a833f-9270-4b4e-be2d-c0033994b28a" /> |
=> RI-7289: adjust Create Index wizard spacing to match style of Workbench/Browser

redisinsight/ui/src/components/recommendation/recommendation-voting/components/vote-option/VoteOption.tsx, redisinsight/ui/src/components/scan-more/ScanMore.tsx, redisinsight/ui/src/components/scan-more/styles.module.scss, redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/LiveTimeRecommendations.tsx, redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/components/recommendation/Recommendation.tsx, redisinsight/ui/src/pages/browser/components/filter-key-type/FilterKeyType.tsx
A number of small miss-alignments
=> Ri-0000 fix recommendations styles

redisinsight/ui/src/components/base/tooltip/HoverContent.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/change-editor-type-button/ChangeEditorTypeButton.spec.tsx
Tooltip size S seems a little too big for the content, so changing it to XS.
Before:
After:
=> RI-7242: Change the tooltip title size from S to XS

.github/build/release-docker.sh, redisinsight/api/config/default.ts, redisinsight/api/config/swagger.ts, redisinsight/api/package.json, redisinsight/desktop/src/lib/aboutPanel/aboutPanel.ts, redisinsight/package.json, redisinsight/ui/src/components/side-panels/components/copilot-panel/CopilotPanel.tsx, redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/chats-wrapper/ChatsWrapper.tsx, redisinsight/ui/src/components/side-panels/panels/ai-assistant/components/texts.tsx, redisinsight/ui/src/pages/pub-sub/PubSubPage.tsx, redisinsight/ui/src/pages/pub-sub/styles.module.scss
Added the same style the tips/insights have to the copilot tabs
Added the same fix for links Same fix as https://github.com/redis/RedisInsight/pull/4805/files#diff-05f1210823b0f8c65973870768a5927f7100cd30283d35b5b8041015444d9d73
Removed the Pub/Sub title altogether as it was not used anywhere.
Refactored the header to use styled components as well, instead of sass, with the proper theme border, instead of eui color.
=> Fe/feature/RI-7351 and RI-7350 and RI-7349

redisinsight/ui/src/components/oauth/shared/oauth-social-buttons/OAuthSocialButtons.tsx
I've replaced the FlexItem with FlexGroup so the children can be center aligned
=> RI-7332---Authentication-options-are-not-centered-with-their-corresponding-icons

redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx
- to remove a warning (max size should be more than the default size)
- to adjust for better UX
=> RI-6855: Adjust default values for resizable Search containers

redisinsight/ui/src/pages/vector-search/create-index/steps/styles.ts
Make the background of the code snippet block in the "**Command Preview**" drawer to support dark theme.
| Old | New |
|-|-|
1. Open a connection to a new or existing Database
2. Go to the **Search** page from the top navbar
- If you don't have any indexes yet, you'll see the "**Create Index**" wizard
- Otherwise, you should trigger the creation process by clicking "**Get Started**" from the alert below the top navbar
- Or simply, go to the following URL manually: http://localhost:8080/:databaseId/vector-search/create-index
3. On the first step of the creation process, click on the "**Proceed to index**" button in the bottom right corner of the page
4. On the second step of the flow, click on the "**Command preview**" button under the index attributes to see the command that will be …
=> RI-7362 Added support for dark theme for the "Command Preview" drawer

redisinsight/ui/src/components/explore-guides/ExploreGuides.tsx, redisinsight/ui/src/components/explore-guides/icons.ts, redisinsight/ui/src/pages/browser/components/no-keys-found/NoKeysFound.tsx
- Fix the missing icons for JSON and Probabilistic types by changing the icon name in the GUIDE to match the names in Redis Component icons. 
- Apply some changes to the text and the title above to look nicer
- Replace `... amazing world of Redis Stack ...` with only `... amazing world of Redis ...`
| Before | After | 
|----------|----------|
| <img width="613" height="627" alt="image" src="https://github.com/user-attachments/assets/99be96a1-ebd4-480c-a9f7-9d2ffe538638" />   | <img width="613" height="627" alt="image" src="https://github.com/user-attachments/assets/16c5550e-c32f-4dd5-a9f5-c31bddb334bf" />  |
| <img width="613" height="627" alt="image" src="https://github.com/user-attachments/assets/00ae741f-4438-4c3b-89cb-e2fb34eefc0c" />   | <img width="613" height="627" alt="image" …
=> RI-7378: Missing icons fix

redisinsight/ui/src/components/base/forms/buttons/EmptyButton.tsx, redisinsight/ui/src/pages/vector-search/create-index/VectorSearchCreateIndex.tsx, redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesScreen.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/styles.ts, redisinsight/ui/src/pages/vector-search/styles.ts
This PR addresses two issues related to the same sections 
- RI-7374 - adjusts the Saved Queries wrapper to match the new design
- RI-7373 - adds close button to Saved Queries & Manage indexes
- adjusts paddings for Saved Queries & Manage indexes to match the new design
| --- | --- |
| <img width="730" height="554" alt="Screenshot 2025-08-20 at 16 47 48" src="https://github.com/user-attachments/assets/4a3453d0-beb2-490c-8b9b-a957f4de416d" /> | <img width="710" height="496" alt="Screenshot 2025-08-20 at 16 47 20" src="https://github.com/user-attachments/assets/d3f2583e-bec8-45df-8c56-8d93c038c15b" /> |
=> [RI-7374] [RI-7373]: update Saved Queries layout to match new design

redisinsight/ui/src/pages/vector-search/create-index/VectorSearchCreateIndex.spec.tsx, redisinsight/ui/src/pages/vector-search/create-index/VectorSearchCreateIndex.tsx, redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesList.spec.tsx, redisinsight/ui/src/pages/vector-search/manage-indexes/ManageIndexesList.tsx, redisinsight/ui/src/pages/vector-search/pages/VectorSearchPage.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.spec.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/IndexSelect.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/IndexSelect.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/QueryCard.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/QueryCard.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/types.ts, redisinsight/ui/src/pages/vector-search/useRedisearchListData.ts
- After creating a new index, automatically selects that index in saved queries panel and expands it
- When no indexes are available, Saved Queries shows a placeholder component
| --- | --- |
| always showing the preset queries, even when no index has been inserted | when no index is available, show the same component used as in Manage Indexes |
| <img width="539" height="511" alt="Screenshot 2025-08-21 at 15 38 30" src="https://github.com/user-attachments/assets/ef7a3aaa-a799-4354-a1e1-ead719a7a8a1" /> | <img width="642" height="516" alt="Screenshot 2025-08-21 at 14 27 04" src="https://github.com/user-attachments/assets/63897e06-8e10-4379-93b7-0b0e529450b4" /> |
There is a new design for the "No indexes" component which will be addressed in another ticket
=> RI-7366: Saved Queries - show empty message when no indexes are available

redisinsight/ui/src/pages/rdi/pipeline-management/PipelineManagementPageRouter.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/Job.spec.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/Job.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/JobsWrapper.spec.tsx, redisinsight/ui/src/slices/rdi/pipeline.ts, redisinsight/ui/src/slices/tests/rdi/pipeline.spec.ts
Make sure to preserve the changes entered in the editor of the different RDI pipeline jobs when switching between them
- introduce a new Redux action to update a single Pipeline Job
https://github.com/user-attachments/assets/378ecf52-dc01-4020-af2b-30d4b357cd08
The issue that we observed was related to the fact that we lose the changes of the users when they toggle between the different pipeline jobs. It was caused by a stale Redux update, which was the cause of the lost changes. What we had in place was a complex Redux action that was updating all the jobs once we entered changes in the text editor. 
As a solution, I have introduced a new, simpler redux action that is meant to update the value of a single pipeline job (when you enter changes in the editor), instead of providing all jobs, …
=> RI-7311 Resolve issue with disappearing changes in the RDI pipeline jobs

redisinsight/ui/src/pages/browser/modules/key-details/KeyDetails.spec.tsx, redisinsight/ui/src/pages/browser/modules/key-details/KeyDetails.tsx
Add the “Formatter” parameter to the following telemetry events:
1. TREE_VIEW_KEY_VALUE_VIEWED
2. BROWSER_KEY_VALUE_VIEWED
=> RI-7266: add formatter field to telemetry events

redisinsight/ui/src/components/command-helper/CommandHelper/CommandHelper.tsx, redisinsight/ui/src/components/command-helper/components/command-helper-search-output/CHSearchOutput.tsx, redisinsight/ui/src/components/command-helper/components/command-helper-search-output/styles.module.scss
| -----| ------|
| <img width="1600" height="282" alt="before" src="https://github.com/user-attachments/assets/016e23cc-add2-4b94-a580-5cfde2e125ea" /> | <img width="505" height="286" alt="image" src="https://github.com/user-attachments/assets/0b0f282e-865a-4f5f-8813-378136c925a6" /> |
=> RI-7377: fix command helper styles

redisinsight/ui/src/components/consents-settings/ConsentOption/ConsentOption.tsx, redisinsight/ui/src/components/consents-settings/ConsentOption/components/ItemDescription.tsx, redisinsight/ui/src/components/consents-settings/ConsentsPrivacy/ConsentsPrivacy.tsx, redisinsight/ui/src/components/consents-settings/ConsentsSettings.tsx, redisinsight/ui/src/components/consents-settings/styles.module.scss, redisinsight/ui/src/constants/links.ts, redisinsight/ui/src/pages/rdi/pipeline-management/pages/config/Config.tsx, redisinsight/ui/src/pages/rdi/pipeline-management/pages/job/Job.tsx, redisinsight/ui/src/pages/settings/components/general-settings/datetime-formatter/DateTimeFormatter.tsx, redisinsight/ui/src/pages/settings/components/general-settings/datetime-formatter/styles.module.scss
- change text color from subdued (blueish) to primary
- remove custom and unneeded styles which automatically fix some alignments
- use theme variables and redis components where possible
- replace leftover EuiLink component
| ----- | ------ |
| <img width="568" height="84" alt="image" src="https://github.com/user-attachments/assets/0506cc3d-2836-4074-af8c-861ad2b64e0e" /> | <img width="709" height="113" alt="image" src="https://github.com/user-attachments/assets/7ca4dec1-95b6-4deb-93b6-1e2c2779db56" /> |
| <img width="855" height="84" alt="image" src="https://github.com/user-attachments/assets/65a5e57c-a366-4c5e-a86a-0f0b7d185acf" /> | <img width="855" height="113" alt="image" src="https://github.com/user-attachments/assets/3371d959-aa5e-407e-ac10-29a1543e8f3f" /> |
| …
=> RI-7338: Fix text and links on RDI page, Settings and EULA screen

redisinsight/ui/src/packages/redisearch/src/components/TableResult/TableResult.tsx, redisinsight/ui/src/packages/redisgraph/src/Graph.tsx, redisinsight/ui/src/packages/ri-explain/src/Explain.tsx, redisinsight/ui/src/packages/ri-explain/src/Node.tsx
The main problem was related to how components imported to plugins.
e.g. `import { RiTooltip } from '../../../../../components'` will fail because bootstrap file in the components folder has more components which might require riConfig or redux state to be initialized
when change to `import { RiTooltip } from '../../../../../components/base/tooltip/RITooltip'` everything works since RiTooltip is stateless itself
=> RI-7384: fix plugins imports to avoid riConfig or redux state initialization errors

redisinsight/ui/src/components/base/inputs/PasswordInput.tsx, redisinsight/ui/src/pages/home/components/form/DatabaseForm.tsx
Due to security reasons, we do not want to have a functionality where password can be seen. Instead, when user clicks on the not empty password field, the field gets cleared and user can enter a new one without seeing the old. 
These changes just remove the hide / unhide button: 
| Before | After | 
| ---- | ---- |
| <img width="497" height="112" alt="image" src="https://github.com/user-attachments/assets/a5e6b2bf-0f93-4c3c-a202-9da34ed4a9a1" /> | <img width="497" height="112" alt="image" src="https://github.com/user-attachments/assets/1f40a5c0-6d62-4a18-977a-4a1aa88b63c5" /> |
| <img width="497" height="112" alt="image" src="https://github.com/user-attachments/assets/f5361e4c-b7b5-468b-b09c-2431d255bd4a" /> | <img width="497" height="112" alt="image" …
=> RI-7330: remove show/hide for the password

redisinsight/ui/src/components/query/query-lite-actions/QueryLiteActions.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.tsx
On the Vector Search page, clicking **Control + Enter** should do the same as the **Run** button. This did not work as the value was not passed to to the onQuerySubmit method. Also, changed the onClick event for the button in QueryLiteActions, as it was passing an event which is not desired scenario.
=> RI-7354: fix the control + enter button to run the query in on Search Page

redisinsight/ui/src/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/components/database-overview/hooks/useDatabaseOverview.ts, redisinsight/ui/src/pages/instance/instanceConnectionLost.spec.tsx, redisinsight/ui/src/services/apiService.ts, redisinsight/ui/src/services/tests/apiService.spec.ts, redisinsight/ui/src/slices/tests/app/connectivity.spec.ts
Fix the "Connection Status" indicator in the Database Overview section to not alert that the connection is lost when it actually is active. It was happening when you try to establish a connection with another (not-running) database, wrongly affecting the status indicator for the current database connection.
_PS: Additionally, I found a weird behavior that the manual Refresh of the connection status was not working consistently. You can learn more about that in the comments below._ 
1. Open Redis Insight and connect to a (_running_) database instance, you should be able to do so
2. Try to switch the database connection to another **not-running** database instance, a toast notification will inform you, and the status icon in the top navbar shouldn't turn red
3. If you turn off the Redis …
=> RI-7364 Connection to server lost

package.json
The `devEngines` field has changed in newer versions of npm and is now causing issues. For example, running `npx npkill` fails with:
```
npm error Invalid property "node"
```
This happens because npm expects a different format ([docs](https://docs.npmjs.com/cli/v11/configuring-npm/package-json#devengines)).
Additional context can be found [in this StackOverflow thread](https://stackoverflow.com/questions/79204945/why-does-npm-keep-giving-out-invalid-property-node).
TL;DR: The engines field already covers the original intent of devEngines. If we need runtime-specific configs in the future, we should add them via the officially supported configuration options.
=> DEV: Remove unsupported devEngines field 

redisinsight/ui/vite.config.mjs
When you install the dependencies root level, usually something like this happens:
which is caused by Vite, which is trying to optimise dependencies. The problem is that some of these dependencies are Node.js ones, not meant to run on the browser => we're getting errors.
There are probably more dependencies that can be included:
```
'class-validator',
'ioredis',
'redis',
'typeorm',
'sqlite3',
'express',
'socket.io',
'socket.io-client',
'fs-extra',
'jsonwebtoken',
'winston',
'adm-zip',
'busboy',
'tunnel-ssh',
'@segment/analytics-node',
```
but my driver for opening this PR was the ugly error, so if we find it useful to add more of that list, we can do it in a separate PR.
=> RI-7410: Exclude backend dependencies from frontend optimisation

redisinsight/ui/src/components/base/display/toast/RiToast.tsx, redisinsight/ui/src/components/notifications/Notifications.tsx, redisinsight/ui/src/components/notifications/success-messages.tsx
- Make the title same size as the text, but bold
- Make the added / deleted or whatever contents needs to be highlighted - to be bold
- Change Ok to OK for success messages to match error messages 
| ---- | ---- |
| <img width="439" height="124" alt="Screenshot 2025-07-25 at 15 32 05" src="https://github.com/user-attachments/assets/2c2d2667-108a-4fc6-920f-9d7d877f0885" /> | <img width="458" height="119" alt="image" src="https://github.com/user-attachments/assets/455fcf3c-fbab-44c9-8391-7da63b3f877a" /> <img width="458" height="93" alt="image" src="https://github.com/user-attachments/assets/fea03d8e-47f7-426a-814e-3c8e8d805c14" /> |
=> RI-7259: Fix Toast message display by highlighting the title

.github/workflows/tests.yml
Add a way to trigger the tests in the CI via a label, so we can run them for the open source contributions when they don't follow the branch naming strategy (_that runs them automatically_).
- `run-all-tests`
- `run-frontend-tests`
- `run-backend-tests`
- `run-integration-tests`
=> Trigger the tests in the CI via a label

redisinsight/ui/src/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/components/auto-refresh/styles.module.scss, redisinsight/ui/src/components/keys-summary/KeysSummary.tsx, redisinsight/ui/src/components/keys-summary/styles.module.scss, redisinsight/ui/src/components/scan-more/ScanMore.tsx, redisinsight/ui/src/components/scan-more/styles.module.scss, redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeSettings/KeyTreeSettings.tsx, redisinsight/ui/src/pages/browser/components/key-tree/KeyTreeSettings/styles.module.scss, redisinsight/ui/src/pages/browser/components/keys-header/KeysHeader.tsx, redisinsight/ui/src/pages/browser/components/keys-header/styles.module.scss, redisinsight/ui/src/styles/base/_helpers.scss
=> RI-7431: Layout fixed. Rework keys list/tree header

redisinsight/ui/src/pages/browser/components/actions/Actions.tsx, redisinsight/ui/src/pages/browser/components/browser-search-panel/styles.module.scss
| - | - |
|<img width="245" height="50" alt="Screenshot 2025-09-16 at 17 24 53" src="https://github.com/user-attachments/assets/76baf200-f817-40af-a358-36d850758081" />|<img width="264" height="61" alt="Screenshot 2025-09-16 at 17 24 38" src="https://github.com/user-attachments/assets/fe5ebfe1-bfb5-40ac-bfce-2f401f2474d1" />|
=> RI-7431: Change add key button view

redisinsight/ui/src/pages/vector-search/components/onboarding/VectorSearchOnboarding.spec.tsx, redisinsight/ui/src/pages/vector-search/components/onboarding/VectorSearchOnboarding.styles.ts, redisinsight/ui/src/pages/vector-search/components/onboarding/VectorSearchOnboarding.tsx, redisinsight/ui/src/pages/vector-search/components/onboarding/components/Features.styles.ts, redisinsight/ui/src/pages/vector-search/components/onboarding/components/Header.tsx, redisinsight/ui/src/pages/vector-search/context/VectorSearchOnboardingContext.spec.tsx, redisinsight/ui/src/pages/vector-search/context/VectorSearchOnboardingContext.tsx, tests/playwright/tests/vector-search/onboarding.spec.ts
Make adjustments to the behavior and the visuals of the Onboarding screen that users see when they open the **Vector Search** page for the first time
- no longer silently mark the onboarding as seen, unless it's explicitly dismissed by the user (video bellow)
- update the spacings (after discussion with the designer) to match what we have in Figma and ignore Redis UI
1. Open existing database (or connect to a new instance)
2. Go to the **Search** page (click on the corresponding link in the main navbar)
3. You'll land on the new onboarding screen, presenting the Vector Search feature
- clicking on the "**X**" button in the top right corner will dismiss the screen
- clicking on the "**Skip for now**" button will dismiss the screen
- clicking on the "**Explore vector search**" button will …
=> RI-7479 Rework the vector search onboarding screen

redisinsight/ui/src/components/auto-refresh/AutoRefresh.tsx, redisinsight/ui/src/components/auto-refresh/styles.module.scss, redisinsight/ui/src/components/inline-item-editor/styles.module.scss
Rework AutoRefresh popover to align to the rest design
|Before|After|
|-|-|
=> RI-7431: rework autorefresh popover layout

redisinsight/ui/src/components/base/display/toast/RiToast.tsx, redisinsight/ui/src/components/base/external-link/ExternalLink.tsx, redisinsight/ui/src/components/notifications/Notifications.tsx, redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.spec.tsx, redisinsight/ui/src/components/notifications/components/infinite-messages/InfiniteMessages.tsx, redisinsight/ui/src/slices/interfaces/app.ts
Update the visuals of the infinite notification to resemble more closely the Redis UI toasts, and the FIgma designs.
- update the interface and the way we serve the data for the infinite notification, so it will resemble more closely the expected format by Redis UI, and make all infinite notifications use it
- rework the way we show the default "X" button for dismissing notifications
- update the variant to reflect the expected design
There are numerous use cases in which we use infinite notifications. Although we have a common way to dispatch these types of notifications, I still had to update the way we build up the data for each notification. Here are all of the updated notifications:
1. Click on the "Cloud Login" button in the top right corner, and login via one of the providers
2. …
=> RI-7254 Update the visuals of the toast notifications

redisinsight/ui/src/components/base/utils/OutsideClickDetector.tsx, redisinsight/ui/src/components/inline-item-editor/InlineItemEditor.tsx
Disable outside click detector when ConfirmationPopover is shown.
Since ConfirmationPopover is "outside" the click detector "jurisdiction", 
clicking anywhere on it unmounts the editor and therefore, \form submission does not happen
=> RI-7461: Unable to edit string key in JSON formatter

redisinsight/ui/src/components/messages/database-not-opened/DatabaseNotOpened.tsx, redisinsight/ui/src/components/side-panels/components/header/styles.module.scss, redisinsight/ui/src/components/side-panels/panels/enablement-area/EnablementArea/components/Group/Group.tsx, redisinsight/ui/src/components/side-panels/panels/enablement-area/EnablementArea/components/Navigation/Navigation.tsx, redisinsight/ui/src/components/side-panels/panels/enablement-area/EnablementArea/components/Pagination/Pagination.tsx, redisinsight/ui/src/components/side-panels/panels/enablement-area/EnablementArea/components/Pagination/styles.module.scss, redisinsight/ui/src/components/side-panels/panels/enablement-area/EnablementArea/styles.module.scss, redisinsight/ui/src/components/side-panels/panels/live-time-recommendations/components/recommendation/Recommendation.tsx, redisinsight/ui/src/components/side-panels/styles.module.scss, redisinsight/ui/src/styles/themes/light_theme/_theme_color.scss
Update the visuals of the Insights panel to make it look "not broken", after the EUI replacement.
- added spacing between the "Insights" title and the tabs
- added spacing between the tabs and the tutorial's content
- match the width of the tips subheader, with the tabs panel above it
- update visuals of the pagination buttons in the tutorials
| - | - |
- align the icons and the titles in the tutorials sections
- added a spacer between the action button and the warning banner in "my tutorials"
- fix the inline padding in the nested sections
- scroll the tutorial to the top when changing pages
- update popover styles
| - | - |
- removed borders and paddings for the content of the tips
- added full title above the content of the tip, if it's longer and …
=> RI-7474 Fix Insights panel visuals

redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx
Stop showing custom indexes in the list with the "**Saved Queries**" on the new **Search** page. Only preset sample data indexes come with such queries, so we should show only them in the list.
_Note: Previously, we were showing the index, but with a blank space, leaving the users without any control over it._
2. Go to the **Browser** page and import sample data
_Note: If the database is not empty, you can run `flushdb` in the CLI, to make sure you can import sample data_
3. Go to the **Search** tab from the main navbar
4. Open the **Saved Queries** panel from the top right corner
You shouldn't see any indexes in the list, although you have such in the **Manage Indexes** …
=> RI-7517 Hide custom indexes from "Saved Queries" list

redisinsight/ui/src/pages/browser/modules/key-details/components/text-details-wrapper/styles.module.scss
When there is Time Series key, the details are not displayed on the right like for most of the other key types, but there is a redirecting screen to workbench. The text in that screen has broken styles.
| --- | --- |
| <img width="1214" height="688" alt="image" src="https://github.com/user-attachments/assets/0d52663e-dc7a-4ec9-951c-06059c5db1dd" /> | <img width="1214" height="688" alt="image" src="https://github.com/user-attachments/assets/36d48c48-d193-4b1d-8adf-dc4f137fdd94" /> | 
| <img width="1214" height="688" alt="image" src="https://github.com/user-attachments/assets/9b18a9d5-da8f-4818-99d0-a102f2cbc343" /> | <img width="1214" height="688" alt="image" src="https://github.com/user-attachments/assets/2208a5bd-8957-4338-8306-1cbaa03c5b88" /> |
=> RI-7529: Fix Time Series screen text for redirecting to Workbench

redisinsight/ui/src/pages/workbench/components/query/Query/Query.tsx, tests/playwright/pageObjects/pages/vector-search/vector-search-page.ts, tests/playwright/tests/vector-search/query.spec.ts, tests/playwright/tests/vector-search/saved-queries.spec.ts
Disable the "suggestions tooltip" in the code editor on the **Vector Search** page when inserting a saved query, because it was hiding the **Run** button (_on a specific screen size_).
| - | - |
2. Go to the **Search** tab from the main navbar
_Note: Make sure to create a new index via the preset sample datasets, following the Vector Search onboarding wizard._
3. Open the **Saved Queries** panel from the top right corner
4. Click on the "**Insert**" button of any of the provided queries
At this point, the query should be added automatically to the code editor, but the "Run" button should remain visible. …
=> RI-7547 Stop showing tooltip suggestions in the editor when inserting saved queries

redisinsight/ui/src/components/base/popover/RiPopover.tsx, redisinsight/ui/src/components/table-column-search-trigger/TableColumnSearchTrigger.spec.tsx, redisinsight/ui/src/components/table-column-search-trigger/TableColumnSearchTrigger.tsx
https://github.com/user-attachments/assets/efbc9902-7669-4e61-b653-be0870a37373
https://github.com/user-attachments/assets/aaa74adf-d587-4306-8dca-f244a3dbe06b
=> [RI-7552] pressing ESC on a keyboard should close popups and unfocus from active input

redisinsight/ui/src/components/multi-search/MultiSearch.tsx, redisinsight/ui/src/components/multi-search/styles.module.scss
| --- | --- |
| <img width="93" height="71" alt="Screenshot 2025-10-01 at 10 43 48" src="https://github.com/user-attachments/assets/68b05d51-eb86-4c03-b11a-9a7398bac0f8" /> | <img width="102" height="69" alt="Screenshot 2025-10-01 at 10 41 46" src="https://github.com/user-attachments/assets/60fc7c0f-047a-4c7c-882f-a7b0681ca908" /> |
| <img width="87" height="58" alt="Screenshot 2025-10-01 at 10 43 56" src="https://github.com/user-attachments/assets/9bba9569-7752-47cc-87c9-99ebba653aa1" /> | <img width="93" height="56" alt="Screenshot 2025-10-01 at 10 41 32" src="https://github.com/user-attachments/assets/197ab232-1ec0-4153-b115-8d0b6c8d1484" /> |
=> RI-7520: fix icons spacing for multi search input

redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-name/KeyDetailsHeaderName.tsx, redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-name/styles.module.scss
Icons placing seemed off. Ideally we'd be able to set dynamic width but redis ui input does not support that.
https://github.com/user-attachments/assets/078828d7-b827-4e2e-a5c9-3469ff7446c5
https://github.com/user-attachments/assets/6407e13b-0867-4266-91e5-8c75f191d4a3
=> RI-7401: fix key name input layout on focus

redisinsight/ui/src/pages/vector-search/components/no-data-message/data.ts, redisinsight/ui/src/pages/vector-search/query/HeaderActions.spec.tsx, redisinsight/ui/src/pages/vector-search/query/HeaderActions.tsx, redisinsight/ui/src/pages/vector-search/query/VectorSearchQuery.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.spec.tsx, redisinsight/ui/src/pages/vector-search/saved-queries/SavedQueriesScreen.tsx, tests/playwright/pageObjects/pages/vector-search/vector-search-page.ts, tests/playwright/tests/vector-search/saved-queries.spec.ts
Rename "Saved queries" to "Sample queries" everywhere in the new Search page
- button in the top right corner used to open the respective panel
- title of the panel
- fallback message when there is no data
2. Go to the **Search** tab from the main navbar
3. Open the **Sample Queries** panel from the top right corner
You can always refer to the README, but simply running the following commands should do the trick for you
```
yarn dev:api
yarn dev:ui
yarn test:chromium:local-web vector-search/saved-queries
yarn playwright show-report
```
=> RI-7573 Rename "Saved queries" to "Sample queries"

redisinsight/ui/src/pages/browser/BrowserPage.tsx, redisinsight/ui/src/templates/instance-page-template/InstancePageTemplate.tsx
1. Fix the moving on the bottom group component (containing the CLI / Command Helper / Profiler badges)
**Before:**
https://github.com/user-attachments/assets/acd3838b-973e-4091-9912-86daa1da80d3
**After:**
https://github.com/user-attachments/assets/4933f9a0-204b-4d51-932a-33c8ae4eb452
2. Change the border radius of the key details panel to match the border radius on the key list panel
| --- | --- |
| <img width="526" height="342" alt="image" src="https://github.com/user-attachments/assets/92cce7b9-ee10-45da-8be1-1814f9de8bd2" /> | <img width="610" height="494" alt="image" src="https://github.com/user-attachments/assets/52332791-89a8-4bb1-86e3-77e2684cda9d" /> |
=> RI-7560: fix bottom group panel movement when expand / collapse

redisinsight/ui/src/styles/themes/dark_theme/_theme_color.scss
https://github.com/user-attachments/assets/ea46d4df-1fd2-436e-8631-cb30868b7b9e
| Before                                                                                                                                                          | After                                                                                                                                                           |
| --------------------------------------------------------------------------------------------------------------------------------------------------------------- | --------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| <img width="1466" height="323" alt="Screenshot 2025-10-02 at 13 …
=> RI-7537: Update dark theme table hover color

redisinsight/ui/src/assets/img/no-data.svg, redisinsight/ui/src/components/explore-guides/ExploreGuides.tsx, redisinsight/ui/src/components/explore-guides/styles.module.scss, redisinsight/ui/src/pages/browser/components/load-sample-data/LoadSampleData.tsx, redisinsight/ui/src/pages/browser/components/no-keys-found/NoKeysFound.tsx, redisinsight/ui/src/pages/browser/components/no-keys-found/styles.module.scss
Update visuals of the **Browser** page when the database is empty:
- change the image when there are no kays available
- change the buttons for importing sample data
- change the buttons for the tutorials
_Note: Redis UI colors do not match what we have in Figma. Still, I rely on the default behavior, so we can inherit any updates in the future (potential color fixes)._
| - | - |
2. Open the **Browser** tab from the top navigation
_Note: Make sure that you have a clean database. If not, you can run `flushdb` in the CLI._
=> RI-7589 Update visuals of the Browser page when the database is empty

redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-name/KeyDetailsHeaderName.tsx, redisinsight/ui/src/pages/browser/modules/key-details-header/components/key-details-header-name/styles.module.scss
Changed icons placing and set dynamic width for key name editor
Also hided copy icon during editing (confirmed)
https://github.com/user-attachments/assets/5d5ba523-1043-4fc0-be6c-4058deb9f9c9
=> RI-7401: fix key name edit controls

redisinsight/ui/src/pages/workbench/components/wb-no-results-message/WbNoResultsMessage.tsx
=> RI-7619: replace blue text in WB

redisinsight/ui/src/components/markdown/CodeButtonBlock/components/RunConfirmationPopover.tsx, redisinsight/ui/src/components/navigation-menu/components/notifications-center/Notification/Notification.tsx, redisinsight/ui/src/pages/browser/components/load-sample-data/styles.module.scss, redisinsight/ui/src/pages/browser/modules/key-details/components/list-details/remove-list-elements/RemoveListElements.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/components/add-item/ConfirmOverwrite.tsx, redisinsight/ui/src/pages/browser/modules/key-details/components/rejson-details/styles.module.scss, redisinsight/ui/src/styles/components/_popover.scss
Update the colors of the "**Import sample data**" popover to follow the color palette defined by Redis UI.
a.k.a remove a custom color override introduced for EUI 4 years ago.
| - | - |
2. Open the **Browser** tab from the top navigation
_Note: Make sure that you have a clean database. If not, you can run flushdb in the CLI._
| - | - |
Also, this is a global change, so it does affect all the popovers in the application that was using the blue color. Now, they all should follow the Redis UI color palette.
1. Open the **Insights** panel from the top right corner
2. Open the **Tutorials** tab
3. Pick the "**How To Query Your Data**" tutorial …
=> RI-7598 Change visuals of the "Import sample data" popover

redisinsight/ui/src/components/query/query-actions/QueryActions.styles.ts, redisinsight/ui/src/components/query/query-actions/QueryActions.tsx, redisinsight/ui/src/components/query/query-card/styles.module.scss
RI-7609: replace custom action buttons with ToggleButton
RI-7607: replace purple border with colors we use in keys list on hover
|Before|After|
|-|-|
=> RI-7607,7609: fix colors in wb
